# Income Statement

In [488]:
import yfinance as yf
import os
import requests
import pandas as pd
import urllib3
import json
import numpy as np
from bs4 import BeautifulSoup
from sqlalchemy import create_engine, Column, String, Date, Numeric, MetaData, Table

In [ ]:
#vantage api key
API_KEY = "875S8KE5GDSRVN1Z"
#disable certificate warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

tickerName = yf.Ticker("HINDCOPPER") #MSFT #HINDCOPPER #PLTR
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [490]:
CACHE_DIR = "offline_statements"
if not os.path.exists(CACHE_DIR):
    os.makedirs(CACHE_DIR)
    print(f"Created folder: {CACHE_DIR}")

In [491]:
#HOME_PC_DB

engine = create_engine(
    "postgresql+psycopg2://postgres:123456@localhost:5432/postgres"
)

In [492]:

def get_yfinance_income_statement(ticker, statement_type,freq,cache_dir=CACHE_DIR):
  #freq
  if freq not in ("quarterly", "yearly"):
        raise ValueError("freq must be 'quarterly' or 'yearly'")
  #path
  if not os.path.exists(cache_dir):
    os.mkdir(cache_dir)
   #filename 
  filename = f"yfinance_{ticker}_{statement_type}_{freq}.json"
  file_path = os.path.join(cache_dir, filename)
   #load from cache 
  if os.path.exists(file_path):
    print(f"Loading yfinance {file_path} from local cache")
    with open(file_path,'r') as f:
      return pd.read_json(file_path)
  
  print(f"Fetching {ticker} {statement_type} from Yfinance")
  #call yfinance
  df = tickerName.get_income_stmt(
        as_dict=False,
        pretty=False,
        freq=freq
    )

  if df is None or df.empty:   
    print(f"No {freq} income statement available from yfinance")
    return None
  #save file
  with open(file_path, "w") as f:
          df.to_json(file_path)

  print(f"Saved yfinance {ticker} income {freq} to cache")
  
  return df

In [493]:
# Store the raw result
raw_data_q = get_yfinance_income_statement(tickerName.ticker, "INCOME_STATEMENT", "quarterly")
raw_data_y = get_yfinance_income_statement(tickerName.ticker, "INCOME_STATEMENT", "yearly")

# check if has data and covert to dataframe
if raw_data_q is not None and raw_data_y is not None:
    
    dfIncomeStatementQ = pd.DataFrame(raw_data_q)
    dfIncomeStatementY = pd.DataFrame(raw_data_y)
    display(dfIncomeStatementQ)
    
    if not dfIncomeStatementQ.empty and not dfIncomeStatementY.empty:
        use_yfinance = True
        print("Yfinance data loaded successfully. Setting use_yfinance = True.")
    else:
        use_yfinance = False
        print("Yfinance returned empty DataFrames. Falling back...")
else:
    
    use_yfinance = False
    dfIncomeStatementQ = None
    dfIncomeStatementY = None
    print("Yfinance data incomplete. Falling back to Alpha Vantage...")

Loading yfinance offline_statements\yfinance_HINDCOPPER.NS_INCOME_STATEMENT_quarterly.json from local cache
Loading yfinance offline_statements\yfinance_HINDCOPPER.NS_INCOME_STATEMENT_yearly.json from local cache

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
TaxEffectOfUnusualItems,0.00,0.00,0.00,-64561459.63,0.00,NaN
TaxRateForCalcs,0.26,0.25,0.25,0.27,0.26,NaN
NormalizedEBITDA,2145500000.00,2490700000.00,1810000000.00,2796177000.00,857400000.00,NaN
TotalUnusualItems,0.00,0.00,0.00,-241712000.00,0.00,NaN
TotalUnusualItemsExcludingGoodwill,0.00,0.00,0.00,-241712000.00,0.00,NaN
NetIncomeFromContinuingOperationNetMinorityInterest,1563000000.00,1860200000.00,1342800000.00,1894891000.00,628700000.00,NaN
ReconciledDepreciation,NaN,NaN,NaN,NaN,376300000.00,NaN
ReconciledCostOfRevenue,500300000.00,1069600000.00,491800000.00,10358451000.00,-317000000.00,NaN
EBITDA,2145500000.00,2490700000.00,1810000000.00,2554465000.00,857400000.00,NaN
EBIT,2145500000.00,2490700000.00,1810000000.00,2554465000.00,857400000.00,NaN
NetInterestIncome,-20300000.00,-4400000.00,-16400000.00,85314000.00,-13100000.00,NaN
InterestExpense,20300000.00,4400000.00,16400000.00,-30829000.00,13100000.00,NaN
NormalizedIncome,1563000000.00,1860200000.00,1342800000.00,2072041540.37,628700000.00,NaN
NetIncomeFromContinuingAndDiscontinuedOperation,1563000000.00,1860200000.00,1342800000.00,1894891000.00,628700000.00,NaN
TotalExpenses,4907600000.00,4798800000.00,3456500000.00,4357226000.00,2578300000.00,NaN
DilutedAverageShares,964382716.00,972433862.00,965827338.00,NaN,967230769.00,968285714.00
BasicAverageShares,964382716.00,972433862.00,965827338.00,NaN,967230769.00,968285714.00
DilutedEPS,1.62,1.89,1.39,NaN,0.65,1.05
BasicEPS,1.62,1.89,1.39,NaN,0.65,1.05
DilutedNIAvailtoComStockholders,1562300000.00,1837900000.00,1342500000.00,1871760000.00,628700000.00,NaN
NetIncomeCommonStockholders,1562300000.00,1837900000.00,1342500000.00,1871760000.00,628700000.00,NaN
OtherunderPreferredStockDividend,0.00,0.00,0.00,0.00,0.00,NaN
NetIncome,1562300000.00,1837900000.00,1342500000.00,1871760000.00,628700000.00,NaN
MinorityInterests,0.00,0.00,0.00,131000.00,0.00,NaN
NetIncomeIncludingNoncontrollingInterests,1563000000.00,1837900000.00,1342500000.00,1871629000.00,628700000.00,NaN
NetIncomeExtraordinary,-700000.00,-22300000.00,-300000.00,-23131000.00,0.00,NaN
NetIncomeDiscontinuousOperations,0.00,0.00,0.00,0.00,0.00,NaN
NetIncomeContinuousOperations,1563000000.00,1860200000.00,1342500000.00,1894760000.00,628700000.00,NaN
TaxProvision,562200000.00,626100000.00,450800000.00,690534000.00,215600000.00,NaN
PretaxIncome,2125200000.00,2486300000.00,1793600000.00,2585294000.00,844300000.00,NaN
OtherNonOperatingIncomeExpenses,179700000.00,109100000.00,102800000.00,-93453000.00,158000000.00,NaN
SpecialIncomeCharges,0.00,0.00,0.00,-245761000.00,0.00,NaN
NetNonOperatingInterestIncomeExpense,-20300000.00,-4400000.00,-16400000.00,85314000.00,-13100000.00,NaN
InterestExpenseNonOperating,20300000.00,4400000.00,16400000.00,17500000.00,13100000.00,NaN
OperatingIncome,1965800000.00,2381600000.00,1707200000.00,2836674000.00,699400000.00,NaN
OperatingExpense,4407300000.00,3729200000.00,2964700000.00,-6001225000.00,2895300000.00,NaN
OtherOperatingExpenses,2489400000.00,2807800000.00,2162400000.00,-6165563000.00,2146900000.00,NaN
DepreciationAndAmortizationInIncomeStatement,NaN,NaN,NaN,NaN,376300000.00,NaN
DepreciationIncomeStatement,NaN,NaN,NaN,NaN,376300000.00,NaN
GrossProfit,6373100000.00,6110800000.00,4671900000.00,-3164551000.00,3594700000.00,NaN
CostOfRevenue,500300000.00,1069600000.00,491800000.00,10358451000.00,-317000000.00,NaN
TotalRevenue,6873400000.00,7180400000.00,5163700000.00,7193900000.00,3277700000.00,NaN
OperatingRevenue,6873400000.00,7180400000.00,5163700000.00,7193900000.00,3277700000.00,NaN

Yfinance data loaded successfully. Setting use_yfinance = True.

In [494]:

def get_alpha_vantage_statement(ticker, statement_type, api_key, cache_dir=CACHE_DIR):
    # Create Local Storage Directory
    if not os.path.exists(cache_dir):
        os.makedirs(cache_dir)
    
    # Define Local File Path
    filename = f"vantage_{ticker}_{statement_type}.json"
    file_path = os.path.join(cache_dir, filename)
    
    # Check Local First: Load from disk if it exists
    if os.path.exists(file_path):
        print(f"Loading vantage {ticker} {statement_type} from local cache")
        with open(file_path, 'r') as f:
            return json.load(f)
    
    #  Download and Save: Ping API if file doesn't exist
    print(f"Fetching {ticker} {statement_type} from Alpha Vantage")
    url = (f"https://www.alphavantage.co/query"
           f"?function={statement_type}"
           f"&symbol={ticker}"
           f"&apikey={api_key}")
    
    try:
        # verify=False used as per your original script
        response = requests.get(url, verify=False, timeout=20)
        data = response.json()
        
        # Validate data before saving (basic check for valid reports)
        if "quarterlyReports" in data:
            with open(file_path, 'w') as f:
                json.dump(data, f)
            print(f"Successfully saved {ticker} to local cache.")
            return data
        else:
            # Handle rate limits or errors from the API
            error_msg = data.get("Note", data.get("Error Message", "Unknown Error"))
            print(f"Alpha Vantage Error/Limit: {error_msg}")
            return None
            
    except Exception as e:
        print(f"Request failed: {e}")
        return None

In [495]:
# Initial Fallback State
alpha_vantage = False

if dfIncomeStatementQ is None or dfIncomeStatementY is None:
    # Use the new fetch/cache function
    ticker = tickerName.ticker
    av_data = get_alpha_vantage_statement(ticker, 'INCOME_STATEMENT', API_KEY)
    
    if av_data:
        alpha_vantage_income_statement_quarterly = av_data["quarterlyReports"]
        alpha_vantage_income_statement_yearly = av_data["annualReports"]
        alpha_vantage = True

# Standard Status Checks
if not alpha_vantage and dfIncomeStatementQ is not None:
    print("Using yfinance statements.")
elif not alpha_vantage and dfIncomeStatementQ is None:
    print("CRITICAL: No data found in yfinance OR local Alpha Vantage cache.")

Using yfinance statements.

In [496]:

if alpha_vantage:

  dfIncomeStatementQ = pd.DataFrame(alpha_vantage_income_statement_quarterly)
  dfIncomeStatementY =  pd.DataFrame(alpha_vantage_income_statement_yearly)
  
  dfIncomeStatementQ = dfIncomeStatementQ.set_index("fiscalDateEnding")
  dfIncomeStatementY = dfIncomeStatementY.set_index("fiscalDateEnding")

  display(dfIncomeStatementQ)
  display(dfIncomeStatementY)

In [497]:
#SCREENER SCRAPPER
import urllib.parse
import os
import json
import requests
from bs4 import BeautifulSoup

def get_screener_financials(ticker, report_type="yearly"):
    filename = f"screener_{ticker}_{report_type}.json"
    file_path = os.path.join(CACHE_DIR, filename)

    # Check Cache
    if os.path.exists(file_path):
        print(f"Loading {ticker} {report_type} from Screener cache...")
        with open(file_path, 'r') as f:
            return json.load(f)
  
    # Use a Session to retain cookies across requests
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "X-Requested-With": "XMLHttpRequest" # Tells Screener this is an AJAX API call
    })
    
    url = f"https://www.screener.in/company/{ticker}/"
    response = session.get(url)
    
    if response.status_code != 200:
        print(f"Error fetching Screener page: {response.status_code}")
        return None
    
    soup = BeautifulSoup(response.text, "html.parser")
    
    # Extract the hidden Company ID for sub item api
    company_div = soup.find(attrs={"data-company-id": True})
    if not company_div:
        print(f"Could not find company ID for {ticker}")
        return None
    company_id = company_div["data-company-id"]
    
    # Identify the section ID
    section_id = "quarters" if report_type == "quarterly" else "profit-loss"
    statement_section = soup.find("section", {"id": section_id})
    
    if not statement_section:
        print(f"Could not find {report_type} section for {ticker}")
        return None
  
    table = statement_section.find("table", class_="data-table")
    
    if table:
        # Date columns (Headers)
        headers = [th.get_text(strip=True) for th in table.find("thead").find_all("th")][1:]
        financial_data = {date: {} for date in headers}
        
        # Parse Rows (Main Line Items)
        for tr in table.find("tbody").find_all("tr"):
            cells = tr.find_all("td")
            if cells:
                row_label_cell = cells[0]
                row_label = row_label_cell.get_text(strip=True).replace("+", "").strip()
                
                # extract the main row values
                row_values = [td.get_text(strip=True).replace(",", "") for td in cells[1:]]
                for i, date in enumerate(headers):
                    if i < len(row_values):
                        financial_data[date][row_label] = row_values[i]
                
                button = row_label_cell.find("button")
                if button:
                    safe_parent = urllib.parse.quote(row_label)
                    api_url = f"https://www.screener.in/api/company/{company_id}/schedules/?parent={safe_parent}&section={section_id}"
                    
                    try:
                        sub_response = session.get(api_url)
                        if sub_response.status_code == 200:
                            sub_data = sub_response.json()
                            
                            for sub_label, date_values in sub_data.items():
                                final_label = f"{sub_label}"
                                
                                for d in headers:
                                    financial_data[d][final_label] = "0"
                                
                                for date_key, val in date_values.items():
                                    # Clean the date strings to ensure a perfect match
                                    clean_api_date = date_key.strip()
                                    
                                    if clean_api_date in financial_data:
                                        # Store the value, removing commas
                                        financial_data[clean_api_date][final_label] = str(val).replace(",", "")
                        else:
                            print(f"    - API Error: {sub_response.status_code}")
                            
                    except Exception as e:
                        print(f"    - Assignment failed for '{row_label}': {e}")
                    
        print(f"\nFinalized scraping {report_type} data from Screener.")           
        with open(file_path, 'w') as f:
            json.dump(financial_data, f)
              
        return financial_data
    
    return None

In [498]:

if not use_yfinance and not alpha_vantage:
  dfIncomeStatementQ = pd.DataFrame(get_screener_financials(tickerName.ticker, report_type='quarterly'))
  dfIncomeStatementY = pd.DataFrame(get_screener_financials(tickerName.ticker, report_type='yearly'))
  display(dfIncomeStatementQ)
  display(dfIncomeStatementY.index)

In [499]:


dfIncomeStatementQ = dfIncomeStatementQ.replace(r'[%,+]', '', regex=True).apply(pd.to_numeric, errors='coerce').fillna(0)
dfIncomeStatementY = dfIncomeStatementY.replace(r'[%,+]', '', regex=True).apply(pd.to_numeric, errors='coerce').fillna(0)
#Income Statement Item Fallbacks

#NetInterestIncome
if 'NetInterestIncome' not in dfIncomeStatementQ.index:
    if 'PretaxIncome' in dfIncomeStatementQ.index and 'OperatingIncome' in dfIncomeStatementQ.index:
        # Calculate the items if labels exist
        dfIncomeStatementQ.loc['NetInterestIncome'] = dfIncomeStatementQ.loc['PretaxIncome'] - dfIncomeStatementQ.loc['OperatingIncome']
        
    elif 'Profit before tax' in dfIncomeStatementQ.index and 'Operating Profit' in dfIncomeStatementQ.index:
        dfIncomeStatementQ.loc['NetInterestIncome'] = dfIncomeStatementQ.loc['Profit before tax'] - dfIncomeStatementQ.loc['Operating Profit']
        # safety
    else:
        dfIncomeStatementQ.loc['NetInterestIncome'] = 0

if 'NetInterestIncome' not in dfIncomeStatementY.index:
    if 'PretaxIncome' in dfIncomeStatementY.index and 'OperatingIncome' in dfIncomeStatementY.index:
        dfIncomeStatementY.loc['NetInterestIncome'] = dfIncomeStatementY.loc['PretaxIncome'] - dfIncomeStatementY.loc['OperatingIncome']
    elif 'Profit before tax' in dfIncomeStatementQ.index and 'Operating Profit' in dfIncomeStatementQ.index:
        dfIncomeStatementY.loc['NetInterestIncome'] = dfIncomeStatementY.loc['Profit before tax'] - dfIncomeStatementY.loc['Operating Profit']
        # safety
    else:
        dfIncomeStatementY.loc['NetInterestIncome'] = 0

#CostOfRevenue   
if 'CostOfRevenue' not in dfIncomeStatementQ.index:
    cost_keys = ['Material Cost %', 'Manufacturing Cost %']
    total_cost_pct = dfIncomeStatementQ.reindex(cost_keys, fill_value=0).sum()
    dfIncomeStatementQ.loc['CostOfRevenue'] = dfIncomeStatementQ.loc['Sales'] * total_cost_pct / 100

        
if 'CostOfRevenue' not in dfIncomeStatementY.index:
    if 'Material Cost %' in dfIncomeStatementY.index and 'Manufacturing Cost %' in dfIncomeStatementY.index:
        dfIncomeStatementY.loc['CostOfRevenue'] = dfIncomeStatementY.loc['Sales'] * (dfIncomeStatementY.loc['Material Cost %'] + dfIncomeStatementY.loc['Manufacturing Cost %'])/100
    else:
        dfIncomeStatementY.loc['CostOfRevenue'] = 0
        
#GrossProfit      
if 'GrossProfit' not in dfIncomeStatementQ.index:
    if 'Sales' in dfIncomeStatementQ.index and 'CostOfRevenue' in dfIncomeStatementQ.index:
        dfIncomeStatementQ.loc['GrossProfit'] = dfIncomeStatementQ.loc['Sales'] - dfIncomeStatementQ.loc['CostOfRevenue']
    else:
        dfIncomeStatementQ.loc['GrossProfit'] = 0
        
if 'GrossProfit' not in dfIncomeStatementY.index:
    if 'Sales' in dfIncomeStatementY.index and 'CostOfRevenue' in dfIncomeStatementY.index:
        dfIncomeStatementY.loc['GrossProfit'] = dfIncomeStatementY.loc['Sales'] - dfIncomeStatementY.loc['CostOfRevenue']
    else:
        dfIncomeStatementY.loc['GrossProfit'] = 0
        
#Operating Expense
if 'OperatingExpense' not in dfIncomeStatementQ.index:
    
    cost_keys = ['Employee Cost %', 'Other Cost %']
    total_cost_pct = dfIncomeStatementQ.reindex(cost_keys, fill_value=0).sum()
    dfIncomeStatementQ.loc['OperatingExpense'] = dfIncomeStatementQ.loc['Sales'] * total_cost_pct / 100
    
        
if 'OperatingExpense' not in dfIncomeStatementY.index:
    if 'Employee Cost %' in dfIncomeStatementY.index and 'Other Cost %' in dfIncomeStatementY.index:
        dfIncomeStatementY.loc['OperatingExpense'] = dfIncomeStatementY.loc['Sales'] * (dfIncomeStatementY.loc['Employee Cost %'] + dfIncomeStatementY.loc['Other Cost %'])/100


#TaxProvision
if 'TaxProvision' not in dfIncomeStatementQ.index:
    if 'Profit before tax' in dfIncomeStatementQ.index and 'Net Profit' in dfIncomeStatementQ.index:
        dfIncomeStatementQ.loc['TaxProvision'] = dfIncomeStatementQ.loc['Profit before tax'] - dfIncomeStatementQ.loc['Net Profit']
    else:
        dfIncomeStatementQ.loc['TaxProvision'] = 0
        
if 'TaxProvision' not in dfIncomeStatementY.index:
    if 'Profit before tax' in dfIncomeStatementY.index and 'Net Profit' in dfIncomeStatementY.index:
        dfIncomeStatementY.loc['TaxProvision'] = dfIncomeStatementY.loc['Profit before tax'] - dfIncomeStatementY.loc['Net Profit']
    else:
        dfIncomeStatementY.loc['TaxProvision'] = 0

In [500]:



#alphas_vantage columns to ittelson mapping
alpha_to_ittelsons_col_map = {
    "totalRevenue": "TotalRevenue",
    "costOfRevenue": "CostOfRevenue",
    "Operating Profit": "GrossProfit",
    "operatingExpenses": "OperatingExpense",
    "operatingIncome": "OperatingIncome",
    "netInterestIncome": "NetInterestIncome",
    "incomeTaxExpense": "TaxProvision", 
    "netIncome": "NetIncome",
}

screener_to_ittelsons_col_map = {
    "Sales": "TotalRevenue",
    "CostOfRevenue": "CostOfRevenue",
    "GrossProfit": "GrossProfit",
    "OperatingExpense": "OperatingExpense",
    "Operating Profit": "OperatingIncome",
    "NetInterestIncome": "NetInterestIncome",
    "TaxProvision": "TaxProvision",
    "Net Profit": "NetIncome",
}

ittelson_income_statement_columns = [
    'TotalRevenue', 
    'CostOfRevenue', 
    'GrossProfit',
    'OperatingExpense',
    'OperatingIncome',
    'NetInterestIncome',
    'TaxProvision',
    'NetIncome'
]

if alpha_vantage:
    #rename av columns to uniform ittleson columns
    dfIncomeStatementQ = dfIncomeStatementQ.rename(columns=alpha_to_ittelsons_col_map)
    dfIncomeStatementY = dfIncomeStatementY.rename(columns=alpha_to_ittelsons_col_map)
    
    #Filter, reset and rename fisacalDate column, add ticker column, replace none and change data types from string to numeric
    clean_quarterly_income_statement = dfIncomeStatementQ.loc[:,ittelson_income_statement_columns]
    clean_quarterly_income_statement = clean_quarterly_income_statement.reset_index()
    clean_quarterly_income_statement = clean_quarterly_income_statement.rename(columns={'fiscalDateEnding': 'ReportDate'})
    clean_quarterly_income_statement.insert(1,'Ticker',tickerName.ticker)
    clean_quarterly_income_statement = clean_quarterly_income_statement.replace('None',np.nan)
    display(clean_quarterly_income_statement)

    clean_yearly_income_statement = dfIncomeStatementY.loc[:,ittelson_income_statement_columns]
    clean_yearly_income_statement = clean_yearly_income_statement.reset_index()
    clean_yearly_income_statement = clean_yearly_income_statement.rename(columns={'fiscalDateEnding': 'ReportDate'})
    clean_yearly_income_statement.insert(1,'Ticker',tickerName.ticker)
    clean_yearly_income_statement = clean_yearly_income_statement.replace('None',np.nan)
    display(clean_yearly_income_statement)
    
elif use_yfinance:
    print("Processing Yfinance data...")
    # Yfinance needs .T because metrics are the index, we want dates as the index
    clean_quarterly_income_statement = dfIncomeStatementQ.T.loc[:, ittelson_income_statement_columns]
    clean_quarterly_income_statement = clean_quarterly_income_statement.reset_index()
    clean_quarterly_income_statement = clean_quarterly_income_statement.rename(columns={'index': 'ReportDate'})
    clean_quarterly_income_statement.insert(1,'Ticker',tickerName.ticker)
    display(clean_quarterly_income_statement)

    clean_yearly_income_statement = dfIncomeStatementY.T.loc[:, ittelson_income_statement_columns]
    clean_yearly_income_statement = clean_yearly_income_statement.reset_index()
    clean_yearly_income_statement = clean_yearly_income_statement.rename(columns={'index': 'ReportDate'})
    clean_yearly_income_statement.insert(1,'Ticker',tickerName.ticker)
    display(clean_yearly_income_statement)
else:
    print("Processing Screener data...")
    # Screener also needs .T (transpose) to move dates from columns to rows
    dfQ_T = dfIncomeStatementQ.T.rename(columns=screener_to_ittelsons_col_map)
    dfY_T = dfIncomeStatementY.T.rename(columns=screener_to_ittelsons_col_map).iloc[:-1]
    
    
    clean_quarterly_income_statement = dfQ_T.loc[:, ittelson_income_statement_columns]
    clean_quarterly_income_statement = clean_quarterly_income_statement.reset_index()
    clean_quarterly_income_statement = clean_quarterly_income_statement.rename(columns={'index': 'ReportDate'})
    clean_quarterly_income_statement["ReportDate"] = (pd.to_datetime(clean_quarterly_income_statement["ReportDate"]) + pd.offsets.MonthEnd(0)).dt.strftime('%Y-%m-%d')
    clean_quarterly_income_statement.insert(1,'Ticker',tickerName.ticker)
    display(clean_quarterly_income_statement)

    clean_yearly_income_statement = dfY_T.loc[:, ittelson_income_statement_columns]
    clean_yearly_income_statement = clean_yearly_income_statement.reset_index()
    clean_yearly_income_statement = clean_yearly_income_statement.rename(columns={'index': 'ReportDate'})
    clean_yearly_income_statement["ReportDate"] = (pd.to_datetime(clean_yearly_income_statement["ReportDate"]) + pd.offsets.MonthEnd(0)).dt.strftime('%Y-%m-%d')
    clean_yearly_income_statement.insert(1,'Ticker',tickerName.ticker)
    display(clean_yearly_income_statement)

Processing Yfinance data...

,ReportDate,Ticker,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
0,2025-12-31,HINDCOPPER.NS,6873400000.00,500300000.00,6373100000.00,4407300000.00,1965800000.00,-20300000.00,562200000.00,1562300000.00
1,2025-09-30,HINDCOPPER.NS,7180400000.00,1069600000.00,6110800000.00,3729200000.00,2381600000.00,-4400000.00,626100000.00,1837900000.00
2,2025-06-30,HINDCOPPER.NS,5163700000.00,491800000.00,4671900000.00,2964700000.00,1707200000.00,-16400000.00,450800000.00,1342500000.00
3,2025-03-31,HINDCOPPER.NS,7193900000.00,10358451000.00,-3164551000.00,-6001225000.00,2836674000.00,85314000.00,690534000.00,1871760000.00
4,2024-12-31,HINDCOPPER.NS,3277700000.00,-317000000.00,3594700000.00,2895300000.00,699400000.00,-13100000.00,215600000.00,628700000.00
5,2024-09-30,HINDCOPPER.NS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

,ReportDate,Ticker,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
0,2025-03-31,HINDCOPPER.NS,20589500000.00,10164751000.00,10424749000.00,4111475000.00,6313274000.00,33514000.00,1649834000.00,4651160000.00
1,2024-03-31,HINDCOPPER.NS,17045653000.00,9264690000.00,7780963000.00,3840998000.00,3939965000.00,82920000.00,1150183000.00,2953068000.00
2,2023-03-31,HINDCOPPER.NS,16651354000.00,8980240000.00,7671114000.00,4092188000.00,3578926000.00,44008000.00,1003507000.00,2954594000.00
3,2022-03-31,HINDCOPPER.NS,18038653000.00,9055561000.00,8983092000.00,4786884000.00,4196208000.00,-126786000.00,80296000.00,3738284000.00

In [501]:

metadata = MetaData(schema='public')

#Define the architecture
quarterly_income_statement = Table(
    'quarterly_income_statement', metadata,
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)
#Define the architecture
yearly_income_statement = Table(
    'yearly_income_statement', metadata,
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)

#Build the table in the database
metadata.create_all(engine)
print("Tables created successfully.")

Tables created successfully.

In [502]:
#Insert DataFrames to Tables

import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

#Define the Custom Upsert Logic
def postgres_upsert(table, conn, keys, data_iter):
    """
    Native PostgreSQL UPSERT
    """
    # Convert Pandas data into a list of dictionaries
    data = [dict(zip(keys, row)) for row in data_iter]
    
    insert_stmt = insert(table.table).values(data)

    update_dict = {
    c.name: getattr(insert_stmt.excluded, c.name)
    for c in table.table.columns
    if c.name not in ("Ticker", "ReportDate")
}
    
    upsert_stmt = insert_stmt.on_conflict_do_update(
        index_elements=['Ticker', 'ReportDate'], 
        set_=update_dict
    )
    
    conn.execute(upsert_stmt)


# Push the data using the custom Upsert method
clean_quarterly_income_statement.to_sql(
    name='quarterly_income_statement',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

clean_yearly_income_statement.to_sql(
    name='yearly_income_statement',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

print("Data successfully upserted into the database.")

Data successfully upserted into the database.

# Balance Sheet

In [503]:
# Store the raw result
raw_data_q = get_yfinance_income_statement(tickerName.ticker, "BALANCE_SHEET", "quarterly")
raw_data_y = get_yfinance_income_statement(tickerName.ticker, "BALANCE_SHEET", "yearly")

# check if has data and covert to dataframe
if raw_data_q is not None and raw_data_y is not None:
    
    dfIncomeStatementQ = pd.DataFrame(raw_data_q)
    dfIncomeStatementY = pd.DataFrame(raw_data_y)
    display(dfIncomeStatementQ)
    
    if not dfIncomeStatementQ.empty and not dfIncomeStatementY.empty:
        use_yfinance = True
        print("Yfinance data loaded successfully. Setting use_yfinance = True.")
    else:
        use_yfinance = False
        print("Yfinance returned empty DataFrames. Falling back...")
else:
    
    use_yfinance = False
    dfIncomeStatementQ = None
    dfIncomeStatementY = None
    print("Yfinance data incomplete. Falling back to Alpha Vantage...")

Fetching HINDCOPPER.NS BALANCE_SHEET from Yfinance
Saved yfinance HINDCOPPER.NS income quarterly to cache
Fetching HINDCOPPER.NS BALANCE_SHEET from Yfinance
Saved yfinance HINDCOPPER.NS income yearly to cache

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
TaxEffectOfUnusualItems,0.00,0.00,0.00,-64561459.63,0.00,NaN
TaxRateForCalcs,0.26,0.25,0.25,0.27,0.26,NaN
NormalizedEBITDA,2145500000.00,2490700000.00,1810000000.00,2796177000.00,857400000.00,NaN
TotalUnusualItems,0.00,0.00,0.00,-241712000.00,0.00,NaN
TotalUnusualItemsExcludingGoodwill,0.00,0.00,0.00,-241712000.00,0.00,NaN
NetIncomeFromContinuingOperationNetMinorityInterest,1563000000.00,1860200000.00,1342800000.00,1894891000.00,628700000.00,NaN
ReconciledDepreciation,NaN,NaN,NaN,NaN,376300000.00,NaN
ReconciledCostOfRevenue,500300000.00,1069600000.00,491800000.00,10358451000.00,-317000000.00,NaN
EBITDA,2145500000.00,2490700000.00,1810000000.00,2554465000.00,857400000.00,NaN
EBIT,2145500000.00,2490700000.00,1810000000.00,2554465000.00,857400000.00,NaN
NetInterestIncome,-20300000.00,-4400000.00,-16400000.00,85314000.00,-13100000.00,NaN
InterestExpense,20300000.00,4400000.00,16400000.00,-30829000.00,13100000.00,NaN
NormalizedIncome,1563000000.00,1860200000.00,1342800000.00,2072041540.37,628700000.00,NaN
NetIncomeFromContinuingAndDiscontinuedOperation,1563000000.00,1860200000.00,1342800000.00,1894891000.00,628700000.00,NaN
TotalExpenses,4907600000.00,4798800000.00,3456500000.00,4357226000.00,2578300000.00,NaN
DilutedAverageShares,964382716.00,972433862.00,965827338.00,NaN,967230769.00,968285714.00
BasicAverageShares,964382716.00,972433862.00,965827338.00,NaN,967230769.00,968285714.00
DilutedEPS,1.62,1.89,1.39,NaN,0.65,1.05
BasicEPS,1.62,1.89,1.39,NaN,0.65,1.05
DilutedNIAvailtoComStockholders,1562300000.00,1837900000.00,1342500000.00,1871760000.00,628700000.00,NaN
NetIncomeCommonStockholders,1562300000.00,1837900000.00,1342500000.00,1871760000.00,628700000.00,NaN
OtherunderPreferredStockDividend,0.00,0.00,0.00,0.00,0.00,NaN
NetIncome,1562300000.00,1837900000.00,1342500000.00,1871760000.00,628700000.00,NaN
MinorityInterests,0.00,0.00,0.00,131000.00,0.00,NaN
NetIncomeIncludingNoncontrollingInterests,1563000000.00,1837900000.00,1342500000.00,1871629000.00,628700000.00,NaN
NetIncomeExtraordinary,-700000.00,-22300000.00,-300000.00,-23131000.00,0.00,NaN
NetIncomeDiscontinuousOperations,0.00,0.00,0.00,0.00,0.00,NaN
NetIncomeContinuousOperations,1563000000.00,1860200000.00,1342500000.00,1894760000.00,628700000.00,NaN
TaxProvision,562200000.00,626100000.00,450800000.00,690534000.00,215600000.00,NaN
PretaxIncome,2125200000.00,2486300000.00,1793600000.00,2585294000.00,844300000.00,NaN
OtherNonOperatingIncomeExpenses,179700000.00,109100000.00,102800000.00,-93453000.00,158000000.00,NaN
SpecialIncomeCharges,0.00,0.00,0.00,-245761000.00,0.00,NaN
NetNonOperatingInterestIncomeExpense,-20300000.00,-4400000.00,-16400000.00,85314000.00,-13100000.00,NaN
InterestExpenseNonOperating,20300000.00,4400000.00,16400000.00,17500000.00,13100000.00,NaN
OperatingIncome,1965800000.00,2381600000.00,1707200000.00,2836674000.00,699400000.00,NaN
OperatingExpense,4407300000.00,3729200000.00,2964700000.00,-6001225000.00,2895300000.00,NaN
OtherOperatingExpenses,2489400000.00,2807800000.00,2162400000.00,-6165563000.00,2146900000.00,NaN
DepreciationAndAmortizationInIncomeStatement,NaN,NaN,NaN,NaN,376300000.00,NaN
DepreciationIncomeStatement,NaN,NaN,NaN,NaN,376300000.00,NaN
GrossProfit,6373100000.00,6110800000.00,4671900000.00,-3164551000.00,3594700000.00,NaN
CostOfRevenue,500300000.00,1069600000.00,491800000.00,10358451000.00,-317000000.00,NaN
TotalRevenue,6873400000.00,7180400000.00,5163700000.00,7193900000.00,3277700000.00,NaN
OperatingRevenue,6873400000.00,7180400000.00,5163700000.00,7193900000.00,3277700000.00,NaN

Yfinance data loaded successfully. Setting use_yfinance = True.

In [504]:
ittelson_balance_sheet_columns = [
  #Assets
  'CashCashEquivalentsAndShortTermInvestments',
  'Receivables',
  'Inventory',
  'CurrentAssets',
  'TotalNonCurrentAssets',
  'GrossPPE',
  'AccumulatedDepreciation',
  'NetPPE',
  'TotalAssets',
  #Liabilities&Equity
  'PayablesAndAccruedExpenses',
  'CurrentDebtAndCapitalLeaseObligation',
  'TotalTaxPayable',
  'CurrentLiabilities',
  'LongTermDebtAndCapitalLeaseObligation',
  'TotalLiabilitiesNetMinorityInterest', #Current Liabilities + Long-Term Debt.
  'CapitalStock',
  'RetainedEarnings',
  'StockholdersEquity'
]