# Income Statement

In [556]:

import yfinance as yf
import os
import requests
import pandas as pd
import urllib3
import json
import re
import numpy as np
from bs4 import BeautifulSoup
from sqlalchemy import create_engine, Column, String, Date, Numeric, MetaData, Table
from sqlalchemy.dialects.postgresql import insert

In [557]:
#vantage api key
API_KEY = "V6FLFA1K7ECKP0RK"
#disable certificate warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

tickerName = yf.Ticker("PLTR") #MSFT #HINDCOPPER #PLTR
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [558]:
CACHE_DIR = "offline_statements"
if not os.path.exists(CACHE_DIR):
    os.makedirs(CACHE_DIR)
    print(f"Created folder: {CACHE_DIR}")

In [559]:
#HOME_PC_DB

engine = create_engine(
    "postgresql+psycopg2://postgres:123456@localhost:5432/postgres"
)

In [560]:

#Yfinance
def get_yfinance(ticker, statement_type,freq,cache_dir=CACHE_DIR):
  #freq
  if freq not in ("quarterly", "yearly"):
        raise ValueError("freq must be 'quarterly' or 'yearly'")
  #path
  if not os.path.exists(cache_dir):
    os.mkdir(cache_dir)
   #filename 
  filename = f"yfinance_{ticker}_{statement_type}_{freq}.json"
  file_path = os.path.join(cache_dir, filename)
   #load from cache 
  if os.path.exists(file_path):
    print(f"Loading yfinance {file_path} from local cache")
    with open(file_path,'r') as f:
      return pd.read_json(file_path)
  
  print(f"Fetching {ticker} {statement_type} from Yfinance")
  #call yfinance
  if statement_type == "INCOME_STATEMENT":
    df = tickerName.get_income_stmt(
          as_dict=False,
          pretty=False,
          freq=freq
      )
  elif statement_type == "BALANCE_SHEET":
       df = tickerName.get_balance_sheet(
          as_dict=False,
          pretty=False,
          freq=freq
      )
  elif statement_type == 'CASH_FLOW' and freq == 'yearly':
     df = tickerName.get_cash_flow(
          as_dict=False,
          pretty=False,
          freq=freq
      )
  else:
       df = tickerName.get_cash_flow(
          as_dict=False,
          pretty=False,
          freq=freq
      )
          
  if df is None or df.empty:   
    print(f"No {freq} income statement available from yfinance")
    return None
  #save file
  with open(file_path, "w") as f:
          df.to_json(file_path)

  print(f"Saved yfinance {ticker} income {freq} to cache")
  
  return df

In [561]:
# #call yfinace
raw_data_q = get_yfinance(tickerName.ticker, "INCOME_STATEMENT", "quarterly")
raw_data_y = get_yfinance(tickerName.ticker, "INCOME_STATEMENT", "yearly")

# check if has data and covert to dataframe
if raw_data_q is not None and raw_data_y is not None:
    
    dfIncomeStatementQ = pd.DataFrame(raw_data_q)
    dfIncomeStatementY = pd.DataFrame(raw_data_y)
    display(dfIncomeStatementQ.index)
    
    if not dfIncomeStatementQ.empty and not dfIncomeStatementY.empty:
        use_yfinance = True
        print("Yfinance data loaded successfully. Setting use_yfinance = True.")
    else:
        use_yfinance = False
        print("Yfinance returned empty DataFrames. Falling back...")
else:
    
    use_yfinance = False
    dfIncomeStatementQ = None
    dfIncomeStatementY = None
    print("Yfinance data incomplete. Falling back to Alpha Vantage...")

Loading yfinance offline_statements\yfinance_PLTR_INCOME_STATEMENT_quarterly.json from local cache
Loading yfinance offline_statements\yfinance_PLTR_INCOME_STATEMENT_yearly.json from local cache

Index(['TaxEffectOfUnusualItems', 'TaxRateForCalcs', 'NormalizedEBITDA',
       'NetIncomeFromContinuingOperationNetMinorityInterest',
       'ReconciledDepreciation', 'ReconciledCostOfRevenue', 'EBITDA', 'EBIT',
       'NetInterestIncome', 'InterestIncome', 'NormalizedIncome',
       'NetIncomeFromContinuingAndDiscontinuedOperation', 'TotalExpenses',
       'TotalOperatingIncomeAsReported', 'DilutedAverageShares',
       'BasicAverageShares', 'DilutedEPS', 'BasicEPS',
       'DilutedNIAvailtoComStockholders', 'NetIncomeCommonStockholders',
       'NetIncome', 'MinorityInterests',
       'NetIncomeIncludingNoncontrollingInterests',
       'NetIncomeContinuousOperations', 'TaxProvision', 'PretaxIncome',
       'OtherIncomeExpense', 'OtherNonOperatingIncomeExpenses',
       'NetNonOperatingInterestIncomeExpense', 'InterestIncomeNonOperating',
       'OperatingIncome', 'OperatingExpense', 'ResearchAndDevelopment',
       'SellingGeneralAndAdministration', 'SellingAndMarketingExpense',
       'GeneralAndAdministrativeExpense', 'OtherGandA', 'GrossProfit',
       'CostOfRevenue', 'TotalRevenue', 'OperatingRevenue'],
      dtype='str')

Yfinance data loaded successfully. Setting use_yfinance = True.

In [562]:
#use_yfinance = False
#dfIncomeStatementQ = None
#dfIncomeStatementY = None

In [563]:
#alpha vantage
def get_alpha_vantage(ticker, statement_type, api_key, cache_dir=CACHE_DIR):
    # Create Local Storage Directory
    if not os.path.exists(cache_dir):
        os.makedirs(cache_dir)
    
    # Define Local File Path
    filename = f"vantage_{ticker}_{statement_type}.json"
    file_path = os.path.join(cache_dir, filename)
    
    # Check Local First: Load from disk if it exists
    if os.path.exists(file_path):
        print(f"Loading vantage {ticker} {statement_type} from local cache")
        with open(file_path, 'r') as f:
            return json.load(f)
    
    #  Download and Save: Ping API if file doesn't exist
    print(f"Fetching {ticker} {statement_type} from Alpha Vantage")
    url = (f"https://www.alphavantage.co/query"
           f"?function={statement_type}"
           f"&symbol={ticker}"
           f"&apikey={api_key}")
    
    try:
        # verify=False used as per your original script
        response = requests.get(url, verify=False, timeout=20)
        data = response.json()
        
        # Validate data before saving (basic check for valid reports)
        if "quarterlyReports" in data:
            with open(file_path, 'w') as f:
                json.dump(data, f)
            print(f"Successfully saved {ticker} to local cache.")
            return data
        else:
            # Handle rate limits or errors from the API
            error_msg = data.get("Note", data.get("Error Message", "Unknown Error"))
            print(f"Alpha Vantage Error/Limit: {error_msg}")
            return None
            
    except Exception as e:
        print(f"Request failed: {e}")
        return None

In [564]:
#call alpha vantage
alpha_vantage = False

if dfIncomeStatementQ is None or dfIncomeStatementY is None:
    # Use the new fetch/cache function
    ticker = tickerName.ticker
    av_data = get_alpha_vantage(ticker, 'INCOME_STATEMENT', API_KEY)
    
    if av_data:
        alpha_vantage_income_statement_quarterly = av_data["quarterlyReports"]
        alpha_vantage_income_statement_yearly = av_data["annualReports"]
        alpha_vantage = True

# Standard Status Checks
if not alpha_vantage and dfIncomeStatementQ is not None:
    print("Using yfinance statements.")
elif not alpha_vantage and dfIncomeStatementQ is None:
    print("CRITICAL: No data found in yfinance OR local Alpha Vantage cache.")
    


if alpha_vantage:

  dfIncomeStatementQ = pd.DataFrame(alpha_vantage_income_statement_quarterly)
  dfIncomeStatementY =  pd.DataFrame(alpha_vantage_income_statement_yearly)
  

  dfIncomeStatementQ = dfIncomeStatementQ.set_index("fiscalDateEnding").rename_axis(None).T
  dfIncomeStatementY = dfIncomeStatementY.set_index("fiscalDateEnding").rename_axis(None).T

  display(dfIncomeStatementQ.index)
  display(dfIncomeStatementY)

Using yfinance statements.

In [565]:
#SCREENER SCRAPPER
import urllib.parse
import os
import json
import requests
from bs4 import BeautifulSoup

def get_screener_financials(ticker, report_type="yearly"):
    filename = f"screener_{ticker}_{report_type}.json"
    file_path = os.path.join(CACHE_DIR, filename)

    # Check Cache
    if os.path.exists(file_path):
        print(f"Loading {ticker} {report_type} from Screener cache...")
        with open(file_path, 'r') as f:
            return json.load(f)
  
    # Use a Session to retain cookies across requests
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "X-Requested-With": "XMLHttpRequest" # Tells Screener this is an AJAX API call
    })
    
    url = f"https://www.screener.in/company/{ticker}/"
    response = session.get(url)
    
    if response.status_code != 200:
        print(f"Error fetching Screener page: {response.status_code}")
        return None
    
    soup = BeautifulSoup(response.text, "html.parser")
    
    # Extract the hidden Company ID for sub item api
    company_div = soup.find(attrs={"data-company-id": True})
    if not company_div:
        print(f"Could not find company ID for {ticker}")
        return None
    company_id = company_div["data-company-id"]
    
    # Identify the section ID
    section_id = []
    if report_type == "quarterly" :
        section_id = "quarters"
    elif report_type == "yearly":
        section_id = 'profit-loss'
    elif report_type == "balance-sheet":
        section_id = 'balance-sheet'
    else:
        section_id = 'cash-flow'
        
    statement_section = soup.find("section", {"id": section_id})
    
    if not statement_section:
        print(f"Could not find {report_type} section for {ticker}")
        return None
  
    table = statement_section.find("table", class_="data-table")
    
    if table:
        # Date columns (Headers)
        headers = [th.get_text(strip=True) for th in table.find("thead").find_all("th")][1:]
        financial_data = {date: {} for date in headers}
        
        # Parse Rows (Main Line Items)
        for tr in table.find("tbody").find_all("tr"):
            cells = tr.find_all("td")
            if cells:
                row_label_cell = cells[0]
                row_label = row_label_cell.get_text(strip=True).replace("+", "").strip()
                
                # extract the main row values
                row_values = [td.get_text(strip=True).replace(",", "") for td in cells[1:]]
                for i, date in enumerate(headers):
                    if i < len(row_values):
                        financial_data[date][row_label] = row_values[i]
                
                button = row_label_cell.find("button")
                if button:
                    safe_parent = urllib.parse.quote(row_label)
                    api_url = f"https://www.screener.in/api/company/{company_id}/schedules/?parent={safe_parent}&section={section_id}"
                    
                    try:
                        sub_response = session.get(api_url)
                        if sub_response.status_code == 200:
                            sub_data = sub_response.json()
                            
                            for sub_label, date_values in sub_data.items():
                                final_label = f"{sub_label}"
                                
                                for d in headers:
                                    financial_data[d][final_label] = "0"
                                
                                for date_key, val in date_values.items():
                                    # Clean the date strings to ensure a perfect match
                                    clean_api_date = date_key.strip()
                                    
                                    if clean_api_date in financial_data:
                                        # Store the value, removing commas
                                        financial_data[clean_api_date][final_label] = str(val).replace(",", "")
                        else:
                            print(f"    - API Error: {sub_response.status_code}")
                            
                    except Exception as e:
                        print(f"    - Assignment failed for '{row_label}': {e}")
                    
        print(f"\nFinalized scraping {report_type} data from Screener.")           
        with open(file_path, 'w') as f:
            json.dump(financial_data, f)
              
        return financial_data
    
    return None

In [566]:
#call screener scrapper income statement
if not use_yfinance and not alpha_vantage:
  dfIncomeStatementQ = pd.DataFrame(get_screener_financials(tickerName.ticker, report_type='quarterly'))
  dfIncomeStatementY = pd.DataFrame(get_screener_financials(tickerName.ticker, report_type='yearly'))
  display(dfIncomeStatementQ)
  display(dfIncomeStatementY.index)

In [567]:

def clean_financial_dataframe(df):
    """Removes string artifacts and converts entire dataframe to numeric."""
    return df.replace(r'[%,+]', '', regex=True).apply(pd.to_numeric, errors='coerce')


def format_statement_for_db(df, target_columns, ticker, currency, multiplier=1.0,index_col_name='index', transpose=False):

    if transpose:
        df = df.T
    
    # Filter to only the columns needed for the database 
    clean_df = df.loc[:, target_columns]
    
    #normalize values decimals
    clean_df = (clean_df * multiplier).round(4)
    
    
    # Reset index to bring the dates into a standard column
    clean_df = clean_df.reset_index()
    
    # Rename the date column (handles Alpha Vantage vs Yfinance/Screener differences)
    clean_df = clean_df.rename(columns={index_col_name: 'ReportDate'})
    
    # Standardize end-of-month date format
    clean_df["ReportDate"] = (pd.to_datetime(clean_df["ReportDate"]) + pd.offsets.MonthEnd(0)).dt.strftime('%Y-%m-%d')
    
    # Insert Ticker at the beginning
    clean_df.insert(1, 'Ticker', ticker)
    clean_df.insert(2, 'Currency', currency)
    
    return clean_df


def to_pascal_case(text):

    if not isinstance(text, str):
        return text
    
    # Insert spaces before capital letters (e.g., "CostOfRevenue" -> "Cost Of Revenue")
    spaced_text = re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', text)
    
    # Replace anything that is NOT a letter with a space
    clean_text = re.sub(r'[^a-zA-Z]', ' ', spaced_text)
    
    #Split into individual words, capitalize the first letter, and glue together
    pascal_str = "".join(word.capitalize() for word in clean_text.split())
    
    return pascal_str


def standardize_dataframe_labels(df):

    df.index = [to_pascal_case(str(idx)) for idx in df.index]
    return df


def safe_fetch(df, target_item, synonym_map):
    """
    Checks the dataframe index for the exact target or its synonyms.
    Returns the first matched row. If nothing matches, returns a row of NaNs.
    """
    
    if target_item in df.index:
        # If there happen to be duplicate indexes, grab the first one to be safe
        result = df.loc[target_item]
        return result.iloc[0] if isinstance(result, pd.DataFrame) else result
    
    # Check for synonyms in the map
    synonyms = synonym_map.get(target_item, [])
    for syn in synonyms:
        if syn in df.index:
            result = df.loc[syn]
            return result.iloc[0] if isinstance(result, pd.DataFrame) else result
            
    #If completely missing, return NaNs
    return pd.Series(np.nan, index=df.columns)

def map_statement_via_dictionary(df, synonym_map, target_columns):
    """
    Loops through the target Ittelson columns and maps them using the safe_fetch scanner.
    """
    mapped_data = {}
    
    # Run the scanner for every column you need
    for target_col in target_columns:
        mapped_data[target_col] = safe_fetch(df, target_col, synonym_map)
        
    # Convert the collected data back into a DataFrame
    return pd.DataFrame(mapped_data).T

def apply_income_statement_fallbacks(df, target_columns):
    """
    Applies mathematical fallbacks only where data is missing (NaN), 
    then filters to target columns and fills remaining NaNs with 0.
    """
    # CostOfRevenue Fallback: TotalRevenue * (MaterialCost + ManufacturingCost) / 100
    if df.loc['CostOfRevenue'].isna().any():
        calc_cost = df.loc['TotalRevenue'] * (df.loc['MaterialCost'].fillna(0) + df.loc['ManufacturingCost'].fillna(0)) / 100
        df.loc['CostOfRevenue'] = df.loc['CostOfRevenue'].fillna(calc_cost)

    # GrossProfit Fallback: TotalRevenue - CostOfRevenue
    if df.loc['GrossProfit'].isna().any():
        calc_gp = df.loc['TotalRevenue'] - df.loc['CostOfRevenue']
        df.loc['GrossProfit'] = df.loc['GrossProfit'].fillna(calc_gp)

    # OperatingExpense Fallback: TotalRevenue * (EmployeeCost + OtherCost) / 100
    if df.loc['OperatingExpense'].isna().any():
        calc_opex = df.loc['TotalRevenue'] * (df.loc['EmployeeCost'].fillna(0) + df.loc['OtherCost'].fillna(0)) / 100
        df.loc['OperatingExpense'] = df.loc['OperatingExpense'].fillna(calc_opex)

    # NetInterestIncome Fallback: PretaxIncome - OperatingIncome
    if df.loc['NetInterestIncome'].isna().any():
        calc_interest = df.loc['PretaxIncome'] - df.loc['OperatingIncome']
        df.loc['NetInterestIncome'] = df.loc['NetInterestIncome'].fillna(calc_interest)

    # TaxProvision Fallback: PretaxIncome - NetIncome
    if df.loc['TaxProvision'].isna().any():
        calc_tax = df.loc['PretaxIncome'] - df.loc['NetIncome']
        df.loc['TaxProvision'] = df.loc['TaxProvision'].fillna(calc_tax)

    # Isolate the strict Ittelson columns and safely convert any remaining NaNs to 0
    final_df = df.loc[target_columns].fillna(0)
    
    return final_df

In [568]:

#alpha_to_ittelsons_col_map = {
#    "totalRevenue": "TotalRevenue",
#    "costOfRevenue": "CostOfRevenue",
#    "Operating Profit": "GrossProfit",
#    "operatingExpenses": "OperatingExpense",
#    "operatingIncome": "OperatingIncome",
#    "netInterestIncome": "NetInterestIncome",
#    "incomeTaxExpense": "TaxProvision", 
#    "netIncome": "NetIncome",
#}

#screener_to_ittelsons_col_map = {
#    "Sales": "TotalRevenue",
#    "CostOfRevenue": "CostOfRevenue",
#    "GrossProfit": "GrossProfit",
#    "OperatingExpense": "OperatingExpense",
#    "OperatingProfit": "OperatingIncome",
#    "NetInterestIncome": "NetInterestIncome",
#    "TaxProvision": "TaxProvision",
#    "NetProfit": "NetIncome",
#}

ittelson_income_statement_columns = [
    'TotalRevenue', 
    'CostOfRevenue', 
    'GrossProfit',
    'OperatingExpense',
    'OperatingIncome',
    'NetInterestIncome',
    'TaxProvision',
    'NetIncome'
]

normalized_is_synonym_map = {

    
    'TotalRevenue': [
        'TotalRevenue', 
        'OperatingRevenue', 
        'Sales'
    ],
    
    'CostOfRevenue': [
        'CostOfRevenue', 
        'ReconciledCostOfRevenue', 
        'CostofGoodsAndServicesSold'
        # Notice: MaterialCost and ManufacturingCost are REMOVED from here
    ],
    
    'GrossProfit': [
        'GrossProfit'
    ],
    
    'OperatingExpense': [
        'OperatingExpense', 
        'OperatingExpenses', 
        'SellingGeneralAndAdministration',
        'SellingGeneralAndAdministrative', 
        'OtherOperatingExpenses', 
        'ResearchAndDevelopment', 
        'SellingAndMarketingExpense',
        'GeneralAndAdministrativeExpense', 
        'OtherGandA',
        'Expenses', 
        'TotalExpenses'
        # Notice: EmployeeCost and OtherCost are REMOVED from here
    ],
    
    'OperatingIncome': [
        'OperatingIncome', 
        'TotalOperatingIncomeAsReported', 
        'OperatingProfit', 
        'Ebit' 
    ],
    
    'NetInterestIncome': [
        'NetInterestIncome', 
        'NetNonOperatingInterestIncomeExpense', 
        'Interest',
        'InterestIncome', 
        'InterestExpense', 
        'InterestAndDebtExpense',
        'InterestExpenseNonOperating', 
        'InterestIncomeNonOperating'
    ],
    
    'TaxProvision': [
        'TaxProvision', 
        'IncomeTaxExpense', 
        'Tax' # Derived from Screener's 'Tax %'
    ],
    
    'NetIncome': [
        'NetIncome', 
        'NetProfit', 
        'NetIncomeCommonStockholders',
        'NetIncomeContinuousOperations', 
        'NetIncomeFromContinuingOperations',
        'NetIncomeIncludingNoncontrollingInterests',
        'NetIncomeFromContinuingAndDiscontinuedOperation',
        'NetIncomeFromContinuingOperationNetMinorityInterest',
        'ProfitForEps', 
        'ProfitForPe'
    ],

    
    'PretaxIncome': [
        'PretaxIncome', 
        'ProfitBeforeTax', 
        'IncomeBeforeTax'
    ],
    
    'MaterialCost': [
        'MaterialCost' # Derived from Screener's 'Material Cost %'
    ],
    
    'ManufacturingCost': [
        'ManufacturingCost' # Derived from Screener's 'Manufacturing Cost %'
    ],
    
    'EmployeeCost': [
        'EmployeeCost' # Derived from Screener's 'Employee Cost %'
    ],
    
    'OtherCost': [
        'OtherCost' # Derived from Screener's 'Other Cost %'
    ]
}

In [ ]:

dfIncomeStatementQ = to_pascal_case(dfIncomeStatementQ)
dfIncomeStatementY = to_pascal_case(dfIncomeStatementY)

dfIncomeStatementQ = standardize_dataframe_labels(dfIncomeStatementQ)
dfIncomeStatementY = standardize_dataframe_labels(dfIncomeStatementY)

dfIncomeStatementQ = clean_financial_dataframe(dfIncomeStatementQ)
dfIncomeStatementY = clean_financial_dataframe(dfIncomeStatementY)

display(dfIncomeStatementQ)
display(dfIncomeStatementY)

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
TaxEffectOfUnusualItems,0.00,0.00,0.00,0.00,0.00
TaxRateForCalcs,0.02,0.01,0.01,0.03,0.04
NormalizedEbitda,582412000.00,399231000.00,275847000.00,182670000.00,18049000.00
NetIncomeFromContinuingOperationNetMinorityInterest,608676000.00,475599000.00,326727000.00,214031000.00,79009000.00
ReconciledDepreciation,7018000.00,5975000.00,6530000.00,6622000.00,7006000.00
ReconciledCostOfRevenue,215966000.00,207307000.00,192934000.00,172970000.00,174533000.00
Ebitda,582412000.00,399231000.00,275847000.00,182670000.00,18049000.00
Ebit,575394000.00,393256000.00,269317000.00,176048000.00,11043000.00
NetInterestIncome,62723000.00,59762000.00,56255000.00,50441000.00,54727000.00
InterestIncome,62723000.00,59762000.00,56255000.00,50441000.00,54727000.00
NormalizedIncome,608676000.00,475599000.00,326727000.00,214031000.00,79009000.00
NetIncomeFromContinuingAndDiscontinuedOperation,608676000.00,475599000.00,326727000.00,214031000.00,79009000.00
TotalExpenses,831408000.00,787836000.00,734380000.00,707807000.00,816476000.00
TotalOperatingIncomeAsReported,575394000.00,393256000.00,269317000.00,176048000.00,11043000.00
DilutedAverageShares,2573497000.00,2567309786.00,2559176657.00,2549097369.00,2524594133.00
BasicAverageShares,2386904000.00,2373702373.00,2361748820.00,2345255893.00,2301523724.00
DilutedEps,0.24,0.18,0.13,0.08,0.03
BasicEps,0.26,0.20,0.14,0.09,0.03
DilutedNiavailtoComStockholders,608676000.00,475599000.00,326727000.00,214031000.00,79009000.00
NetIncomeCommonStockholders,608676000.00,475599000.00,326727000.00,214031000.00,79009000.00
NetIncome,608676000.00,475599000.00,326727000.00,214031000.00,79009000.00
MinorityInterests,-2931000.00,-1149000.00,-1845000.00,-3686000.00,2073000.00
NetIncomeIncludingNoncontrollingInterests,611607000.00,476748000.00,328572000.00,217717000.00,76936000.00
NetIncomeContinuousOperations,611607000.00,476748000.00,328572000.00,217717000.00,76936000.00
TaxProvision,9776000.00,3753000.00,3596000.00,5599000.00,3602000.00
PretaxIncome,621383000.00,480501000.00,332168000.00,223316000.00,80538000.00
OtherIncomeExpense,-16734000.00,27483000.00,6596000.00,-3173000.00,14768000.00
OtherNonOperatingIncomeExpenses,-16734000.00,27483000.00,6596000.00,-3173000.00,14768000.00
NetNonOperatingInterestIncomeExpense,62723000.00,59762000.00,56255000.00,50441000.00,54727000.00
InterestIncomeNonOperating,62723000.00,59762000.00,56255000.00,50441000.00,54727000.00
OperatingIncome,575394000.00,393256000.00,269317000.00,176048000.00,11043000.00
OperatingExpense,615442000.00,580529000.00,541446000.00,534837000.00,641943000.00
ResearchAndDevelopment,143554000.00,144191000.00,135043000.00,134889000.00,171502000.00
SellingGeneralAndAdministration,471888000.00,436338000.00,406403000.00,399948000.00,470441000.00
SellingAndMarketingExpense,302126000.00,274636000.00,243788000.00,236309000.00,288295000.00
GeneralAndAdministrativeExpense,169762000.00,161702000.00,162615000.00,163639000.00,182146000.00
OtherGandA,169762000.00,161702000.00,162615000.00,163639000.00,182146000.00
GrossProfit,1190836000.00,973785000.00,810763000.00,710885000.00,652986000.00
CostOfRevenue,215966000.00,207307000.00,192934000.00,172970000.00,174533000.00
TotalRevenue,1406802000.00,1181092000.00,1003697000.00,883855000.00,827519000.00
OperatingRevenue,1406802000.00,1181092000.00,1003697000.00,883855000.00,827519000.00

,2025-12-31,2024-12-31,2023-12-31,2022-12-31,2021-12-31
TaxEffectOfUnusualItems,0.00,0.00,0.00,0.00,NaN
TaxRateForCalcs,0.01,0.04,0.08,0.21,NaN
NormalizedEbitda,1440160000.00,341990000.00,153320000.00,-138679000.00,NaN
NetIncomeFromContinuingOperationNetMinorityInterest,1625033000.00,462190000.00,209825000.00,-373705000.00,NaN
ReconciledDepreciation,26145000.00,31587000.00,33354000.00,22522000.00,NaN
ReconciledCostOfRevenue,789177000.00,565990000.00,431105000.00,408549000.00,NaN
Ebitda,1440160000.00,341990000.00,153320000.00,-138679000.00,NaN
Ebit,1414015000.00,310403000.00,119966000.00,-161201000.00,NaN
NetInterestIncome,229181000.00,196792000.00,132572000.00,20309000.00,NaN
InterestExpense,NaN,NaN,3470000.00,4058000.00,3640000.00
InterestIncome,229181000.00,196792000.00,132572000.00,20309000.00,NaN
NormalizedIncome,1625033000.00,462190000.00,209825000.00,-373705000.00,NaN
NetIncomeFromContinuingAndDiscontinuedOperation,1625033000.00,462190000.00,209825000.00,-373705000.00,NaN
TotalExpenses,3061431000.00,2555104000.00,2105046000.00,2067072000.00,NaN
TotalOperatingIncomeAsReported,1414015000.00,310403000.00,119966000.00,-161201000.00,NaN
DilutedAverageShares,2565197000.00,2447246030.00,2294577862.00,2060785103.00,NaN
BasicAverageShares,2369612000.00,2246883476.00,2144316182.00,2060785103.00,NaN
DilutedEps,0.63,0.19,0.09,-0.18,NaN
BasicEps,0.69,0.21,0.10,-0.18,NaN
DilutedNiavailtoComStockholders,1625033000.00,462190000.00,209825000.00,-373705000.00,NaN
AverageDilutionEarnings,NaN,NaN,NaN,0.00,0.00
NetIncomeCommonStockholders,1625033000.00,462190000.00,209825000.00,-373705000.00,NaN
OtherunderPreferredStockDividend,NaN,NaN,NaN,NaN,0.00
NetIncome,1625033000.00,462190000.00,209825000.00,-373705000.00,NaN
MinorityInterests,-9611000.00,-5728000.00,-7550000.00,-2611000.00,NaN
NetIncomeIncludingNoncontrollingInterests,1634644000.00,467918000.00,217375000.00,-371094000.00,NaN
NetIncomeContinuousOperations,1634644000.00,467918000.00,217375000.00,-371094000.00,NaN
TaxProvision,22724000.00,21255000.00,19716000.00,10067000.00,NaN
PretaxIncome,1657368000.00,489173000.00,237091000.00,-361027000.00,NaN
OtherIncomeExpense,14172000.00,-18022000.00,-15447000.00,-220135000.00,NaN
OtherNonOperatingIncomeExpenses,14172000.00,-18022000.00,-15447000.00,-220135000.00,NaN
NetNonOperatingInterestIncomeExpense,229181000.00,196792000.00,132572000.00,20309000.00,NaN
InterestExpenseNonOperating,NaN,NaN,3470000.00,4058000.00,3640000.00
InterestIncomeNonOperating,229181000.00,196792000.00,132572000.00,20309000.00,NaN
OperatingIncome,1414015000.00,310403000.00,119966000.00,-161201000.00,NaN
OperatingExpense,2272254000.00,1989114000.00,1673941000.00,1658523000.00,NaN
ResearchAndDevelopment,557677000.00,507878000.00,404624000.00,359679000.00,NaN
SellingGeneralAndAdministration,1714577000.00,1481236000.00,1269317000.00,1298844000.00,NaN
SellingAndMarketingExpense,1056859000.00,887755000.00,744992000.00,702511000.00,NaN
GeneralAndAdministrativeExpense,657718000.00,593481000.00,524325000.00,596333000.00,NaN
OtherGandA,657718000.00,593481000.00,524325000.00,596333000.00,NaN
GrossProfit,3686269000.00,2299517000.00,1793907000.00,1497322000.00,NaN
CostOfRevenue,789177000.00,565990000.00,431105000.00,408549000.00,NaN
TotalRevenue,4475446000.00,2865507000.00,2225012000.00,1905871000.00,NaN
OperatingRevenue,4475446000.00,2865507000.00,2225012000.00,1905871000.00,NaN

In [570]:

keys_to_fetch = ittelson_income_statement_columns + [
        'PretaxIncome', 'MaterialCost', 'ManufacturingCost', 'EmployeeCost', 'OtherCost'
    ]

# clean df for db insertion
if alpha_vantage:
    
    stmt_currency = 'USD' 
    stmt_multiplier = 0.000001

    #rename av columns to uniform ittleson columns
    dfIncomeStatementQ = format_statement_for_db(
        dfIncomeStatementQ, ittelson_income_statement_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier,transpose=True)
    dfIncomeStatementY = format_statement_for_db(
        dfIncomeStatementY, ittelson_income_statement_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier,transpose=True)
    display(dfIncomeStatementQ)
    
    #Filter, reset and rename fisacalDate column, add ticker column, replace none and change data types from string to numeric
    clean_quarterly_income_statement = format_statement_for_db(
        dfIncomeStatementQ, ittelson_income_statement_columns,tickerName.ticker,currency=stmt_currency,multiplier=stmt_multiplier, transpose=True)
    clean_quarterly_income_statement = clean_quarterly_income_statement.replace('None',np.nan)
    display(clean_quarterly_income_statement)

    clean_yearly_income_statement = format_statement_for_db(
        dfIncomeStatementY, ittelson_income_statement_columns,tickerName.ticker,currency=stmt_currency,multiplier=stmt_multiplier,transpose=False)
    clean_yearly_income_statement = clean_yearly_income_statement.replace('None',np.nan)
    display(clean_yearly_income_statement)
    
elif use_yfinance:

    print("Processing Yfinance data...")
    
    stmt_currency = tickerName.info.get('currency', 'USD') 
    stmt_multiplier = 0.000001
    
    df_normalize_Q = map_statement_via_dictionary(dfIncomeStatementQ, normalized_is_synonym_map, keys_to_fetch)
    df_normalize_Y = map_statement_via_dictionary(dfIncomeStatementY, normalized_is_synonym_map, keys_to_fetch).iloc[:,:-1]
    
    dfIncomeStatementQ_calc = apply_income_statement_fallbacks(df_normalize_Q, ittelson_income_statement_columns)
    dfIncomeStatementY_calc = apply_income_statement_fallbacks(df_normalize_Y, ittelson_income_statement_columns)

    # Yfinance needs .T because metrics are the index, we want dates as the index
    clean_quarterly_income_statement = format_statement_for_db(
        dfIncomeStatementQ_calc, ittelson_income_statement_columns,tickerName.ticker,currency=stmt_currency,multiplier=stmt_multiplier,transpose=True)
    display(clean_quarterly_income_statement)

    clean_yearly_income_statement = format_statement_for_db(
        dfIncomeStatementY_calc, ittelson_income_statement_columns,tickerName.ticker,currency=stmt_currency,multiplier=stmt_multiplier, transpose=True)
    display(clean_yearly_income_statement)
else:
    print("Processing Screener data...")
    
    stmt_currency = 'INR'
    stmt_multiplier = 10.0
    
    #include extra keys with normalization for further calulation - keys will be dropped at format_statement_for_db call
    
    df_normalize_Q = map_statement_via_dictionary(dfIncomeStatementQ, normalized_is_synonym_map, keys_to_fetch)
    df_normalize_Y = map_statement_via_dictionary(dfIncomeStatementY, normalized_is_synonym_map, keys_to_fetch).iloc[:,:-1]
    
    dfIncomeStatementQ_calc = apply_income_statement_fallbacks(df_normalize_Q, ittelson_income_statement_columns)
    clean_quarterly_income_statement = format_statement_for_db(
        dfIncomeStatementQ_calc, ittelson_income_statement_columns,tickerName.ticker,currency=stmt_currency,multiplier=stmt_multiplier, transpose=True)
    display(clean_quarterly_income_statement)
    
    dfIncomeStatementY_calc = apply_income_statement_fallbacks(df_normalize_Y, ittelson_income_statement_columns)
    clean_yearly_income_statement = format_statement_for_db(
        dfIncomeStatementY_calc, ittelson_income_statement_columns, tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier,transpose=True
        )
    display(clean_yearly_income_statement)

Processing Yfinance data...

,ReportDate,Ticker,Currency,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
0,2025-12-31,PLTR,USD,1406.80,215.97,1190.84,615.44,575.39,62.72,9.78,608.68
1,2025-09-30,PLTR,USD,1181.09,207.31,973.78,580.53,393.26,59.76,3.75,475.60
2,2025-06-30,PLTR,USD,1003.70,192.93,810.76,541.45,269.32,56.26,3.60,326.73
3,2025-03-31,PLTR,USD,883.86,172.97,710.88,534.84,176.05,50.44,5.60,214.03
4,2024-12-31,PLTR,USD,827.52,174.53,652.99,641.94,11.04,54.73,3.60,79.01

,ReportDate,Ticker,Currency,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
0,2025-12-31,PLTR,USD,4475.45,789.18,3686.27,2272.25,1414.02,229.18,22.72,1625.03
1,2024-12-31,PLTR,USD,2865.51,565.99,2299.52,1989.11,310.40,196.79,21.25,462.19
2,2023-12-31,PLTR,USD,2225.01,431.11,1793.91,1673.94,119.97,132.57,19.72,209.82
3,2022-12-31,PLTR,USD,1905.87,408.55,1497.32,1658.52,-161.20,20.31,10.07,-373.70

In [571]:
metadata = MetaData(schema='public')
metadata.create_all(engine)

#Define the architecture
quarterly_income_statement = Table(
    'quarterly_income_statement', metadata,
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)
#Define the architecture
yearly_income_statement = Table(
    'yearly_income_statement', metadata,
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)


## Drop the old tables
#quarterly_income_statement.drop(engine, checkfirst=True)
#yearly_income_statement.drop(engine, checkfirst=True)

## Create the new tables with the Primary Keys
#metadata.create_all(engine)
#print("Tables dropped and recreated with proper Primary Keys!")
##Build the table in the database


print("Tables created successfully.")

Tables created successfully.

In [572]:

#Define the Custom Upsert Logic
def postgres_upsert(table, conn, keys, data_iter):
    """
    Native PostgreSQL UPSERT
    """
    # Convert Pandas data into a list of dictionaries
    data = [dict(zip(keys, row)) for row in data_iter]
    
    insert_stmt = insert(table.table).values(data)

    update_dict = {
    c.name: getattr(insert_stmt.excluded, c.name)
    for c in table.table.columns
    if c.name not in ("Ticker", "ReportDate")
}
    
    upsert_stmt = insert_stmt.on_conflict_do_update(
        index_elements=['Ticker', 'ReportDate'], 
        set_=update_dict
    )
    
    conn.execute(upsert_stmt)


# Push the data using the custom Upsert method
clean_quarterly_income_statement.to_sql(
    name='quarterly_income_statement',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

clean_yearly_income_statement.to_sql(
    name='yearly_income_statement',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

print("Income Statement Data successfully upserted into the database.")

Income Statement Data successfully upserted into the database.

# Balance Sheet

In [573]:
# call yfinace balancesheet
raw_data_q = get_yfinance(tickerName.ticker, "BALANCE_SHEET", "quarterly")
raw_data_y = get_yfinance(tickerName.ticker, "BALANCE_SHEET", "yearly")

# check if has data and covert to dataframe
if raw_data_q is not None and raw_data_y is not None:
    
    dfBalanceSheetQ = pd.DataFrame(raw_data_q)
    dfBalanceSheetY = pd.DataFrame(raw_data_y)
    display(dfBalanceSheetQ)
    display(dfBalanceSheetY.index)
    
    if not dfBalanceSheetQ.empty and not dfBalanceSheetY.empty:
        use_yfinance = True
        print("Yfinance data loaded successfully. Setting use_yfinance = True.")
    else:
        use_yfinance = False
        print("Yfinance returned empty DataFrames. Falling back...")
else:
    
    use_yfinance = False
    dfBalanceSheetQ = None
    dfBalanceSheetY = None
    print("Yfinance data incomplete. Falling back to Alpha Vantage...")

Loading yfinance offline_statements\yfinance_PLTR_BALANCE_SHEET_quarterly.json from local cache
Loading yfinance offline_statements\yfinance_PLTR_BALANCE_SHEET_yearly.json from local cache

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
OrdinarySharesNumber,2391192000.00,2383314028.00,2371847000.00,2359663165.00,2338795190,NaN
ShareIssued,2391192000.00,2383314028.00,2371847000.00,2359663165.00,2338795190,NaN
TotalDebt,229338000.00,235436000.00,237812000.00,244596000.00,239219000,NaN
TangibleBookValue,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
InvestedCapital,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
WorkingCapital,7182593000.00,6405753000.00,5800753000.00,5315156000.00,4938271000,NaN
NetTangibleAssets,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
CapitalLeaseObligations,229338000.00,235436000.00,237812000.00,244596000.00,239219000,NaN
CommonStockEquity,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
TotalCapitalization,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
TotalEquityGrossMinorityInterest,7488011000.00,6688269000.00,6025564000.00,5518973000.00,5094407000,NaN
MinorityInterest,100743000.00,97812000.00,96663000.00,94818000.00,91132000,NaN
StockholdersEquity,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
GainsLossesNotAffectingRetainedEarnings,13942000.00,11537000.00,4721000.00,-2994000.00,-5611000,NaN
OtherEquityAdjustments,13942000.00,11537000.00,4721000.00,-2994000.00,-5611000,NaN
RetainedEarnings,-3562390000.00,-4171066000.00,-4646665000.00,-4973392000.00,-5187423000,NaN
AdditionalPaidInCapital,10933325000.00,10747603000.00,10568473000.00,10398181000.00,10193970000,NaN
CapitalStock,2391000.00,2383000.00,2372000.00,2360000.00,2339000,NaN
CommonStock,2391000.00,2383000.00,2372000.00,2360000.00,2339000,NaN
TotalLiabilitiesNetMinorityInterest,1412381000.00,1425691000.00,1340124000.00,1217944000.00,1246477000,NaN
TotalNonCurrentLiabilitiesNetMinorityInterest,236800000.00,245288000.00,250484000.00,250501000.00,250459000,NaN
OtherNonCurrentLiabilities,7092000.00,10652000.00,12008000.00,12489000.00,13685000,NaN
NonCurrentDeferredLiabilities,46234000.00,45471000.00,46129000.00,37835000.00,41548000,NaN
NonCurrentDeferredRevenue,46234000.00,45471000.00,46129000.00,37835000.00,41548000,NaN
LongTermDebtAndCapitalLeaseObligation,183474000.00,189165000.00,192347000.00,200177000.00,195226000,NaN
LongTermCapitalLeaseObligation,183474000.00,189165000.00,192347000.00,200177000.00,195226000,NaN
CurrentLiabilities,1175581000.00,1180403000.00,1089640000.00,967443000.00,996018000,NaN
CurrentDeferredLiabilities,766029000.00,684892000.00,639778000.00,549633000.00,524876000,NaN
CurrentDeferredRevenue,766029000.00,684892000.00,639778000.00,549633000.00,524876000,NaN
CurrentDebtAndCapitalLeaseObligation,45864000.00,46271000.00,45465000.00,44419000.00,43993000,NaN
CurrentCapitalLeaseObligation,45864000.00,46271000.00,45465000.00,44419000.00,43993000,NaN
PayablesAndAccruedExpenses,363688000.00,449240000.00,404397000.00,373391000.00,427149000,NaN
CurrentAccruedExpenses,355624000.00,381737000.00,393623000.00,371061000.00,427046000,NaN
Payables,8064000.00,67503000.00,10774000.00,2330000.00,103000,NaN
TotalTaxPayable,NaN,NaN,NaN,NaN,42243000,31952000.00
AccountsPayable,8064000.00,67503000.00,10774000.00,2330000.00,103000,NaN
TotalAssets,8900392000.00,8113960000.00,7365688000.00,6736917000.00,6340884000,NaN
TotalNonCurrentAssets,542218000.00,527804000.00,475295000.00,454318000.00,406595000,NaN
OtherNonCurrentAssets,290153000.00,277783000.00,228298000.00,205301000.00,166217000,NaN
NetPPE,252065000.00,250021000.00,246997000.00,249017000.00,240378000,NaN
AccumulatedDepreciation,-149091000.00,-142790000.00,-138176000.00,-129669000.00,-122999000,NaN
GrossPPE,401156000.00,392811000.00,385173000.00,378686000.00,363377000,NaN
Leases,98302000.00,97182000.00,92401000.00,89216000.00,85284000,NaN
ConstructionInProgress,9999000.00,5959000.00,6533000.00,7261000.00,7632000,NaN
OtherProperties,200105000.00,204315000.00,203474000.00,209348000.00,200740000,NaN
MachineryFurnitureEquipment,92750000.00,85355000.00,82765000.00,72861000.00,69721000,NaN
Properties,0.00,0.00,0.00,0.00,0,NaN
CurrentAssets,8358174000.00,7586156000.00,6890393000.00,6282599000.00,5934289000,NaN
OtherCurrentAssets,139066000.00,142429000.00,142487000.00,126705000.00,129254000,NaN
Receivables,1042065000.00,1005910000.00,747484000.00,725205000.00,575048000,NaN
AccountsReceivable,1042065000.00,1005910000.00,747484000.00,725205000.00,575048000,NaN
AllowanceForDoubtfulAccountsReceivable,NaN,NaN,NaN,NaN,-10500000,-1500000.00
GrossAccountsReceivable,NaN,NaN,NaN,NaN,585548000,669610000.00
CashCashEquivalentsAndShortTermInvestments,7177043000.00,6437817000.00,6000422000.00,5430689000.00,5229987000,NaN
OtherShortTermInvestments,5753247000.00,4821850000.00,5070875000.00,4437225000.00,3131463000,NaN
CashAndCashEquivalents,1423796000.00,1615967000.00,929547000.00,993464000.00,2098524000,NaN

Index(['TreasurySharesNumber', 'OrdinarySharesNumber', 'ShareIssued',
       'TotalDebt', 'TangibleBookValue', 'InvestedCapital', 'WorkingCapital',
       'NetTangibleAssets', 'CapitalLeaseObligations', 'CommonStockEquity',
       'TotalCapitalization', 'TotalEquityGrossMinorityInterest',
       'MinorityInterest', 'StockholdersEquity',
       'GainsLossesNotAffectingRetainedEarnings', 'OtherEquityAdjustments',
       'RetainedEarnings', 'AdditionalPaidInCapital', 'CapitalStock',
       'CommonStock', 'PreferredStock', 'TotalLiabilitiesNetMinorityInterest',
       'TotalNonCurrentLiabilitiesNetMinorityInterest',
       'OtherNonCurrentLiabilities', 'NonCurrentDeferredLiabilities',
       'NonCurrentDeferredRevenue', 'LongTermDebtAndCapitalLeaseObligation',
       'LongTermCapitalLeaseObligation', 'CurrentLiabilities',
       'CurrentDeferredLiabilities', 'CurrentDeferredRevenue',
       'CurrentDebtAndCapitalLeaseObligation', 'CurrentCapitalLeaseObligation',
       'PayablesAndAccruedExpenses', 'CurrentAccruedExpenses', 'Payables',
       'TotalTaxPayable', 'AccountsPayable', 'TotalAssets',
       'TotalNonCurrentAssets', 'OtherNonCurrentAssets', 'NetPPE',
       'AccumulatedDepreciation', 'GrossPPE', 'Leases',
       'ConstructionInProgress', 'OtherProperties',
       'MachineryFurnitureEquipment', 'Properties', 'CurrentAssets',
       'OtherCurrentAssets', 'RestrictedCash', 'PrepaidAssets', 'Receivables',
       'AccountsReceivable', 'AllowanceForDoubtfulAccountsReceivable',
       'GrossAccountsReceivable', 'CashCashEquivalentsAndShortTermInvestments',
       'OtherShortTermInvestments', 'CashAndCashEquivalents'],
      dtype='str')

Yfinance data loaded successfully. Setting use_yfinance = True.

In [574]:
#dfBalanceSheetQ = None
#dfBalanceSheetY = None

In [575]:
#call alpha vantage balancesheet
alpha_vantage = False

if dfBalanceSheetQ is None or dfBalanceSheetQ is None:
    # Use the new fetch/cache function
    ticker = tickerName.ticker
    avB_data = get_alpha_vantage(ticker, 'BALANCE_SHEET', API_KEY)
    
    if avB_data:
        alpha_vantage_balance_sheet_quarterly = avB_data["quarterlyReports"]
        alpha_vantage_balance_sheet_yearly = avB_data["annualReports"]
        alpha_vantage = True

# Standard Status Checks
if not alpha_vantage and dfBalanceSheetQ is not None:
    print("Using yfinance statements.")
elif not alpha_vantage and dfBalanceSheetQ is None:
    print("CRITICAL: No data found in yfinance OR local Alpha Vantage cache.")
    

if alpha_vantage:

  dfBalanceSheetQ = pd.DataFrame(alpha_vantage_balance_sheet_quarterly)
  dfBalanceSheetY =  pd.DataFrame(alpha_vantage_balance_sheet_yearly)
  
  dfBalanceSheetQ = dfBalanceSheetQ.set_index("fiscalDateEnding")
  dfBalanceSheetY = dfBalanceSheetY.set_index("fiscalDateEnding")

  display(dfBalanceSheetQ)
  display(dfBalanceSheetY)

Using yfinance statements.

In [576]:
#call screener scrapper balance sheet
if not use_yfinance and not alpha_vantage:
  #dfBalanceSheetQ = pd.DataFrame(get_screener_financials(tickerName.ticker, report_type='balance-sheet'))
  dfBalanceSheetY = pd.DataFrame(get_screener_financials(tickerName.ticker, report_type='balance-sheet'))
  #display(dfBalanceSheetQ)
  display(dfBalanceSheetY)

In [577]:

#Screener balance sheet items mapping
ittelson_screener_balance_sheet_map = {
    'Cash Equivalents': 'CashCashEquivalentsAndShortTermInvestments',
    'Trade receivables': 'Receivables',
    'Inventories': 'Inventory',
    'Gross Block': 'GrossPPE',
    'Accumulated Depreciation': 'AccumulatedDepreciation',
    'Fixed Assets': 'NetPPE',
    'Total Assets': 'TotalAssets',
    'Trade Payables': 'PayablesAndAccruedExpenses',
    'Short term Borrowings': 'CurrentDebtAndCapitalLeaseObligation',
    'Long term Borrowings': 'LongTermDebtAndCapitalLeaseObligation',
    'Equity Capital': 'CapitalStock',
    'Reserves': 'RetainedEarnings'
}

yfinance_to_ittelson_map = {
    'AccountsReceivable': 'Receivables',
    'AccountsPayable': 'PayablesAndAccruedExpenses',
    'Inventory': 'Inventory',
    'GrossPPE': 'GrossPPE',
    'AccumulatedDepreciation': 'AccumulatedDepreciation',
    'NetPPE': 'NetPPE',
    'TotalAssets': 'TotalAssets',
    'CurrentDebtAndCapitalLeaseObligation': 'CurrentDebtAndCapitalLeaseObligation',
    'LongTermDebtAndCapitalLeaseObligation': 'LongTermDebtAndCapitalLeaseObligation',
    'TotalTaxPayable': 'TotalTaxPayable',
    'CapitalStock': 'CapitalStock',
    'RetainedEarnings': 'RetainedEarnings',
    'StockholdersEquity': 'StockholdersEquity'
}

normalized_bs_synonym_map = {
    # --- ASSETS ---
    'CashCashEquivalentsAndShortTermInvestments': [
        'CashCashEquivalentsAndShortTermInvestments', 
        'CashAndCashEquivalents',
        'CashFinancial'
        # Notice: 'CashEquivalents' and 'Investments' are REMOVED from here (they are ingredients)
    ],
    
    'Receivables': [
        'Receivables', 
        'AccountsReceivable', 
        'TradeReceivables' # 1:1 Screener equivalent
    ],
    
    'Inventory': [
        'Inventory', 
        'Inventories'
    ],
    
    'CurrentAssets': [
        'CurrentAssets'
    ],
    
    'TotalNonCurrentAssets': [
        'TotalNonCurrentAssets'
    ],
    
    'GrossPPE': [
        'GrossPPE',
        'GrossPpe', 
        'GrossBlock' # 1:1 Screener equivalent
    ],
    
    'AccumulatedDepreciation': [
        'AccumulatedDepreciation'
    ],
    
    'NetPpe': [
        'NetPPE',
        'NetPpe' 
        'FixedAssets' # 1:1 Screener equivalent
    ],
    
    'TotalAssets': [
        'TotalAssets'
    ],
    
    # --- LIABILITIES & EQUITY ---
    'PayablesAndAccruedExpenses': [
        'PayablesAndAccruedExpenses', 
        'AccountsPayable', 
        'Payables'
        # Notice: 'TradePayables' and 'AdvanceFromCustomers' are REMOVED from here
    ],
    
    'CurrentDebtAndCapitalLeaseObligation': [
        'CurrentDebtAndCapitalLeaseObligation', 
        'CurrentDebt',
        'CurrentCapitalLeaseObligation'
        # Notice: 'ShortTermBorrowings' is REMOVED from here
    ],
    
    'TotalTaxPayable': [
        'TotalTaxPayable',
        'TaxesPayable'
    ],
    
    'CurrentLiabilities': [
        'CurrentLiabilities'
    ],
    
    'LongTermDebtAndCapitalLeaseObligation': [
        'LongTermDebtAndCapitalLeaseObligation', 
        'LongTermDebt',
        'LongTermCapitalLeaseObligation'
        # Notice: 'LongTermBorrowings' is REMOVED from here
    ],
    
    'TotalLiabilitiesNetMinorityInterest': [
        'TotalLiabilitiesNetMinorityInterest', 
        'TotalLiabilities'
    ],
    
    'CapitalStock': [
        'CapitalStock', 
        'CommonStock', 
        'EquityCapital' # 1:1 Screener equivalent
    ],
    
    'RetainedEarnings': [
        'RetainedEarnings', 
        'Reserves' # 1:1 Screener equivalent
    ],
    
    'StockholdersEquity': [
        'StockholdersEquity', 
        'TotalEquityGrossMinorityInterest', 
        'CommonStockEquity'
    ],

    
    # Cash Components
    'CashEquivalents': ['CashEquivalents'],
    'Investments': ['Investments'],
    
    # Current Asset Components
    'LoansNAdvances': ['LoansNAdvances'], 
    'OtherAssetItems': ['OtherAssetItems'],
    
    # Payables Components
    'TradePayables': ['TradePayables'],
    'AdvanceFromCustomers': ['AdvanceFromCustomers'],
    
    # Debt Components
    'ShortTermBorrowings': ['ShortTermBorrowings'],
    'LeaseLiabilities': ['LeaseLiabilities'],
    'LongTermBorrowings': ['LongTermBorrowings'],
    'OtherBorrowings': ['OtherBorrowings'],
    
    # Liability Components
    'OtherLiabilityItems': ['OtherLiabilityItems'],
    'Borrowings': ['Borrowings'],
    'OtherLiabilities': ['OtherLiabilities']
}

ittelson_balance_sheet_columns = [
  #Assets
  'CashCashEquivalentsAndShortTermInvestments',
  'Receivables',
  'Inventory',
  'CurrentAssets',
  'TotalNonCurrentAssets',
  'GrossPPE',
  'AccumulatedDepreciation',
  'NetPPE',
  'TotalAssets',
  #Liabilities&Equity
  'PayablesAndAccruedExpenses',
  'CurrentDebtAndCapitalLeaseObligation',
  'TotalTaxPayable',
  'CurrentLiabilities',
  'LongTermDebtAndCapitalLeaseObligation',
  'TotalLiabilitiesNetMinorityInterest', #Current Liabilities + Long-Term Debt.
  'CapitalStock',
  'RetainedEarnings',
  'StockholdersEquity'
]

In [579]:
def apply_balance_sheet_fallbacks(df, target_columns):
    """
    Applies mathematical fallbacks for the Balance Sheet where data is missing (NaN),
    then filters strictly to the target columns and fills remaining NaNs with 0.
    """
    #ASSETS
    # Cash & Equivalents Fallback
    if df.loc['CashCashEquivalentsAndShortTermInvestments'].isna().any():
        calc_cash = df.loc['CashEquivalents'].fillna(0) + df.loc['Investments'].fillna(0)
        df.loc['CashCashEquivalentsAndShortTermInvestments'] = df.loc['CashCashEquivalentsAndShortTermInvestments'].fillna(calc_cash)

    # Current Assets Fallback
    if df.loc['CurrentAssets'].isna().any():
        calc_ca = (df.loc['Inventory'].fillna(0) + 
                   df.loc['Receivables'].fillna(0) + 
                   df.loc['CashEquivalents'].fillna(0) + 
                   df.loc['LoansNAdvances'].fillna(0) + 
                   df.loc['OtherAssetItems'].fillna(0))
        df.loc['CurrentAssets'] = df.loc['CurrentAssets'].fillna(calc_ca)
    
    #Inventory
    if df.loc['Inventory'].isna().any():
        calc_inv = df.loc['CurrentAssets'] - (df.loc['CashCashEquivalentsAndShortTermInvestments'].fillna(0) + 
                                              df.loc['Receivables'].fillna(0) + 
                                              df.loc['LoansNAdvances'].fillna(0) + 
                                              df.loc['OtherAssetItems'].fillna(0))
        df.loc['Inventory'] = df.loc['Inventory'].fillna(calc_inv)
    
    # Total Non-Current Assets Fallback
    if df.loc['TotalNonCurrentAssets'].isna().any():
        calc_nca = df.loc['TotalAssets'] - df.loc['CurrentAssets']
        df.loc['TotalNonCurrentAssets'] = df.loc['TotalNonCurrentAssets'].fillna(calc_nca)

    # PPE Math
    if df.loc['NetPPE'].isna().any():
        df.loc['NetPPE'] = df.loc['NetPPE'].fillna(df.loc['GrossPPE'] - df.loc['AccumulatedDepreciation'].fillna(0))
        
    if df.loc['GrossPPE'].isna().any():
        df.loc['GrossPPE'] = df.loc['GrossPPE'].fillna(df.loc['NetPPE'] + df.loc['AccumulatedDepreciation'].fillna(0))


    # LIABILITIES
    # Payables & Accrued Expenses Fallback
    if df.loc['PayablesAndAccruedExpenses'].isna().any():
        calc_payables = df.loc['TradePayables'].fillna(0) + df.loc['AdvanceFromCustomers'].fillna(0)
        df.loc['PayablesAndAccruedExpenses'] = df.loc['PayablesAndAccruedExpenses'].fillna(calc_payables)

    # Current Debt Fallback
    if df.loc['CurrentDebtAndCapitalLeaseObligation'].isna().any():
        calc_cdebt = df.loc['ShortTermBorrowings'].fillna(0) + df.loc['LeaseLiabilities'].fillna(0)
        df.loc['CurrentDebtAndCapitalLeaseObligation'] = df.loc['CurrentDebtAndCapitalLeaseObligation'].fillna(calc_cdebt)

    # Current Liabilities Fallback
    if df.loc['CurrentLiabilities'].isna().any():
        calc_cl = (df.loc['PayablesAndAccruedExpenses'].fillna(0) + 
                   df.loc['CurrentDebtAndCapitalLeaseObligation'].fillna(0) + 
                   df.loc['OtherLiabilityItems'].fillna(0))
        df.loc['CurrentLiabilities'] = df.loc['CurrentLiabilities'].fillna(calc_cl)

    # Long-Term Debt Fallback
    if df.loc['LongTermDebtAndCapitalLeaseObligation'].isna().any():
        calc_ltdebt = df.loc['LongTermBorrowings'].fillna(0) + df.loc['OtherBorrowings'].fillna(0)
        df.loc['LongTermDebtAndCapitalLeaseObligation'] = df.loc['LongTermDebtAndCapitalLeaseObligation'].fillna(calc_ltdebt)

    # Total Liabilities Fallback
    if df.loc['TotalLiabilitiesNetMinorityInterest'].isna().any():
        calc_tl = df.loc['Borrowings'].fillna(0) + df.loc['OtherLiabilities'].fillna(0)
        df.loc['TotalLiabilitiesNetMinorityInterest'] = df.loc['TotalLiabilitiesNetMinorityInterest'].fillna(calc_tl)

    # --- EQUITY ---
    # Stockholders Equity Fallback
    if df.loc['StockholdersEquity'].isna().any():
        calc_equity = df.loc['CapitalStock'].fillna(0) + df.loc['RetainedEarnings'].fillna(0)
        df.loc['StockholdersEquity'] = df.loc['StockholdersEquity'].fillna(calc_equity)

    final_df = df.loc[target_columns].fillna(0)
    
    return final_df

In [ ]:

#Clean
if use_yfinance or alpha_vantage: 
  dfBalanceSheetQ = to_pascal_case(dfBalanceSheetQ)
  dfBalanceSheetY = to_pascal_case(dfBalanceSheetY)

  dfBalanceSheetQ = standardize_dataframe_labels(dfBalanceSheetQ)
  dfBalanceSheetY = standardize_dataframe_labels(dfBalanceSheetY)

  dfBalanceSheetQ = clean_financial_dataframe(dfBalanceSheetQ)
  dfBalanceSheetY = clean_financial_dataframe(dfBalanceSheetY)
  
else:
  
  dfBalanceSheetY = to_pascal_case(dfBalanceSheetY)
  dfBalanceSheetY = standardize_dataframe_labels(dfBalanceSheetY)
  dfBalanceSheetY = clean_financial_dataframe(dfBalanceSheetY)

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
OrdinarySharesNumber,2391192000.00,2383314028.00,2371847000.00,2359663165.00,2338795190,NaN
ShareIssued,2391192000.00,2383314028.00,2371847000.00,2359663165.00,2338795190,NaN
TotalDebt,229338000.00,235436000.00,237812000.00,244596000.00,239219000,NaN
TangibleBookValue,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
InvestedCapital,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
WorkingCapital,7182593000.00,6405753000.00,5800753000.00,5315156000.00,4938271000,NaN
NetTangibleAssets,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
CapitalLeaseObligations,229338000.00,235436000.00,237812000.00,244596000.00,239219000,NaN
CommonStockEquity,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
TotalCapitalization,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
TotalEquityGrossMinorityInterest,7488011000.00,6688269000.00,6025564000.00,5518973000.00,5094407000,NaN
MinorityInterest,100743000.00,97812000.00,96663000.00,94818000.00,91132000,NaN
StockholdersEquity,7387268000.00,6590457000.00,5928901000.00,5424155000.00,5003275000,NaN
GainsLossesNotAffectingRetainedEarnings,13942000.00,11537000.00,4721000.00,-2994000.00,-5611000,NaN
OtherEquityAdjustments,13942000.00,11537000.00,4721000.00,-2994000.00,-5611000,NaN
RetainedEarnings,-3562390000.00,-4171066000.00,-4646665000.00,-4973392000.00,-5187423000,NaN
AdditionalPaidInCapital,10933325000.00,10747603000.00,10568473000.00,10398181000.00,10193970000,NaN
CapitalStock,2391000.00,2383000.00,2372000.00,2360000.00,2339000,NaN
CommonStock,2391000.00,2383000.00,2372000.00,2360000.00,2339000,NaN
TotalLiabilitiesNetMinorityInterest,1412381000.00,1425691000.00,1340124000.00,1217944000.00,1246477000,NaN
TotalNonCurrentLiabilitiesNetMinorityInterest,236800000.00,245288000.00,250484000.00,250501000.00,250459000,NaN
OtherNonCurrentLiabilities,7092000.00,10652000.00,12008000.00,12489000.00,13685000,NaN
NonCurrentDeferredLiabilities,46234000.00,45471000.00,46129000.00,37835000.00,41548000,NaN
NonCurrentDeferredRevenue,46234000.00,45471000.00,46129000.00,37835000.00,41548000,NaN
LongTermDebtAndCapitalLeaseObligation,183474000.00,189165000.00,192347000.00,200177000.00,195226000,NaN
LongTermCapitalLeaseObligation,183474000.00,189165000.00,192347000.00,200177000.00,195226000,NaN
CurrentLiabilities,1175581000.00,1180403000.00,1089640000.00,967443000.00,996018000,NaN
CurrentDeferredLiabilities,766029000.00,684892000.00,639778000.00,549633000.00,524876000,NaN
CurrentDeferredRevenue,766029000.00,684892000.00,639778000.00,549633000.00,524876000,NaN
CurrentDebtAndCapitalLeaseObligation,45864000.00,46271000.00,45465000.00,44419000.00,43993000,NaN
CurrentCapitalLeaseObligation,45864000.00,46271000.00,45465000.00,44419000.00,43993000,NaN
PayablesAndAccruedExpenses,363688000.00,449240000.00,404397000.00,373391000.00,427149000,NaN
CurrentAccruedExpenses,355624000.00,381737000.00,393623000.00,371061000.00,427046000,NaN
Payables,8064000.00,67503000.00,10774000.00,2330000.00,103000,NaN
TotalTaxPayable,NaN,NaN,NaN,NaN,42243000,31952000.00
AccountsPayable,8064000.00,67503000.00,10774000.00,2330000.00,103000,NaN
TotalAssets,8900392000.00,8113960000.00,7365688000.00,6736917000.00,6340884000,NaN
TotalNonCurrentAssets,542218000.00,527804000.00,475295000.00,454318000.00,406595000,NaN
OtherNonCurrentAssets,290153000.00,277783000.00,228298000.00,205301000.00,166217000,NaN
NetPpe,252065000.00,250021000.00,246997000.00,249017000.00,240378000,NaN
AccumulatedDepreciation,-149091000.00,-142790000.00,-138176000.00,-129669000.00,-122999000,NaN
GrossPpe,401156000.00,392811000.00,385173000.00,378686000.00,363377000,NaN
Leases,98302000.00,97182000.00,92401000.00,89216000.00,85284000,NaN
ConstructionInProgress,9999000.00,5959000.00,6533000.00,7261000.00,7632000,NaN
OtherProperties,200105000.00,204315000.00,203474000.00,209348000.00,200740000,NaN
MachineryFurnitureEquipment,92750000.00,85355000.00,82765000.00,72861000.00,69721000,NaN
Properties,0.00,0.00,0.00,0.00,0,NaN
CurrentAssets,8358174000.00,7586156000.00,6890393000.00,6282599000.00,5934289000,NaN
OtherCurrentAssets,139066000.00,142429000.00,142487000.00,126705000.00,129254000,NaN
Receivables,1042065000.00,1005910000.00,747484000.00,725205000.00,575048000,NaN
AccountsReceivable,1042065000.00,1005910000.00,747484000.00,725205000.00,575048000,NaN
AllowanceForDoubtfulAccountsReceivable,NaN,NaN,NaN,NaN,-10500000,-1500000.00
GrossAccountsReceivable,NaN,NaN,NaN,NaN,585548000,669610000.00
CashCashEquivalentsAndShortTermInvestments,7177043000.00,6437817000.00,6000422000.00,5430689000.00,5229987000,NaN
OtherShortTermInvestments,5753247000.00,4821850000.00,5070875000.00,4437225000.00,3131463000,NaN
CashAndCashEquivalents,1423796000.00,1615967000.00,929547000.00,993464000.00,2098524000,NaN

In [581]:
#map
bs_keys_to_fetch = ittelson_balance_sheet_columns + [
    'CashEquivalents', 'Investments', 'LoansNAdvances', 'OtherAssetItems',
    'TradePayables', 'AdvanceFromCustomers', 'ShortTermBorrowings', 'LeaseLiabilities',
    'LongTermBorrowings', 'OtherBorrowings', 'OtherLiabilityItems', 'Borrowings', 'OtherLiabilities'
]

if alpha_vantage:
  
  stmt_currency = 'USD' 
  stmt_multiplier = 0.000001
  
  df_normalize_BQ = map_statement_via_dictionary(dfBalanceSheetQ, normalized_bs_synonym_map, bs_keys_to_fetch)
  df_normalize_BY = map_statement_via_dictionary(dfBalanceSheetY, normalized_bs_synonym_map, bs_keys_to_fetch)
  
  dfBalanceSheetQ_calc = apply_balance_sheet_fallbacks(df_normalize_BQ, ittelson_balance_sheet_columns)
  clean_quarterly_balance_sheet = format_statement_for_db(dfBalanceSheetQ_calc, ittelson_balance_sheet_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  
  dfBalanceSheetY_calc = apply_balance_sheet_fallbacks(df_normalize_BY, ittelson_balance_sheet_columns)
  clean_yearly_balance_sheet = format_statement_for_db(dfBalanceSheetY_calc, ittelson_balance_sheet_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)

elif use_yfinance:
  
  stmt_currency = tickerName.info.get('currency', 'USD') 
  stmt_multiplier = 0.000001
  
  df_normalize_BQ = map_statement_via_dictionary(dfBalanceSheetQ, normalized_bs_synonym_map, bs_keys_to_fetch)
  df_normalize_BY = map_statement_via_dictionary(dfBalanceSheetY, normalized_bs_synonym_map, bs_keys_to_fetch)
  
  dfBalanceSheetQ_calc = apply_balance_sheet_fallbacks(df_normalize_BQ, ittelson_balance_sheet_columns)
  clean_quarterly_balance_sheet = format_statement_for_db(dfBalanceSheetQ_calc, ittelson_balance_sheet_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  
  dfBalanceSheetY_calc = apply_balance_sheet_fallbacks(df_normalize_BY, ittelson_balance_sheet_columns)
  clean_yearly_balance_sheet = format_statement_for_db(dfBalanceSheetY_calc, ittelson_balance_sheet_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  
  display(clean_quarterly_balance_sheet)
  display(clean_yearly_balance_sheet)
  
else:
  
  stmt_currency = 'INR'
  stmt_multiplier = 10.0
  df_normalize_BY = map_statement_via_dictionary(dfBalanceSheetY, normalized_bs_synonym_map, bs_keys_to_fetch)
  dfBalanceSheetY_calc = apply_balance_sheet_fallbacks(df_normalize_BY, ittelson_balance_sheet_columns)
  clean_yearly_balance_sheet = format_statement_for_db(dfBalanceSheetY_calc, ittelson_balance_sheet_columns, tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  display(clean_yearly_balance_sheet)

,ReportDate,Ticker,Currency,CashCashEquivalentsAndShortTermInvestments,Receivables,Inventory,CurrentAssets,TotalNonCurrentAssets,GrossPPE,AccumulatedDepreciation,...,TotalAssets,PayablesAndAccruedExpenses,CurrentDebtAndCapitalLeaseObligation,TotalTaxPayable,CurrentLiabilities,LongTermDebtAndCapitalLeaseObligation,TotalLiabilitiesNetMinorityInterest,CapitalStock,RetainedEarnings,StockholdersEquity
0,2025-12-31,PLTR,USD,7177.04,1042.07,139.07,8358.17,542.22,401.16,-149.09,...,8900.39,363.69,45.86,0.00,1175.58,183.47,1412.38,2.39,-3562.39,7387.27
1,2025-09-30,PLTR,USD,6437.82,1005.91,142.43,7586.16,527.80,392.81,-142.79,...,8113.96,449.24,46.27,0.00,1180.40,189.16,1425.69,2.38,-4171.07,6590.46
2,2025-06-30,PLTR,USD,6000.42,747.48,142.49,6890.39,475.30,385.17,-138.18,...,7365.69,404.40,45.47,0.00,1089.64,192.35,1340.12,2.37,-4646.66,5928.90
3,2025-03-31,PLTR,USD,5430.69,725.21,126.70,6282.60,454.32,378.69,-129.67,...,6736.92,373.39,44.42,0.00,967.44,200.18,1217.94,2.36,-4973.39,5424.15
4,2024-12-31,PLTR,USD,5229.99,575.05,129.25,5934.29,406.60,363.38,-123.00,...,6340.88,427.15,43.99,42.24,996.02,195.23,1246.48,2.34,-5187.42,5003.27
5,2024-09-30,PLTR,USD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,31.95,0.00,0.00,0.00,0.00,0.00,0.00

,ReportDate,Ticker,Currency,CashCashEquivalentsAndShortTermInvestments,Receivables,Inventory,CurrentAssets,TotalNonCurrentAssets,GrossPPE,AccumulatedDepreciation,...,TotalAssets,PayablesAndAccruedExpenses,CurrentDebtAndCapitalLeaseObligation,TotalTaxPayable,CurrentLiabilities,LongTermDebtAndCapitalLeaseObligation,TotalLiabilitiesNetMinorityInterest,CapitalStock,RetainedEarnings,StockholdersEquity
0,2025-12-31,PLTR,USD,7177.04,1042.07,139.07,8358.17,542.22,401.16,-149.09,...,8900.39,363.69,45.86,0.00,1175.58,183.47,1412.38,2.39,-3562.39,7387.27
1,2024-12-31,PLTR,USD,5229.99,575.05,129.25,5934.29,406.60,363.38,-123.00,...,6340.88,427.15,43.99,42.24,996.02,195.23,1246.48,2.34,-5187.42,5003.27
2,2023-12-31,PLTR,USD,3674.18,364.78,99.66,4138.62,383.81,332.78,-102.16,...,4522.43,235.11,54.18,47.26,746.02,175.22,961.46,2.20,-5649.61,3475.56
3,2022-12-31,PLTR,USD,2633.68,258.35,149.56,3041.58,419.66,351.82,-82.41,...,3461.24,217.50,45.10,41.33,587.94,204.31,818.80,2.10,-5859.44,2565.33
4,2021-12-31,PLTR,USD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,22.55,0.00,0.00,0.00,0.00,0.00,0.00

In [582]:
quarterly_balance_sheet = Table(
    'quarterly_balance_sheet', metadata,
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    # Assets
    Column('CashCashEquivalentsAndShortTermInvestments', Numeric),
    Column('Receivables', Numeric),
    Column('Inventory', Numeric),
    Column('CurrentAssets', Numeric),
    Column('TotalNonCurrentAssets', Numeric),
    Column('GrossPPE', Numeric),
    Column('AccumulatedDepreciation', Numeric),
    Column('NetPPE', Numeric),
    Column('TotalAssets', Numeric),
    
    # Liabilities & Equity
    Column('PayablesAndAccruedExpenses', Numeric),
    Column('CurrentDebtAndCapitalLeaseObligation', Numeric),
    Column('TotalTaxPayable', Numeric),
    Column('CurrentLiabilities', Numeric),
    Column('LongTermDebtAndCapitalLeaseObligation', Numeric),
    Column('TotalLiabilitiesNetMinorityInterest', Numeric),
    Column('CapitalStock', Numeric),
    Column('RetainedEarnings', Numeric),
    Column('StockholdersEquity', Numeric)
)

# Define the Yearly Balance Sheet Architecture
yearly_balance_sheet = Table(
    'yearly_balance_sheet', metadata,
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    # Assets
    Column('CashCashEquivalentsAndShortTermInvestments', Numeric),
    Column('Receivables', Numeric),
    Column('Inventory', Numeric),
    Column('CurrentAssets', Numeric),
    Column('TotalNonCurrentAssets', Numeric),
    Column('GrossPPE', Numeric),
    Column('AccumulatedDepreciation', Numeric),
    Column('NetPPE', Numeric),
    Column('TotalAssets', Numeric),
    
    # Liabilities & Equity
    Column('PayablesAndAccruedExpenses', Numeric),
    Column('CurrentDebtAndCapitalLeaseObligation', Numeric),
    Column('TotalTaxPayable', Numeric),
    Column('CurrentLiabilities', Numeric),
    Column('LongTermDebtAndCapitalLeaseObligation', Numeric),
    Column('TotalLiabilitiesNetMinorityInterest', Numeric),
    Column('CapitalStock', Numeric),
    Column('RetainedEarnings', Numeric),
    Column('StockholdersEquity', Numeric)
)

# Build the tables in the database
metadata.create_all(engine)
print("Balance Sheet tables created successfully.")

Balance Sheet tables created successfully.

In [583]:

# Push the data using the custom Upsert method
clean_quarterly_balance_sheet.to_sql(
    name='quarterly_balance_sheet',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

clean_yearly_balance_sheet.to_sql(
    name='yearly_balance_sheet',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

print(" Balance Sheet Data successfully upserted into the database.")

 Balance Sheet Data successfully upserted into the database.

# Cash Flow Statement

In [584]:
# call yfinace balancesheet
raw_data_csq = get_yfinance(tickerName.ticker, "CASH_FLOW", "quarterly")
raw_data_csy = get_yfinance(tickerName.ticker, "CASH_FLOW", "yearly")

# check if has data and covert to dataframe
if raw_data_q is not None and raw_data_y is not None:
    
    dfCashFlowQ = pd.DataFrame(raw_data_csq)
    dfCashFlowY = pd.DataFrame(raw_data_csy)
    display(dfCashFlowQ)
    display(dfCashFlowY)
    
    if not dfCashFlowQ.empty and not dfCashFlowY.empty:
        use_yfinance = True
        print("Yfinance data loaded successfully. Setting use_yfinance = True.")
    else:
        use_yfinance = False
        print("Yfinance returned empty DataFrames. Falling back...")
else:
    
    use_yfinance = False
    dfCashFlowQ = None
    dfCashFlowY = None
    print("Yfinance data incomplete. Falling back to Alpha Vantage...")

Loading yfinance offline_statements\yfinance_PLTR_CASH_FLOW_quarterly.json from local cache
Loading yfinance offline_statements\yfinance_PLTR_CASH_FLOW_yearly.json from local cache

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
FreeCashFlow,764023000.00,500872000.00,531617000.00,304079000.00,457221000,NaN
RepurchaseOfCapitalStock,-19196000.00,-19195000.00,-18596000.00,-17998000.00,-18598000,NaN
CapitalExpenditure,-13272000.00,-6792000.00,-7634000.00,-6184000.00,-3106000,NaN
EndCashPosition,1451425000.00,1644826000.00,951234000.00,1015005000.00,2119936000,NaN
BeginningCashPosition,1644826000.00,951234000.00,1015005000.00,2119936000.00,788456000,NaN
EffectOfExchangeRateChanges,-1967000.00,-2074000.00,7538000.00,3980000.00,-7705000,NaN
ChangesInCash,-191434000.00,695666000.00,-71309000.00,-1108911000.00,1339185000,NaN
FinancingCashFlow,-10898000.00,6435000.00,6450000.00,-28897000.00,238664000,NaN
CashFlowFromContinuingFinancingActivities,-10898000.00,6435000.00,6450000.00,-28897000.00,238664000,NaN
NetOtherFinancingCharges,30000.00,-8000.00,-3571000.00,-77483000.00,-217927000,NaN
ProceedsFromStockOptionExercised,8268000.00,25638000.00,28617000.00,66584000.00,475189000,NaN
NetCommonStockIssuance,-19196000.00,-19195000.00,-18596000.00,-17998000.00,-18598000,NaN
CommonStockPayments,-19196000.00,-19195000.00,-18596000.00,-17998000.00,-18598000,NaN
InvestingCashFlow,-957831000.00,181567000.00,-617010000.00,-1390277000.00,640194000,NaN
CashFlowFromContinuingInvestingActivities,-957831000.00,181567000.00,-617010000.00,-1390277000.00,640194000,NaN
NetOtherInvestingChanges,0.00,NaN,NaN,-30000000.00,-1615000,0.00
NetInvestmentPurchaseAndSale,-944559000.00,189359000.00,-639376000.00,-1354093000.00,644915000,NaN
SaleOfInvestment,665988000.00,3707565000.00,302135000.00,350627000.00,2622129000,NaN
PurchaseOfInvestment,-1610547000.00,-3518206000.00,-941511000.00,-1704720000.00,-1977214000,NaN
NetPPEPurchaseAndSale,-13272000.00,-6792000.00,-7634000.00,-6184000.00,-3106000,NaN
PurchaseOfPPE,-13272000.00,-6792000.00,-7634000.00,-6184000.00,-3106000,NaN
OperatingCashFlow,777295000.00,507664000.00,539251000.00,310263000.00,460327000,NaN
CashFlowFromContinuingOperatingActivities,777295000.00,507664000.00,539251000.00,310263000.00,460327000,NaN
ChangeInWorkingCapital,-48564000.00,-134522000.00,39444000.00,-66321000.00,104156000,NaN
ChangeInOtherWorkingCapital,78534000.00,39488000.00,101906000.00,18760000.00,-55544000,NaN
ChangeInOtherCurrentLiabilities,-15359000.00,-14564000.00,-11690000.00,-13247000.00,-15150000,NaN
ChangeInOtherCurrentAssets,NaN,NaN,NaN,NaN,625000,-1515000.00
ChangeInPayablesAndAccruedExpense,-85923000.00,42380000.00,25807000.00,22395000.00,46934000,NaN
ChangeInAccruedExpense,NaN,NaN,NaN,NaN,73485000,72697000.00
ChangeInPayable,-85923000.00,42380000.00,25807000.00,22395000.00,-26551000,NaN
ChangeInAccountPayable,-85923000.00,42380000.00,25807000.00,22395000.00,-26551000,NaN
ChangeInPrepaidAssets,1636000.00,57650000.00,-48037000.00,40730000.00,26749000,NaN
ChangeInReceivables,-27452000.00,-259476000.00,-28542000.00,-134959000.00,100542000,NaN
ChangesInAccountReceivables,-27452000.00,-259476000.00,-28542000.00,-134959000.00,100542000,NaN
OtherNonCashItems,-5394000.00,-18312000.00,15874000.00,-13782000.00,-2854000,NaN
StockBasedCompensation,196405000.00,172318000.00,159971000.00,155339000.00,281798000,NaN
UnrealizedGainLossOnInvestmentSecurities,16223000.00,5457000.00,-11140000.00,10688000.00,-6715000,NaN
DepreciationAmortizationDepletion,7018000.00,5975000.00,6530000.00,6622000.00,7006000,NaN
DepreciationAndAmortization,7018000.00,5975000.00,6530000.00,6622000.00,7006000,NaN
NetIncomeFromContinuingOperations,611607000.00,476748000.00,328572000.00,217717000.00,76936000,NaN

,2025-12-31,2024-12-31,2023-12-31,2022-12-31,2021-12-31
FreeCashFlow,2100591000.00,1141231000.00,697069000.00,183710000.00,NaN
RepurchaseOfCapitalStock,-74985000.00,-64196000.00,0.00,0.00,NaN
RepaymentOfDebt,NaN,NaN,0.00,0.00,-200000000.00
IssuanceOfDebt,NaN,NaN,NaN,0.00,0.00
IssuanceOfCapitalStock,NaN,NaN,NaN,0.00,0.00
CapitalExpenditure,-33882000.00,-12634000.00,-15114000.00,-40027000.00,NaN
InterestPaidSupplementalData,NaN,NaN,NaN,5000.00,2774000.00
IncomeTaxPaidSupplementalData,NaN,16179000.00,13515000.00,2904000.00,4131000.00
EndCashPosition,1451425000.00,2119936000.00,850107000.00,2627335000.00,NaN
BeginningCashPosition,2119936000.00,850107000.00,2627335000.00,2366914000.00,NaN
EffectOfExchangeRateChanges,7477000.00,-6745000.00,2930000.00,-3885000.00,NaN
ChangesInCash,-675988000.00,1276574000.00,-1780158000.00,264306000.00,NaN
FinancingCashFlow,-26910000.00,463364000.00,218839000.00,85996000.00,NaN
CashFlowFromContinuingFinancingActivities,-26910000.00,463364000.00,218839000.00,85996000.00,NaN
NetOtherFinancingCharges,-81032000.00,-217836000.00,601000.00,-93000.00,NaN
ProceedsFromStockOptionExercised,129107000.00,745396000.00,218238000.00,86089000.00,NaN
NetPreferredStockIssuance,NaN,NaN,NaN,NaN,0.00
PreferredStockPayments,NaN,NaN,NaN,NaN,0.00
PreferredStockIssuance,NaN,NaN,NaN,NaN,0.00
NetCommonStockIssuance,-74985000.00,-64196000.00,0.00,0.00,NaN
CommonStockPayments,-74985000.00,-64196000.00,0.00,0.00,NaN
CommonStockIssuance,NaN,NaN,NaN,0.00,0.00
NetIssuancePaymentsOfDebt,NaN,NaN,0.00,0.00,-200000000.00
NetLongTermDebtIssuance,NaN,NaN,0.00,0.00,-200000000.00
LongTermDebtPayments,NaN,NaN,0.00,0.00,-200000000.00
LongTermDebtIssuance,NaN,NaN,NaN,0.00,0.00
InvestingCashFlow,-2783551000.00,-340655000.00,-2711180000.00,-45427000.00,NaN
CashFlowFromContinuingInvestingActivities,-2783551000.00,-340655000.00,-2711180000.00,-45427000.00,NaN
NetOtherInvestingChanges,-1000000.00,-5615000.00,51072000.00,66781000.00,NaN
NetInvestmentPurchaseAndSale,-2748669000.00,-328021000.00,-2747138000.00,-72181000.00,NaN
SaleOfInvestment,5026315000.00,5073507000.00,2889268000.00,52319000.00,NaN
PurchaseOfInvestment,-7774984000.00,-5401528000.00,-5636406000.00,-124500000.00,NaN
NetBusinessPurchaseAndSale,NaN,NaN,0.00,66708000.00,0.00
SaleOfBusiness,NaN,NaN,0.00,66708000.00,0.00
PurchaseOfBusiness,NaN,NaN,NaN,NaN,0.00
NetPPEPurchaseAndSale,-33882000.00,-12634000.00,-15114000.00,-40027000.00,NaN
PurchaseOfPPE,-33882000.00,-12634000.00,-15114000.00,-40027000.00,NaN
OperatingCashFlow,2134473000.00,1153865000.00,712183000.00,223737000.00,NaN
CashFlowFromContinuingOperatingActivities,2134473000.00,1153865000.00,712183000.00,223737000.00,NaN
ChangeInWorkingCapital,-209963000.00,-70097000.00,6236000.00,-261217000.00,NaN
ChangeInOtherWorkingCapital,238688000.00,76796000.00,143859000.00,-110625000.00,NaN
ChangeInOtherCurrentLiabilities,-54860000.00,-44412000.00,-49572000.00,-34663000.00,NaN
ChangeInOtherCurrentAssets,NaN,4681000.00,3242000.00,6033000.00,-3345000.00
ChangeInPayablesAndAccruedExpense,4659000.00,96793000.00,21063000.00,-24332000.00,NaN
ChangeInAccruedExpense,NaN,115634000.00,52895000.00,5527000.00,15245000.00
ChangeInPayable,4659000.00,96793000.00,21063000.00,-29859000.00,NaN
ChangeInAccountPayable,4659000.00,96793000.00,21063000.00,-29859000.00,NaN
ChangeInPrepaidAssets,51979000.00,11883000.00,-2955000.00,-24811000.00,NaN
ChangeInReceivables,-450429000.00,-211157000.00,-106159000.00,-72819000.00,NaN
ChangesInAccountReceivables,-450429000.00,-211157000.00,-106159000.00,-72819000.00,NaN
OtherNonCashItems,-21614000.00,13513000.00,-33845000.00,-3380000.00,NaN
StockBasedCompensation,684033000.00,691638000.00,475903000.00,564798000.00,NaN
UnrealizedGainLossOnInvestmentSecurities,21228000.00,19306000.00,13160000.00,272108000.00,NaN
AssetImpairmentCharge,NaN,NaN,NaN,NaN,0.00
DeferredTax,NaN,NaN,-4806000.00,-174000.00,43316000.00
DeferredIncomeTax,NaN,NaN,-4806000.00,-174000.00,43316000.00
DepreciationAmortizationDepletion,26145000.00,31587000.00,33354000.00,22522000.00,NaN
DepreciationAndAmortization,26145000.00,31587000.00,33354000.00,22522000.00,NaN
NetIncomeFromContinuingOperations,1634644000.00,467918000.00,217375000.00,-371094000.00,NaN

Yfinance data loaded successfully. Setting use_yfinance = True.

In [585]:
#call alpha vantage balancesheet
alpha_vantage = False

if dfCashFlowQ is None or dfCashFlowQ is None:
    # Use the new fetch/cache function
    ticker = tickerName.ticker
    avB_data = get_alpha_vantage(ticker, 'CASH_FLOW', API_KEY)
    
    if avB_data:
        alpha_vantage_balance_sheet_quarterly = avB_data["quarterlyReports"]
        alpha_vantage_balance_sheet_yearly = avB_data["annualReports"]
        alpha_vantage = True

# Standard Status Checks
if not alpha_vantage and dfCashFlowQ is not None:
    print("Using yfinance statements.")
elif not alpha_vantage and dfCashFlowQ is None:
    print("CRITICAL: No data found in yfinance OR local Alpha Vantage cache.")
    

if alpha_vantage:

  dfCashFlowQ = pd.DataFrame(alpha_vantage_balance_sheet_quarterly)
  dfCashFlowY =  pd.DataFrame(alpha_vantage_balance_sheet_yearly)
  
  dfCashFlowQ = dfCashFlowQ.set_index("fiscalDateEnding")
  dfCashFlowY = dfCashFlowY.set_index("fiscalDateEnding")

  display(dfCashFlowQ)
  display(dfCashFlowY)

Using yfinance statements.

In [586]:
#call screener scrapper balance sheet
if not use_yfinance and not alpha_vantage:
  #dfBalanceSheetQ = pd.DataFrame(get_screener_financials(tickerName.ticker, report_type='balance-sheet'))
  dfCashFlowY = pd.DataFrame(get_screener_financials(tickerName.ticker, report_type='cash-flow'))
  #display(dfBalanceSheetQ)
  display(dfCashFlowY.index)

In [587]:

ittelson_cash_flow_columns = [
    'BeginningCashBalance',
    'CashReceipts',
    'CashDisbursements',
    'CashFromOperations',
    'FixedAssetPurchases',
    'NetBorrowing',
    'IncomeTaxPaid',
    'SaleOfStock',
    'EndingCashBalance'
]



normalized_cf_synonym_map = {
    
    'BeginningCashBalance': [
        'BeginningCashBalance',
        'BeginningCashPosition'
    ],
    
    'CashReceipts': [],
    
    'CashDisbursements': [],
    
    'CashFromOperations': [
        'CashFromOperations',
        'CashFlowFromContinuingOperatingActivities', # Prioritized to avoid yfinance NaN rows
        'OperatingCashFlow',
        'CashFromOperatingActivity' 
    ],
    
    'FixedAssetPurchases': [
        'FixedAssetPurchases',
        'CapitalExpenditure', # Prioritized for US
        'PurchaseOfPPE',
        'FixedAssetsPurchased' 
    ],
    
    'NetBorrowing': [
        'NetBorrowing',
        'NetIssuancePaymentsOfDebt', 
        'NetLongTermDebtIssuance' # Added for US Yearly
    ],
    
    'IncomeTaxPaid': [
        'IncomeTaxPaid',
        'IncomeTaxPaidSupplementalData', # Added for US Yearly
        'TaxesRefundPaid', 
        'DirectTaxes' 
    ],
    
    'SaleOfStock': [
        'SaleOfStock',
        'NetCommonStockIssuance', # Prioritized for US Quarterly
        'IssuanceOfCapitalStock',
        'CommonStockIssuance',
        'ProceedsFromShares' 
    ],
    
    'EndingCashBalance': [
        'EndingCashBalance',
        'EndCashPosition'
    ],

    # Components for calculating missing Net Borrowing
    'RepaymentOfBorrowings': ['RepaymentOfDebt', 'RepaymentOfBorrowings', 'Repayment of borrowings'],   
    'IssuanceOfDebt': ['IssuanceOfDebt', 'ProceedsFromBorrowings', 'Proceeds from borrowings'],                 
    'RepaymentOfDebt': ['RepaymentOfDebt'],             
    
    # Components for tracking missing Cash Balances
    'NetCashFlow': ['NetCashFlow', 'ChangesInCash', 'Net Cash Flow']
}

In [588]:

def apply_cash_flow_fallbacks(df, target_columns, df_is_calc=None, df_bs_calc=None):

    #  NET BORROWING 
    if df.loc['NetBorrowing'].isna().any():
        if 'IssuanceOfDebt' in df.index and 'RepaymentOfDebt' in df.index:
            calc_borrowing = df.loc['IssuanceOfDebt'].fillna(0) - df.loc['RepaymentOfDebt'].fillna(0)
            
            # Ensure we only fill where we actually had data (don't inject 0s if both were NaN)
            has_debt_data = ~(df.loc['IssuanceOfDebt'].isna() & df.loc['RepaymentOfDebt'].isna())
            df.loc['NetBorrowing'] = df.loc['NetBorrowing'].fillna(calc_borrowing.where(has_debt_data))

    #  NET BORROWING (Balance Sheet Bridge for missing Q data) 
    if df.loc['NetBorrowing'].isna().any() and df_bs_calc is not None:
        if 'LongTermDebtAndCapitalLeaseObligation' in df_bs_calc.index and 'CurrentDebtAndCapitalLeaseObligation' in df_bs_calc.index:
            common_cols = df.columns.intersection(df_bs_calc.columns)
            
            total_debt = df_bs_calc.loc['LongTermDebtAndCapitalLeaseObligation', common_cols].fillna(0) + \
                         df_bs_calc.loc['CurrentDebtAndCapitalLeaseObligation', common_cols].fillna(0)
            
            # Temporarily sort chronologically to calculate the difference
            temp_s = total_debt.copy()
            original_idx = temp_s.index
            temp_s.index = pd.to_datetime(temp_s.index)
            diff_s = temp_s.sort_index().diff()
            
            mapping = {pd.to_datetime(idx): idx for idx in original_idx}
            diff_s.index = diff_s.index.map(mapping)
            calc_bridge = diff_s[original_idx]
            
            df.loc['NetBorrowing', common_cols] = df.loc['NetBorrowing', common_cols].fillna(calc_bridge)

    #  ENDING CASH (From Balance Sheet)
    # We always bridge this directly from the BS as the absolute source of truth
    if df.loc['EndingCashBalance'].isna().any() and df_bs_calc is not None:
        if 'CashCashEquivalentsAndShortTermInvestments' in df_bs_calc.index:
            common_cols = df.columns.intersection(df_bs_calc.columns)
            df.loc['EndingCashBalance', common_cols] = df.loc['EndingCashBalance', common_cols].fillna(
                df_bs_calc.loc['CashCashEquivalentsAndShortTermInvestments', common_cols]
            )

    #  BEGINNING CASH (Internal CF Math) 
    # Strictly calculated using the bridged Ending Cash and the internal NetCashFlow
    if df.loc['BeginningCashBalance'].isna().any():
        if 'NetCashFlow' in df.index:
            calc_beg = df.loc['EndingCashBalance'].fillna(0) - df.loc['NetCashFlow'].fillna(0)
            has_beg_data = ~(df.loc['EndingCashBalance'].isna() & df.loc['NetCashFlow'].isna())
            df.loc['BeginningCashBalance'] = df.loc['BeginningCashBalance'].fillna(calc_beg.where(has_beg_data))

    #  DIRECT METHOD CONVERSIONS
    # Cash Receipts (Income Statement Bridge)
    if df.loc['CashReceipts'].isna().any() and df_is_calc is not None:
        if 'TotalRevenue' in df_is_calc.index:
            common_cols = df.columns.intersection(df_is_calc.columns)
            df.loc['CashReceipts', common_cols] = df.loc['CashReceipts', common_cols].fillna(
                df_is_calc.loc['TotalRevenue', common_cols]
            )
            
    # Cash Disbursements (Internal CF Math)
    if df.loc['CashDisbursements'].isna().any():
        calc_disbursements = df.loc['CashReceipts'].fillna(0) - df.loc['CashFromOperations'].fillna(0)
        has_disb_data = ~(df.loc['CashReceipts'].isna() & df.loc['CashFromOperations'].isna())
        df.loc['CashDisbursements'] = df.loc['CashDisbursements'].fillna(calc_disbursements.where(has_disb_data))

    #  FINAL CLEANUP
    final_df = df.loc[target_columns].fillna(0)
    
    return final_df

In [589]:

#Clean
if use_yfinance or alpha_vantage: 
  dfCashFlowQ = to_pascal_case(dfCashFlowQ)
  dfCashFlowY = to_pascal_case(dfCashFlowY)

  dfCashFlowQ = standardize_dataframe_labels(dfCashFlowQ)
  dfCashFlowY = standardize_dataframe_labels(dfCashFlowY)

  dfCashFlowQ = clean_financial_dataframe(dfCashFlowQ)
  dfCashFlowY = clean_financial_dataframe(dfCashFlowY)
  
else:
  
  dfCashFlowY = to_pascal_case(dfCashFlowY)
  dfCashFlowY = standardize_dataframe_labels(dfCashFlowY)
  dfCashFlowY = clean_financial_dataframe(dfCashFlowY)

In [590]:
#map
cf_keys_to_fetch = ittelson_cash_flow_columns + [
    'IssuanceOfDebt', 
    'RepaymentOfDebt',
    'NetCashFlow' 
]

if alpha_vantage:
  
  stmt_currency = 'USD' 
  stmt_multiplier = 0.000001
  
  df_normalize_CQ = map_statement_via_dictionary(dfCashFlowQ, normalized_cf_synonym_map, cf_keys_to_fetch)
  df_normalize_CY = map_statement_via_dictionary(dfCashFlowY, normalized_cf_synonym_map, cf_keys_to_fetch)
  
  dfCashFlowQ_calc = apply_cash_flow_fallbacks(df_normalize_CQ, ittelson_cash_flow_columns,df_is_calc=dfIncomeStatementQ_calc,df_bs_calc=dfBalanceSheetQ_calc)
  clean_quarterly_cash_flow = format_statement_for_db(dfCashFlowQ_calc, ittelson_cash_flow_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  
  dfCashFlowY_calc = apply_cash_flow_fallbacks(df_normalize_CY, ittelson_cash_flow_columns,df_is_calc=dfIncomeStatementY_calc,df_bs_calc=dfBalanceSheetY_calc)
  clean_yearly_cash_flow = format_statement_for_db(dfCashFlowY_calc, ittelson_cash_flow_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  

elif use_yfinance:
  
  stmt_currency = tickerName.info.get('currency', 'USD') 
  stmt_multiplier = 0.000001
  
  df_normalize_CQ = map_statement_via_dictionary(
    dfCashFlowQ, normalized_cf_synonym_map, cf_keys_to_fetch)
  
  df_normalize_CY = map_statement_via_dictionary(
    dfCashFlowY, normalized_cf_synonym_map, cf_keys_to_fetch)
  
  dfCashFlowQ_calc = apply_cash_flow_fallbacks(
    df_normalize_CQ, ittelson_cash_flow_columns, df_is_calc=dfIncomeStatementQ_calc, df_bs_calc=dfBalanceSheetQ_calc)
  
  clean_quarterly_cash_flow = format_statement_for_db(
    dfCashFlowQ_calc, ittelson_cash_flow_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  
  dfCashFlowY_calc = apply_cash_flow_fallbacks(
    df_normalize_CY, ittelson_cash_flow_columns, df_is_calc=dfIncomeStatementY_calc, df_bs_calc=dfBalanceSheetY_calc)
  
  clean_yearly_cash_flow = format_statement_for_db(
    dfCashFlowY_calc, ittelson_cash_flow_columns,tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  
  display(clean_quarterly_cash_flow)
  display(clean_yearly_cash_flow)
  
else:
  
  stmt_currency = 'INR'
  stmt_multiplier = 10.0
  df_normalize_CY = map_statement_via_dictionary(
    dfCashFlowY, normalized_cf_synonym_map, cf_keys_to_fetch)
  
  dfCashFlowY_calc = apply_cash_flow_fallbacks(
    df_normalize_CY, ittelson_cash_flow_columns,df_is_calc=dfIncomeStatementY_calc,df_bs_calc=dfBalanceSheetY_calc)
  
  clean_yearly_cash_flow = format_statement_for_db(
    dfCashFlowY_calc, ittelson_cash_flow_columns, tickerName.ticker,currency=stmt_currency, multiplier=stmt_multiplier, transpose=True)
  
  display(clean_yearly_cash_flow)

,ReportDate,Ticker,Currency,BeginningCashBalance,CashReceipts,CashDisbursements,CashFromOperations,FixedAssetPurchases,NetBorrowing,IncomeTaxPaid,SaleOfStock,EndingCashBalance
0,2025-12-31,PLTR,USD,1644.83,1406.80,629.51,777.29,-13.27,-6.10,0.00,-19.20,1451.42
1,2025-09-30,PLTR,USD,951.23,1181.09,673.43,507.66,-6.79,-2.38,0.00,-19.20,1644.83
2,2025-06-30,PLTR,USD,1015.00,1003.70,464.45,539.25,-7.63,-6.78,0.00,-18.60,951.23
3,2025-03-31,PLTR,USD,2119.94,883.86,573.59,310.26,-6.18,5.38,0.00,-18.00,1015.00
4,2024-12-31,PLTR,USD,788.46,827.52,367.19,460.33,-3.11,239.22,0.00,-18.60,2119.94
5,2024-09-30,PLTR,USD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

,ReportDate,Ticker,Currency,BeginningCashBalance,CashReceipts,CashDisbursements,CashFromOperations,FixedAssetPurchases,NetBorrowing,IncomeTaxPaid,SaleOfStock,EndingCashBalance
0,2025-12-31,PLTR,USD,2119.94,4475.45,2340.97,2134.47,-33.88,-9.88,0.00,-74.98,1451.42
1,2024-12-31,PLTR,USD,850.11,2865.51,1711.64,1153.87,-12.63,9.83,16.18,-64.20,2119.94
2,2023-12-31,PLTR,USD,2627.34,2225.01,1512.83,712.18,-15.11,0.00,13.52,0.00,850.11
3,2022-12-31,PLTR,USD,2366.91,1905.87,1682.13,223.74,-40.03,0.00,2.90,0.00,2627.34
4,2021-12-31,PLTR,USD,0.00,0.00,0.00,0.00,0.00,-200.00,4.13,0.00,0.00

In [591]:

# Define the Quarterly Cash Flow Architecture
quarterly_cash_flow = Table(
    'quarterly_cash_flow', metadata,
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    
    Column('BeginningCashBalance', Numeric),
    Column('CashReceipts', Numeric),
    Column('CashDisbursements', Numeric),
    Column('CashFromOperations', Numeric),
    Column('FixedAssetPurchases', Numeric),
    Column('NetBorrowing', Numeric),
    Column('IncomeTaxPaid', Numeric),
    Column('SaleOfStock', Numeric),
    Column('EndingCashBalance', Numeric)
)

# Define the Yearly Cash Flow Architecture
yearly_cash_flow = Table(
    'yearly_cash_flow', metadata,
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    
    Column('BeginningCashBalance', Numeric),
    Column('CashReceipts', Numeric),
    Column('CashDisbursements', Numeric),
    Column('CashFromOperations', Numeric),
    Column('FixedAssetPurchases', Numeric),
    Column('NetBorrowing', Numeric),
    Column('IncomeTaxPaid', Numeric),
    Column('SaleOfStock', Numeric),
    Column('EndingCashBalance', Numeric)
)

# Build the tables in the database
metadata.create_all(engine)
print("Cash Flow tables created successfully.")

Cash Flow tables created successfully.

In [ ]:

# Push the data using the custom Upsert method
clean_quarterly_cash_flow.to_sql(
    name='quarterly_cash_flow',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

clean_yearly_cash_flow.to_sql(
    name='yearly_cash_flow',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

print(" Cash Flow Data successfully upserted into the database.")

 Balance Sheet Data successfully upserted into the database.