In [1]:
import time
import yfinance as yf
import os
import requests
import pandas as pd
import urllib3
import json
import re
import numpy as np
import urllib.parse
from bs4 import BeautifulSoup
from sqlalchemy import create_engine, Column, String, Date, Numeric, MetaData, Table, Boolean
from sqlalchemy.dialects.postgresql import insert

In [2]:
#vantage api key
API_KEY = "V6FLFA1K7ECKP0RK"
#disable certificate warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [3]:
CACHE_DIR = "offline_statements"
if not os.path.exists(CACHE_DIR):
    os.makedirs(CACHE_DIR)
    print(f"Created folder: {CACHE_DIR}")

In [4]:
#HOME_PC_DB

engine = create_engine(
    "postgresql+psycopg2://postgres:123456@localhost:5432/postgres"
)

In [5]:
# Yfinance
def get_yfinance(ticker, statement_type, freq, cache_dir=CACHE_DIR):
    if freq not in ("quarterly", "yearly"):
        raise ValueError("freq must be 'quarterly' or 'yearly'")
    
    if not os.path.exists(cache_dir):
        os.mkdir(cache_dir)
        
    filename = f"yfinance_{ticker}_{statement_type}_{freq}.json"
    file_path = os.path.join(cache_dir, filename)
    
    if os.path.exists(file_path):
        print(f"Loading yfinance {file_path} from local cache")
        with open(file_path, 'r') as f:
            return pd.read_json(file_path)
    
    print(f"Fetching {ticker} {statement_type} from Yfinance")
    
    # NEW: Create a local ticker instance so it changes with every loop iteration
    yf_ticker = yf.Ticker(ticker) 
    
    # call yfinance using the local yf_ticker instead of global tickerName
    if statement_type == "INCOME_STATEMENT":
        df = yf_ticker.get_income_stmt(as_dict=False, pretty=False, freq=freq)
    elif statement_type == "BALANCE_SHEET":
        df = yf_ticker.get_balance_sheet(as_dict=False, pretty=False, freq=freq)
    else:
        # Simplifies the CF logic as freq is already passed correctly
        df = yf_ticker.get_cash_flow(as_dict=False, pretty=False, freq=freq)
          
    if df is None or df.empty:   
        print(f"No {freq} {statement_type} available from yfinance")
        return None

    # Save to cache
    df.to_json(file_path)
    print(f"Saved yfinance {ticker} {statement_type} {freq} to cache")
    
    return df

In [6]:
# Alpha Vantage
def get_alpha_vantage(ticker, statement_type, api_key, cache_dir=CACHE_DIR):
    if not os.path.exists(cache_dir):
        os.makedirs(cache_dir)
    
    filename = f"vantage_{ticker}_{statement_type}.json"
    file_path = os.path.join(cache_dir, filename)
    
    if os.path.exists(file_path):
        print(f"Loading vantage {ticker} {statement_type} from local cache")
        with open(file_path, 'r') as f:
            return json.load(f)
    
    print(f"Fetching {ticker} {statement_type} from Alpha Vantage")
    url = (f"https://www.alphavantage.co/query"
           f"?function={statement_type}"
           f"&symbol={ticker}"
           f"&apikey={api_key}")
    
    try:
        response = requests.get(url, verify=False, timeout=20)
        data = response.json()
        
        # CHANGED: Check for either annual or quarterly reports to be more robust
        if "annualReports" in data or "quarterlyReports" in data:
            with open(file_path, 'w') as f:
                json.dump(data, f)
            print(f"Successfully saved {ticker} to local cache.")
            return data
        else:
            error_msg = data.get("Note", data.get("Error Message", "Unknown Error"))
            print(f"Alpha Vantage Error/Limit for {ticker}: {error_msg}")
            return None
            
    except Exception as e:
        print(f"Request failed for {ticker}: {e}")
        return None

In [7]:
#SCREENER SCRAPPER
def get_screener_financials(ticker, report_type="yearly"):
    filename = f"screener_{ticker}_{report_type}.json"
    file_path = os.path.join(CACHE_DIR, filename)

    # Check Cache
    if os.path.exists(file_path):
        print(f"Loading {ticker} {report_type} from Screener cache...")
        with open(file_path, 'r') as f:
            return json.load(f)
  
    # Use a Session to retain cookies across requests
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "X-Requested-With": "XMLHttpRequest" # Tells Screener this is an AJAX API call
    })
    
    url = f"https://www.screener.in/company/{ticker}/"
    response = session.get(url)
    
    if response.status_code != 200:
        print(f"Error fetching Screener page: {response.status_code}")
        return None
    
    soup = BeautifulSoup(response.text, "html.parser")
    
    # Extract the hidden Company ID for sub item api
    company_div = soup.find(attrs={"data-company-id": True})
    if not company_div:
        print(f"Could not find company ID for {ticker}")
        return None
    company_id = company_div["data-company-id"]
    
    # Identify the section ID
    section_id = []
    if report_type == "quarterly" :
        section_id = "quarters"
    elif report_type == "yearly":
        section_id = 'profit-loss'
    elif report_type == "balance-sheet":
        section_id = 'balance-sheet'
    else:
        section_id = 'cash-flow'
        
    statement_section = soup.find("section", {"id": section_id})
    
    if not statement_section:
        print(f"Could not find {report_type} section for {ticker}")
        return None
  
    table = statement_section.find("table", class_="data-table")
    
    if table:
        # EXACT ORIGINAL PARSING: Date columns (Headers)
        headers = [th.get_text(strip=True) for th in table.find("thead").find_all("th")][1:]
        financial_data = {date: {} for date in headers}
        
        # Parse Rows (Main Line Items)
        for tr in table.find("tbody").find_all("tr"):
            cells = tr.find_all("td")
            if cells:
                row_label_cell = cells[0]
                
                # EXACT ORIGINAL PARSING
                row_label = row_label_cell.get_text(strip=True).replace("+", "").strip()
                row_values = [td.get_text(strip=True).replace(",", "") for td in cells[1:]]
                
                for i, date in enumerate(headers):
                    if i < len(row_values):
                        financial_data[date][row_label] = row_values[i]
                
                button = row_label_cell.find("button")
                if button:
                    safe_parent = urllib.parse.quote(row_label)
                    api_url = f"https://www.screener.in/api/company/{company_id}/schedules/?parent={safe_parent}&section={section_id}"
                    
                    try:
                        # ARCHITECTURAL FIX: Add a half-second delay so the bot doesn't ban us during the loop
                        time.sleep(0.5) 
                        
                        sub_response = session.get(api_url)
                        if sub_response.status_code == 200:
                            sub_data = sub_response.json()
                            
                            for sub_label, date_values in sub_data.items():
                                final_label = f"{sub_label}"
                                
                                for d in headers:
                                    financial_data[d][final_label] = "0"
                                
                                for date_key, val in date_values.items():
                                    clean_api_date = date_key.strip()
                                    
                                    if clean_api_date in financial_data:
                                        financial_data[clean_api_date][final_label] = str(val).replace(",", "")
                        else:
                            # ARCHITECTURAL FIX: Explicitly print the error code so we aren't blind
                            print(f"    - Sub-API Error for '{row_label}': {sub_response.status_code}")
                            
                    except Exception as e:
                        print(f"    - Assignment failed for '{row_label}': {e}")
                    
        print(f"\nFinalized scraping {report_type} data from Screener.")           
        with open(file_path, 'w') as f:
            json.dump(financial_data, f)
              
        return financial_data
    
    return None

In [8]:
#use_yfinance = False
#dfIncomeStatementQ = None
#dfIncomeStatementY = None

## SQL TABLE METADATA

In [9]:

metadata = MetaData(schema='public')
metadata.create_all(engine)

#Define the architecture
quarterly_income_statement = Table(
    'quarterly_income_statement', metadata,
    Column('DataSource', String(50)),
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)
#Define the architecture
yearly_income_statement = Table(
    'yearly_income_statement', metadata,
    Column('DataSource', String(50)),
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    Column('IsValid', Boolean),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)


## Drop the old tables
#quarterly_income_statement.drop(engine, checkfirst=True)
#yearly_income_statement.drop(engine, checkfirst=True)

## Create the new tables with the Primary Keys
#metadata.create_all(engine)
#print("Tables dropped and recreated with proper Primary Keys!")
##Build the table in the database


print("Tables created successfully.")

Tables created successfully.

In [10]:

quarterly_balance_sheet = Table(
    'quarterly_balance_sheet', metadata,
    Column('DataSource', String(50)),
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    
    # Assets
    Column('CashCashEquivalentsAndShortTermInvestments', Numeric),
    Column('Receivables', Numeric),
    Column('Inventory', Numeric),
    Column('CurrentAssets', Numeric),
    Column('TotalNonCurrentAssets', Numeric),
    Column('GrossPPE', Numeric),
    Column('AccumulatedDepreciation', Numeric),
    Column('NetPPE', Numeric),
    Column('TotalAssets', Numeric),
    
    # Liabilities & Equity
    Column('PayablesAndAccruedExpenses', Numeric),
    Column('CurrentDebtAndCapitalLeaseObligation', Numeric),
    Column('TotalTaxPayable', Numeric),
    Column('CurrentLiabilities', Numeric),
    Column('LongTermDebtAndCapitalLeaseObligation', Numeric),
    Column('TotalLiabilitiesNetMinorityInterest', Numeric),
    Column('CapitalStock', Numeric),
    Column('RetainedEarnings', Numeric),
    Column('StockholdersEquity', Numeric)
)

# Define the Yearly Balance Sheet Architecture
yearly_balance_sheet = Table(
    'yearly_balance_sheet', metadata,
    Column('DataSource', String(50)),
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    Column('IsValid', Boolean),
    # Assets
    Column('CashCashEquivalentsAndShortTermInvestments', Numeric),
    Column('Receivables', Numeric),
    Column('Inventory', Numeric),
    Column('CurrentAssets', Numeric),
    Column('TotalNonCurrentAssets', Numeric),
    Column('GrossPPE', Numeric),
    Column('AccumulatedDepreciation', Numeric),
    Column('NetPPE', Numeric),
    Column('TotalAssets', Numeric),
    
    # Liabilities & Equity
    Column('PayablesAndAccruedExpenses', Numeric),
    Column('CurrentDebtAndCapitalLeaseObligation', Numeric),
    Column('TotalTaxPayable', Numeric),
    Column('CurrentLiabilities', Numeric),
    Column('LongTermDebtAndCapitalLeaseObligation', Numeric),
    Column('TotalLiabilitiesNetMinorityInterest', Numeric),
    Column('CapitalStock', Numeric),
    Column('RetainedEarnings', Numeric),
    Column('StockholdersEquity', Numeric)
)

# Build the tables in the database
metadata.create_all(engine)
print("Balance Sheet tables created successfully.")

Balance Sheet tables created successfully.

In [11]:


# Define the Quarterly Cash Flow Architecture
quarterly_cash_flow = Table(
    'quarterly_cash_flow', metadata,
    Column('DataSource', String(50)),
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    
    Column('BeginningCashBalance', Numeric),
    Column('CashReceipts', Numeric),
    Column('CashDisbursements', Numeric),
    Column('CashFromOperations', Numeric),
    Column('FixedAssetPurchases', Numeric),
    Column('NetBorrowing', Numeric),
    Column('IncomeTaxPaid', Numeric),
    Column('SaleOfStock', Numeric),
    Column('EndingCashBalance', Numeric)
)

# Define the Yearly Cash Flow Architecture
yearly_cash_flow = Table(
    'yearly_cash_flow', metadata,
    Column('DataSource', String(50)),
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    Column('IsValid', Boolean),
    Column('BeginningCashBalance', Numeric),
    Column('CashReceipts', Numeric),
    Column('CashDisbursements', Numeric),
    Column('CashFromOperations', Numeric),
    Column('FixedAssetPurchases', Numeric),
    Column('NetBorrowing', Numeric),
    Column('IncomeTaxPaid', Numeric),
    Column('SaleOfStock', Numeric),
    Column('EndingCashBalance', Numeric)
)

# Build the tables in the database
metadata.create_all(engine)
print("Cash Flow tables created successfully.")

Cash Flow tables created successfully.

In [12]:

# Define the Yearly Indirect Cash Flow Architecture
yearly_indirect_cash_flow = Table(
    'yearly_indirect_cash_flow', metadata,
    Column('DataSource', String(50)),
    Column('Ticker', String(50), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('Currency', String(10)),
    Column('IsValid', Boolean),
    
    # Operating
    Column('NetIncome', Numeric),
    Column('DepreciationAndAmortization', Numeric),
    Column('OtherNonCashAdjustments', Numeric),
    Column('ChangeInAccountsReceivable', Numeric),
    Column('ChangeInInventory', Numeric),
    Column('ChangeInAccountsPayable', Numeric),
    Column('OtherWorkingCapitalChanges', Numeric),
    Column('IncomeTaxPaid', Numeric),
    Column('TotalOperatingCashFlow', Numeric),
    Column('Unmapped_Operating', Numeric), # TRACKING COLUMN
    
    # Investing
    Column('CapExPurchaseOfPPE', Numeric),
    Column('PurchaseSaleOfInvestments', Numeric),
    Column('OtherInvestingActivities', Numeric),
    Column('TotalInvestingCashFlow', Numeric),
    Column('Unmapped_Investing', Numeric), # TRACKING COLUMN
    
    # Financing
    Column('NetDebtIssuedRepaid', Numeric),
    Column('NetStockIssuedRepurchased', Numeric),
    Column('DividendsPaid', Numeric),
    Column('OtherFinancingActivities', Numeric),
    Column('TotalFinancingCashFlow', Numeric),
    Column('Unmapped_Financing', Numeric), # TRACKING COLUMN
    
    # Rollforward
    Column('EffectOfExchangeRates', Numeric),
    Column('NetChangeInCash', Numeric),
    Column('BeginningCash', Numeric),
    Column('EndingCash', Numeric),
    Column('Unmapped_Rollforward', Numeric) # TRACKING COLUMN
)

# Build the tables in the database
metadata.create_all(engine)
print("Indirect Cash Flow table created successfully.")

Indirect Cash Flow table created successfully.

## Dictionaries

In [13]:
ittelson_income_statement_columns = [
    'TotalRevenue', 
    'CostOfRevenue', 
    'GrossProfit',
    'OperatingExpense',
    'OperatingIncome',
    'NetInterestIncome',
    'TaxProvision',
    'NetIncome'
]

normalized_is_synonym_map = {

    
    'TotalRevenue': [
        'TotalRevenue', 
        'OperatingRevenue', 
        'Sales'
    ],
    
    'CostOfRevenue': [
        'CostOfRevenue', 
        'ReconciledCostOfRevenue', 
        'CostofGoodsAndServicesSold'
        # Notice: MaterialCost and ManufacturingCost are REMOVED from here
    ],
    
    'GrossProfit': [
        'GrossProfit'
    ],
    
    'OperatingExpense': [
        'OperatingExpense', 
        'OperatingExpenses', 
        'SellingGeneralAndAdministration',
        'SellingGeneralAndAdministrative', 
        'OtherOperatingExpenses', 
        'ResearchAndDevelopment', 
        'SellingAndMarketingExpense',
        'GeneralAndAdministrativeExpense', 
        'OtherGandA',
        'TotalExpenses'
        # Notice: EmployeeCost and OtherCost are REMOVED from here
    ],
    
    'OperatingIncome': [
        'OperatingIncome', 
        'TotalOperatingIncomeAsReported', 
        'OperatingProfit', 
        'Ebit' 
    ],
    
    'NetInterestIncome': [
        'NetInterestIncome', 
        'NetNonOperatingInterestIncomeExpense', 
        'Interest',
        'InterestIncome', 
        'InterestExpense', 
        'InterestAndDebtExpense',
        'InterestExpenseNonOperating', 
        'InterestIncomeNonOperating'
    ],
    
    'TaxProvision': [
        'TaxProvision', 
        'IncomeTaxExpense', 
        'Tax' # Derived from Screener's 'Tax %'
    ],
    
    'NetIncome': [
        'NetIncome', 
        'NetProfit', 
        'NetIncomeCommonStockholders',
        'NetIncomeContinuousOperations', 
        'NetIncomeFromContinuingOperations',
        'NetIncomeIncludingNoncontrollingInterests',
        'NetIncomeFromContinuingAndDiscontinuedOperation',
        'NetIncomeFromContinuingOperationNetMinorityInterest',
        'ProfitForEps', 
        'ProfitForPe'
    ],

    
    'PretaxIncome': [
        'PretaxIncome', 
        'ProfitBeforeTax', 
        'IncomeBeforeTax'
    ],
    
    'MaterialCost': [
        'MaterialCost' # Derived from Screener's 'Material Cost %'
    ],
    
    'ManufacturingCost': [
        'ManufacturingCost' # Derived from Screener's 'Manufacturing Cost %'
    ],
    
    'EmployeeCost': [
        'EmployeeCost' # Derived from Screener's 'Employee Cost %'
    ],
    
    'OtherCost': [
        'OtherCost' # Derived from Screener's 'Other Cost %'
    ]
}

In [14]:

#Screener balance sheet items mapping
ittelson_screener_balance_sheet_map = {
    'Cash Equivalents': 'CashCashEquivalentsAndShortTermInvestments',
    'Trade receivables': 'Receivables',
    'Inventories': 'Inventory',
    'Gross Block': 'GrossPPE',
    'Accumulated Depreciation': 'AccumulatedDepreciation',
    'Fixed Assets': 'NetPPE',
    'Total Assets': 'TotalAssets',
    'Trade Payables': 'PayablesAndAccruedExpenses',
    'Short term Borrowings': 'CurrentDebtAndCapitalLeaseObligation',
    'Long term Borrowings': 'LongTermDebtAndCapitalLeaseObligation',
    'Equity Capital': 'CapitalStock',
    'Reserves': 'RetainedEarnings'
}

yfinance_to_ittelson_map = {
    'AccountsReceivable': 'Receivables',
    'AccountsPayable': 'PayablesAndAccruedExpenses',
    'Inventory': 'Inventory',
    'GrossPPE': 'GrossPPE',
    'AccumulatedDepreciation': 'AccumulatedDepreciation',
    'NetPPE': 'NetPPE',
    'TotalAssets': 'TotalAssets',
    'CurrentDebtAndCapitalLeaseObligation': 'CurrentDebtAndCapitalLeaseObligation',
    'LongTermDebtAndCapitalLeaseObligation': 'LongTermDebtAndCapitalLeaseObligation',
    'TotalTaxPayable': 'TotalTaxPayable',
    'CapitalStock': 'CapitalStock',
    'RetainedEarnings': 'RetainedEarnings',
    'StockholdersEquity': 'StockholdersEquity'
}

normalized_bs_synonym_map = {
    # --- ASSETS ---
    'CashCashEquivalentsAndShortTermInvestments': [
        'CashCashEquivalentsAndShortTermInvestments', 
        'CashAndCashEquivalents',
        'CashFinancial'
        # Notice: 'CashEquivalents' and 'Investments' are REMOVED from here (they are ingredients)
    ],
    
    'Receivables': [
        'Receivables', 
        'AccountsReceivable', 
        'TradeReceivables' # 1:1 Screener equivalent
    ],
    
    'Inventory': [
        'Inventory', 
        'Inventories'
    ],
    
    'CurrentAssets': [
        'CurrentAssets'
    ],
    
    'TotalNonCurrentAssets': [
        'TotalNonCurrentAssets'
    ],
    
    'GrossPPE': [
        'GrossPPE',
        'GrossPpe', 
        'GrossBlock' # 1:1 Screener equivalent
    ],
    
    'AccumulatedDepreciation': [
        'AccumulatedDepreciation'
    ],
    
    'NetPpe': [
        'NetPPE',
        'NetPpe' 
        'FixedAssets' # 1:1 Screener equivalent
    ],
    
    'TotalAssets': [
        'TotalAssets'
    ],
    
    # --- LIABILITIES & EQUITY ---
    'PayablesAndAccruedExpenses': [
        'PayablesAndAccruedExpenses', 
        'AccountsPayable', 
        'Payables'
        # Notice: 'TradePayables' and 'AdvanceFromCustomers' are REMOVED from here
    ],
    
    'CurrentDebtAndCapitalLeaseObligation': [
        'CurrentDebtAndCapitalLeaseObligation', 
        'CurrentDebt',
        'CurrentCapitalLeaseObligation'
        # Notice: 'ShortTermBorrowings' is REMOVED from here
    ],
    
    'TotalTaxPayable': [
        'TotalTaxPayable',
        'TaxesPayable'
    ],
    
    'CurrentLiabilities': [
        'CurrentLiabilities'
    ],
    
    'LongTermDebtAndCapitalLeaseObligation': [
        'LongTermDebtAndCapitalLeaseObligation', 
        'LongTermDebt',
        'LongTermCapitalLeaseObligation'
        # Notice: 'LongTermBorrowings' is REMOVED from here
    ],
    
    'TotalLiabilitiesNetMinorityInterest': [
        'TotalLiabilitiesNetMinorityInterest', 
        
    ],
    
    'CapitalStock': [
        'CapitalStock', 
        'CommonStock', 
        'EquityCapital' # 1:1 Screener equivalent
    ],
    
    'RetainedEarnings': [
        'RetainedEarnings', 
        'Reserves' # 1:1 Screener equivalent
    ],
    
    'StockholdersEquity': [
        'TotalEquityGrossMinorityInterest',
        'StockholdersEquity', 
        'CommonStockEquity'
    ],

    
    # Cash Components
    'CashEquivalents': ['CashEquivalents'],
    'ShortTermInvestments': ['ShortTermInvestments', 'OtherShortTermInvestments'],
    'Investments': ['Investments'],
    
    # Current Asset Components
    'LoansNAdvances': ['LoansNAdvances'], 
    'OtherAssetItems': ['OtherAssetItems'],
    
    # Payables Components
    'TradePayables': ['TradePayables'],
    'AdvanceFromCustomers': ['AdvanceFromCustomers'],
    
    # Debt Components
    'ShortTermBorrowings': ['ShortTermBorrowings'],
    'LeaseLiabilities': ['LeaseLiabilities'],
    'LongTermBorrowings': ['LongTermBorrowings'],
    'OtherBorrowings': ['OtherBorrowings'],
    
    # Liability Components
    'OtherLiabilityItems': ['OtherLiabilityItems'],
    'Borrowings': ['Borrowings'],
    'OtherLiabilities': ['OtherLiabilities']
}

ittelson_balance_sheet_columns = [
  #Assets
  'CashCashEquivalentsAndShortTermInvestments',
  'Receivables',
  'Inventory',
  'CurrentAssets',
  'TotalNonCurrentAssets',
  'GrossPPE',
  'AccumulatedDepreciation',
  'NetPPE',
  'TotalAssets',
  #Liabilities&Equity
  'PayablesAndAccruedExpenses',
  'CurrentDebtAndCapitalLeaseObligation',
  'TotalTaxPayable',
  'CurrentLiabilities',
  'LongTermDebtAndCapitalLeaseObligation',
  'TotalLiabilitiesNetMinorityInterest', #Current Liabilities + Long-Term Debt.
  'CapitalStock',
  'RetainedEarnings',
  'StockholdersEquity'
]

In [15]:

ittelson_cash_flow_columns = [
    'BeginningCashBalance',
    'CashReceipts',
    'CashDisbursements',
    'CashFromOperations',
    'FixedAssetPurchases',
    'NetBorrowing',
    'IncomeTaxPaid',
    'SaleOfStock',
    'EndingCashBalance'
]



normalized_cf_synonym_map = {
    
    'BeginningCashBalance': [
        'BeginningCashBalance',
        'BeginningCashPosition'
    ],
    
    'CashReceipts': [],
    
    'CashDisbursements': [],
    
    'CashFromOperations': [
        'CashFromOperations',
        'CashFlowFromContinuingOperatingActivities', # Prioritized to avoid yfinance NaN rows
        'OperatingCashFlow',
        'CashFromOperatingActivity' 
    ],
    
    'FixedAssetPurchases': [
        'FixedAssetPurchases',
        'CapitalExpenditure', # Prioritized for US
        'PurchaseOfPPE',
         'PurchaseOfPpe',
        'FixedAssetsPurchased' 
    ],
    
    'NetBorrowing': [
        'NetBorrowing',
        'NetIssuancePaymentsOfDebt', 
        'NetLongTermDebtIssuance' # Added for US Yearly
    ],
    
    'IncomeTaxPaid': [
        'IncomeTaxPaid',
        'IncomeTaxPaidSupplementalData', # Added for US Yearly
        'TaxesRefundPaid', 
        'DirectTaxes' 
    ],
    
    'SaleOfStock': [
        'SaleOfStock',
        'NetCommonStockIssuance', # Prioritized for US Quarterly
        'IssuanceOfCapitalStock',
        'CommonStockIssuance',
        'ProceedsFromShares' 
    ],
    
    'EndingCashBalance': [
        'EndingCashBalance',
        'EndCashPosition'
    ],

    # Components for calculating missing Net Borrowing
    'RepaymentOfBorrowings': ['RepaymentOfDebt', 'RepaymentOfBorrowings', 'Repayment of borrowings'],   
    'IssuanceOfDebt': ['IssuanceOfDebt', 'ProceedsFromBorrowings', 'Proceeds from borrowings'],                 
    'RepaymentOfDebt': ['RepaymentOfDebt'],             
    
    # Components for tracking missing Cash Balances
    'NetCashFlow': ['NetCashFlow', 'ChangesInCash', 'Net Cash Flow']
}



normalized_indirect_cf_synonym_map = {
    # --- OPERATING ACTIVITIES ---
    'NetIncome': [
        ['NetIncomeFromContinuingOperations', 'ProfitFromOperations', 'NetIncome']
    ],
    'DepreciationAndAmortization': [
        ['DepreciationAmortizationDepletion', 'DepreciationAndAmortization', 'Depreciation', 'AmortizationCashFlow']
    ],
    'OtherNonCashAdjustments': [
        # Distinct components in separate brackets to be summed
        ['StockBasedCompensation'], 
        ['DeferredTax', 'DeferredIncomeTax'], 
        ['AssetImpairmentCharge'], 
        ['UnrealizedGainLossOnInvestmentSecurities'], 
        ['GainLossOnInvestmentSecurities', 'OperatingGainsLosses'], 
        ['OtherOperatingItems'],
        ['ProvisionandWriteOffofAssets'],
        ['OtherNonCashItems'],
        ['PensionAndEmployeeBenefitExpense'],
        ['NetForeignCurrencyExchangeGainLoss'],
        ['GainLossOnSaleOfPPE','GainLossOnSaleOfPpe'],
        ['GainLossOnSaleOfBusiness'], # <-- Added to fix the 1.2B gap in 2022
    ],
    'ChangeInAccountsReceivable': [
        ['ChangeInReceivables', 'ChangesInAccountReceivables', 'Receivables']
    ],
    'ChangeInInventory': [
        ['ChangeInInventory', 'Inventory']
    ],
    'ChangeInAccountsPayable': [
        ['ChangeInAccountPayable', 'ChangeInPayable', 'ChangeInPayablesAndAccruedExpense', 'Payables']
    ],
'OtherWorkingCapitalChanges': [
        ['ChangeInOtherCurrentAssets'], 
        ['ChangeInOtherCurrentLiabilities'], 
        ['ChangeInOtherWorkingCapital', 'OtherWcItems'], # Removed 'WorkingCapitalChanges'
        ['LoansAdvances'] 
    ],
    'IncomeTaxPaid': [
        ['TaxesRefundPaid', 'IncomeTaxPaid', 'IncomeTaxPaidSupplementalData', 'DirectTaxes']
    ],
    'TotalOperatingCashFlow': [
        ['OperatingCashFlow', 'CashFlowFromContinuingOperatingActivities', 'CashFromOperatingActivity']
    ],

    # --- INVESTING ACTIVITIES ---
  # --- INVESTING ACTIVITIES ---
    "CapExPurchaseOfPPE": [
        ["CapitalExpenditure", "PurchaseOfPpe", "FixedAssetsPurchased", "NetPPEPurchaseAndSale", "NetPpePurchaseAndSale"],
        ["SaleOfPPE", "SaleOfPpe", "FixedAssetsSold"]
    ],
    "PurchaseSaleOfInvestments": [
        ["PurchaseOfInvestment", "InvestmentsPurchased", "NetInvestmentPurchaseAndSale"], 
        ["SaleOfInvestment", "InvestmentsSold"],          
        ["PurchaseOfBusiness", "AcquisitionOfCompanies", "NetBusinessPurchaseAndSale"],
        ["SaleOfBusiness"],
        ["PurchaseOfIntangibles", "NetIntangiblesPurchaseAndSale"],
        ["SaleOfIntangibles"],
        ["ProceedsFromMaturitiesOfInvestments"],
        ["RedempNCancOfShares"]
    ],
    "OtherInvestingActivities": [
        ["NetOtherInvestingChanges", "OtherInvestingItems"], 
        ["InterestReceived", "InterestReceivedCFI", "InterestReceivedCfi"],
        ["DividendsReceived","DividendsReceivedCfi"],
        ["InterCorporateDeposits"] 
    ],
    "TotalInvestingCashFlow": [
        ["InvestingCashFlow", "CashFlowFromContinuingInvestingActivities", "CashFromInvestingActivity"]
    ],

    # --- FINANCING ACTIVITIES ---
    "NetDebtIssuedRepaid": [
        ["IssuanceOfDebt", "LongTermDebtIssuance", "ProceedsFromBorrowings", "NetShortTermDebtIssuance", "ShortTermDebtIssuance"],
        ["ProceedsFromDeposits"], 
        ["RepaymentOfDebt", "LongTermDebtPayments", "RepaymentOfBorrowings", "ShortTermDebtPayments"]
    ],
    "NetStockIssuedRepurchased": [
        ["IssuanceOfCapitalStock", "CommonStockIssuance", "ProceedsFromShares", "NetCommonStockIssuance"], 
        ["RepurchaseOfCapitalStock", "CommonStockPayments"],
        ["TaxesPaidRelatedToNetShareSettlementOfEquityAwards"]
    ],
    "DividendsPaid": [
        ["CashDividendsPaid", "CommonStockDividendPaid", "DividendsPaid"]
    ],
    "OtherFinancingActivities": [
        ["NetOtherFinancingCharges", "OtherFinancingItems"],
        ["InterestPaidFin", "InterestPaidCFF", "InterestPaidCff"], 
        ["FinancialLiabilities"]
    ],
    "TotalFinancingCashFlow": [
        ["FinancingCashFlow", "CashFlowFromContinuingFinancingActivities", "CashFromFinancingActivity"]
    ],
    # --- CASH SUMMARIES ---
    'EffectOfExchangeRates': [
        ['EffectOfExchangeRateChanges']
    ],
    'NetChangeInCash': [
        ['ChangesInCash', 'NetCashFlow']
    ],
    'BeginningCash': [
        ['BeginningCashPosition']
    ],
    'EndingCash': [
        ['EndCashPosition']
    ]
}

# The target column list for your formatter and database tables
ittelson_indirect_cf_columns = list(normalized_indirect_cf_synonym_map.keys())

In [16]:
indirect_cf_buckets = [
    'OtherNonCashAdjustments', 
    'OtherWorkingCapitalChanges',
    'NetDebtIssuedRepaid',
    'NetStockIssuedRepurchased',
    'PurchaseSaleOfInvestments',
    'OtherInvestingActivities', 
    'OtherFinancingActivities'
]

## API/UPSERT CALL FUNTION

In [17]:
def fetch_all_financials(ticker):
    """
    Attempts to fetch a complete set of financials (IS, BS, CF) from a single source.
    Enforces a strict "all-or-nothing" rule to prevent mixed-source validation errors.
    """
    print(f"\n" + "="*40)
    print(f"[{ticker}] INITIATING DATA FETCH")
    print("="*40)
    
    # ATTEMPT 1: YFINANCE (The Preferred Source)
    print(f"[{ticker}] Attempting YFinance...")
    try:
        yf_is_q = get_yfinance(ticker, "INCOME_STATEMENT", "quarterly")
        yf_is_y = get_yfinance(ticker, "INCOME_STATEMENT", "yearly")
        yf_bs_q = get_yfinance(ticker, "BALANCE_SHEET", "quarterly")
        yf_bs_y = get_yfinance(ticker, "BALANCE_SHEET", "yearly")
        yf_cf_y = get_yfinance(ticker, "CASH_FLOW", "yearly")
        
        # Note: YFinance often lacks Quarterly CF, so we only strictly require Yearly CF to pass
        if all(v is not None and not v.empty for v in [yf_is_q, yf_is_y, yf_bs_q, yf_bs_y, yf_cf_y]):
            print(f"[{ticker}] SUCCESS: Complete YFinance dataset acquired.")
            return {
                "source": "yfinance",
                "data": {
                    "is_q": yf_is_q, "is_y": yf_is_y,
                    "bs_q": yf_bs_q, "bs_y": yf_bs_y,
                    "cf_y": yf_cf_y,
                    # Safely grab Q CF if it exists, otherwise pass None
                    "cf_q": get_yfinance(ticker, "CASH_FLOW", "quarterly") 
                }
            }
    except Exception as e:
        print(f"[{ticker}] YFinance fetch encountered an error: {e}")

   
    # ATTEMPT 2: ALPHA VANTAGE
    
    print(f"[{ticker}] YFinance incomplete. Attempting Alpha Vantage...")
    try:
        av_is = get_alpha_vantage(ticker, 'INCOME_STATEMENT', API_KEY)
        av_bs = get_alpha_vantage(ticker, 'BALANCE_SHEET', API_KEY)
        av_cf = get_alpha_vantage(ticker, 'CASH_FLOW', API_KEY)
        
        if av_is and av_bs and av_cf and "annualReports" in av_is:
            print(f"[{ticker}] SUCCESS: Complete Alpha Vantage dataset acquired.")
            return {
                "source": "vantage",
                "data": {
                    "is": av_is, "bs": av_bs, "cf": av_cf
                }
            }
    except Exception as e:
        print(f"[{ticker}] Alpha Vantage fetch encountered an error: {e}")

   
    # ATTEMPT 3: SCREENER.IN
  
    print(f"[{ticker}] Alpha Vantage incomplete. Attempting Screener.in...")
    try:
        sc_is_q = get_screener_financials(ticker, report_type='quarterly')
        sc_is_y = get_screener_financials(ticker, report_type='yearly')
        sc_bs_y = get_screener_financials(ticker, report_type='balance-sheet')
        sc_cf_y = get_screener_financials(ticker, report_type='cash-flow')
        
        if sc_is_y and sc_bs_y and sc_cf_y:
            print(f"[{ticker}] SUCCESS: Complete Screener dataset acquired.")
            return {
                "source": "screener",
                "data": {
                    "is_q": sc_is_q, "is_y": sc_is_y,
                    "bs_y": sc_bs_y, "cf_y": sc_cf_y
                }
            }
    except Exception as e:
        print(f"[{ticker}] Screener fetch encountered an error: {e}")
        
    print(f"[{ticker}] CRITICAL FAILURE: Could not acquire complete data from any source.")
    return None

In [18]:
# Define the Custom Upsert Logic
def postgres_upsert(table, conn, keys, data_iter):
    """
    Native PostgreSQL UPSERT
    """
    # Convert Pandas data into a list of dictionaries
    data = [dict(zip(keys, row)) for row in data_iter]
    
    insert_stmt = insert(table.table).values(data)

    # Automatically create the "UPDATE" part of the query for all columns 
    # EXCEPT the primary keys (Ticker and ReportDate)
    update_dict = {
        c.name: getattr(insert_stmt.excluded, c.name)
        for c in table.table.columns
        if c.name not in ("Ticker", "ReportDate")
    }
    
    upsert_stmt = insert_stmt.on_conflict_do_update(
        index_elements=['Ticker', 'ReportDate'], 
        set_=update_dict
    )
    
    conn.execute(upsert_stmt)

## CLEAN DATA FUNCTIONS

In [19]:

def clean_financial_dataframe(df):
   
    return df.replace(r'[%,+]', '', regex=True).apply(pd.to_numeric, errors='coerce')


def format_statement_for_db(df, target_columns, ticker, currency,data_source, multiplier=1.0,index_col_name='index', transpose=False):

    if transpose:
        df = df.T
    
    # Filter to only the columns needed for the database 
    clean_df = df.loc[:, target_columns]
    
    #normalize values decimals
    clean_df = (clean_df * multiplier).round(4)
    
    
    # Reset index to bring the dates into a standard column
    clean_df = clean_df.reset_index()
    
    # Rename the date column (handles Alpha Vantage vs Yfinance/Screener differences)
    clean_df = clean_df.rename(columns={index_col_name: 'ReportDate'})
    
    # Standardize end-of-month date format
    clean_df["ReportDate"] = (pd.to_datetime(clean_df["ReportDate"]) + pd.offsets.MonthEnd(0)).dt.strftime('%Y-%m-%d')
    
    # Insert Ticker at the beginning
    clean_df.insert(1, 'Ticker', ticker)
    clean_df.insert(2, 'Currency', currency)
    clean_df.insert(3, 'DataSource', data_source)
    
    return clean_df


def to_pascal_case(text):

    if not isinstance(text, str):
        return text
    
    # Insert spaces before capital letters (e.g., "CostOfRevenue" -> "Cost Of Revenue")
    spaced_text = re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', text)
    
    # Replace anything that is NOT a letter with a space
    clean_text = re.sub(r'[^a-zA-Z]', ' ', spaced_text)
    
    #Split into individual words, capitalize the first letter, and glue together
    pascal_str = "".join(word.capitalize() for word in clean_text.split())
    
    return pascal_str


def standardize_dataframe_labels(df):

    df.index = [to_pascal_case(str(idx)) for idx in df.index]
    return df

#% to values for screener


def convert_screener_percentages_to_absolute(df_screener_is):
    
    if df_screener_is.attrs.get('screener_converted_to_absolute'):
        return df_screener_is

    # 1. Cost Items (Base = Sales)
    if 'Sales' in df_screener_is.index:
        sales = df_screener_is.loc['Sales'].fillna(0)
        
        if 'MaterialCost' in df_screener_is.index:
            df_screener_is.loc['MaterialCost'] = sales * (df_screener_is.loc['MaterialCost'].fillna(0) / 100)
            
        if 'ManufacturingCost' in df_screener_is.index:
            df_screener_is.loc['ManufacturingCost'] = sales * (df_screener_is.loc['ManufacturingCost'].fillna(0) / 100)
            
        if 'EmployeeCost' in df_screener_is.index:
            df_screener_is.loc['EmployeeCost'] = sales * (df_screener_is.loc['EmployeeCost'].fillna(0) / 100)
            
        if 'OtherCost' in df_screener_is.index:
            df_screener_is.loc['OtherCost'] = sales * (df_screener_is.loc['OtherCost'].fillna(0) / 100)

    # 2. Tax Item (Base = Profit before tax)
    if 'ProfitBeforeTax' in df_screener_is.index and 'Tax' in df_screener_is.index:
        pbt = df_screener_is.loc['ProfitBeforeTax'].fillna(0)
        df_screener_is.loc['Tax'] = pbt * (df_screener_is.loc['Tax'].fillna(0) / 100)
        
    df_screener_is.attrs['screener_converted_to_absolute'] = True
        
    return df_screener_is

# CHECK ITEMS UNIFORM
def safe_fetch(df, target_item, synonym_map, bucket_mode=False):
    
    # Get the raw mapping from the dictionary
    raw_mapping = synonym_map.get(target_item, [target_item])
    
    if raw_mapping and isinstance(raw_mapping[0], str):
        search_groups = [raw_mapping]
    else:
        # It is already a list of lists (New CF dict)
        search_groups = raw_mapping
    
    if bucket_mode:
        # BUCKET: Sum exactly ONE item from each sub-list
        matched_values = []
        for group in search_groups:
            # Loop through aliases in the current group
            for label in group:
                if label in df.index:
                    result = df.loc[label]
                    val = result.iloc[0] if isinstance(result, pd.DataFrame) else result
                    matched_values.append(val.fillna(0))
                    break # CRITICAL: Stop looking in this group to prevent double-counting!
                    
        if matched_values:
            return sum(matched_values)
            
        return pd.Series(np.nan, index=df.columns)
        
    else:
        # SYNONYM: Stop entirely after finding the very first match anywhere
        for group in search_groups:
            for label in group:
                if label in df.index:
                    result = df.loc[label]
                    return result.iloc[0] if isinstance(result, pd.DataFrame) else result
                    
        return pd.Series(np.nan, index=df.columns)

def map_statement_via_dictionary(df, synonym_map, target_columns, bucket_columns=None):
    if bucket_columns is None:
        bucket_columns = []
        
    mapped_data = {}
    
    # Run the scanner for every column you need
    for target_col in target_columns:
        # Pass bucket_mode=True only if the column is explicitly flagged as a bucket
        mode = True if target_col in bucket_columns else False
        mapped_data[target_col] = safe_fetch(df, target_col, synonym_map, bucket_mode=mode)
        
    return pd.DataFrame(mapped_data).T

## FALLBACK FUNCTIONS

In [20]:

# FALLBACK

def apply_income_statement_fallbacks(df, target_columns):

    # CostOfRevenue Fallback: Pure addition of absolute values (No Revenue Multiplier)
    if df.loc['CostOfRevenue'].isna().any():
        if 'MaterialCost' in df.index and 'ManufacturingCost' in df.index:
            calc_cost = df.loc['MaterialCost'].fillna(0) + df.loc['ManufacturingCost'].fillna(0)
            has_screener_cogs = ~(df.loc['MaterialCost'].isna() & df.loc['ManufacturingCost'].isna())
            df.loc['CostOfRevenue'] = df.loc['CostOfRevenue'].fillna(calc_cost.where(has_screener_cogs))
            
        elif 'GrossProfit' in df.index:
            calc_cost_gaap = df.loc['TotalRevenue'] - df.loc['GrossProfit']
            df.loc['CostOfRevenue'] = df.loc['CostOfRevenue'].fillna(calc_cost_gaap)

    # GrossProfit Fallback: TotalRevenue - CostOfRevenue
    if df.loc['GrossProfit'].isna().any():
        calc_gp = df.loc['TotalRevenue'] - df.loc['CostOfRevenue'].fillna(0)
        df.loc['GrossProfit'] = df.loc['GrossProfit'].fillna(calc_gp)

    # OperatingExpense Fallback: Anchor Row minus Calculated COGS (No Revenue Multiplier)
    if df.loc['OperatingExpense'].isna().any():
        if 'TotalScreenerExpenses' in df.index:
            calc_opex = df.loc['TotalScreenerExpenses'] - df.loc['CostOfRevenue'].fillna(0)
            df.loc['OperatingExpense'] = df.loc['OperatingExpense'].fillna(calc_opex)
            
        elif 'OperatingIncome' in df.index:
            calc_opex_gaap = df.loc['GrossProfit'].fillna(0) - df.loc['OperatingIncome']
            df.loc['OperatingExpense'] = df.loc['OperatingExpense'].fillna(calc_opex_gaap)

    # OperatingIncome Fallback (Ensure calculation exists if API skips it)
    if df.loc['OperatingIncome'].isna().any():
        calc_op_inc = df.loc['GrossProfit'].fillna(0) - df.loc['OperatingExpense'].fillna(0)
        df.loc['OperatingIncome'] = df.loc['OperatingIncome'].fillna(calc_op_inc)

    # NetInterestIncome Fallback: PretaxIncome - OperatingIncome
    if df.loc['NetInterestIncome'].isna().any():
        calc_interest = df.loc['PretaxIncome'] - df.loc['OperatingIncome']
        df.loc['NetInterestIncome'] = df.loc['NetInterestIncome'].fillna(calc_interest)

    # TaxProvision Fallback: PretaxIncome - NetIncome
    if df.loc['TaxProvision'].isna().any():
        calc_tax = df.loc['PretaxIncome'] - df.loc['NetIncome']
        df.loc['TaxProvision'] = df.loc['TaxProvision'].fillna(calc_tax)

    # Isolate the strict Ittelson columns and safely convert any remaining NaNs to 0
    final_df = df.loc[target_columns].fillna(0)
    
    return final_df

In [21]:
def apply_balance_sheet_fallbacks(df, target_columns):

    #ASSETS
    
    # Cash & Equivalents Fallback
    if df.loc['CashCashEquivalentsAndShortTermInvestments'].isna().any():
        
        calc_cash = df.loc['CashEquivalents'].fillna(0)
        #using .get shows attribute error
        if 'ShortTermInvestments' in df.index:
            calc_cash += df.loc['ShortTermInvestments'].fillna(0)
            
        df.loc['CashCashEquivalentsAndShortTermInvestments'] = df.loc['CashCashEquivalentsAndShortTermInvestments'].fillna(calc_cash)

    # Current Assets Fallback
    if df.loc['CurrentAssets'].isna().any():
        calc_ca = (df.loc['Inventory'].fillna(0) + 
                   df.loc['Receivables'].fillna(0) + 
                   df.loc['CashEquivalents'].fillna(0) + 
                   df.loc['LoansNAdvances'].fillna(0) + 
                   df.loc['OtherAssetItems'].fillna(0))
        df.loc['CurrentAssets'] = df.loc['CurrentAssets'].fillna(calc_ca)
    
    #Inventory
    if df.loc['Inventory'].isna().any():
        calc_inv = df.loc['CurrentAssets'] - (df.loc['CashCashEquivalentsAndShortTermInvestments'].fillna(0) + 
                                              df.loc['Receivables'].fillna(0) + 
                                              df.loc['LoansNAdvances'].fillna(0) + 
                                              df.loc['OtherAssetItems'].fillna(0))
        df.loc['Inventory'] = df.loc['Inventory'].fillna(calc_inv)
    
    # Total Non-Current Assets Fallback
    if df.loc['TotalNonCurrentAssets'].isna().any():
        calc_nca = df.loc['TotalAssets'] - df.loc['CurrentAssets']
        df.loc['TotalNonCurrentAssets'] = df.loc['TotalNonCurrentAssets'].fillna(calc_nca)

    # PPE Math
    if df.loc['NetPPE'].isna().any():
        df.loc['NetPPE'] = df.loc['NetPPE'].fillna(df.loc['GrossPPE'] - df.loc['AccumulatedDepreciation'].fillna(0))
        
    if df.loc['GrossPPE'].isna().any():
        df.loc['GrossPPE'] = df.loc['GrossPPE'].fillna(df.loc['NetPPE'] + df.loc['AccumulatedDepreciation'].fillna(0))


    # LIABILITIES
    # Payables & Accrued Expenses Fallback
    if df.loc['PayablesAndAccruedExpenses'].isna().any():
        calc_payables = df.loc['TradePayables'].fillna(0) + df.loc['AdvanceFromCustomers'].fillna(0)
        df.loc['PayablesAndAccruedExpenses'] = df.loc['PayablesAndAccruedExpenses'].fillna(calc_payables)

    # Current Debt Fallback
    if df.loc['CurrentDebtAndCapitalLeaseObligation'].isna().any():
        calc_cdebt = df.loc['ShortTermBorrowings'].fillna(0) + df.loc['LeaseLiabilities'].fillna(0)
        df.loc['CurrentDebtAndCapitalLeaseObligation'] = df.loc['CurrentDebtAndCapitalLeaseObligation'].fillna(calc_cdebt)

    # Current Liabilities Fallback
    if df.loc['CurrentLiabilities'].isna().any():
        calc_cl = (df.loc['PayablesAndAccruedExpenses'].fillna(0) + 
                   df.loc['CurrentDebtAndCapitalLeaseObligation'].fillna(0) + 
                   df.loc['OtherLiabilityItems'].fillna(0))
        df.loc['CurrentLiabilities'] = df.loc['CurrentLiabilities'].fillna(calc_cl)

    # Long-Term Debt Fallback
    if df.loc['LongTermDebtAndCapitalLeaseObligation'].isna().any():
        calc_ltdebt = df.loc['LongTermBorrowings'].fillna(0) + df.loc['OtherBorrowings'].fillna(0)
        df.loc['LongTermDebtAndCapitalLeaseObligation'] = df.loc['LongTermDebtAndCapitalLeaseObligation'].fillna(calc_ltdebt)

    # Total Liabilities Fallback
    if df.loc['TotalLiabilitiesNetMinorityInterest'].isna().any():
        calc_tl = df.loc['Borrowings'].fillna(0) + df.loc['OtherLiabilities'].fillna(0)
        df.loc['TotalLiabilitiesNetMinorityInterest'] = df.loc['TotalLiabilitiesNetMinorityInterest'].fillna(calc_tl)

    # --- EQUITY ---
    # Stockholders Equity Fallback
    if df.loc['StockholdersEquity'].isna().any():
        calc_equity = df.loc['CapitalStock'].fillna(0) + df.loc['RetainedEarnings'].fillna(0)
        df.loc['StockholdersEquity'] = df.loc['StockholdersEquity'].fillna(calc_equity)

    final_df = df.loc[target_columns].fillna(0)
    
    return final_df

In [22]:

def apply_cash_flow_fallbacks(df, target_columns, df_is_calc=None, df_bs_calc=None):

    #  NET BORROWING 
    if df.loc['NetBorrowing'].isna().any():
        if 'IssuanceOfDebt' in df.index and 'RepaymentOfDebt' in df.index:
            calc_borrowing = df.loc['IssuanceOfDebt'].fillna(0) - df.loc['RepaymentOfDebt'].fillna(0)
            
            # Ensure we only fill where we actually had data (don't inject 0s if both were NaN)
            has_debt_data = ~(df.loc['IssuanceOfDebt'].isna() & df.loc['RepaymentOfDebt'].isna())
            df.loc['NetBorrowing'] = df.loc['NetBorrowing'].fillna(calc_borrowing.where(has_debt_data))

    #  NET BORROWING (Balance Sheet Bridge for missing Q data) 
    if df.loc['NetBorrowing'].isna().any() and df_bs_calc is not None:
        if 'LongTermDebtAndCapitalLeaseObligation' in df_bs_calc.index and 'CurrentDebtAndCapitalLeaseObligation' in df_bs_calc.index:
            common_cols = df.columns.intersection(df_bs_calc.columns)
            
            total_debt = df_bs_calc.loc['LongTermDebtAndCapitalLeaseObligation', common_cols].fillna(0) + \
                         df_bs_calc.loc['CurrentDebtAndCapitalLeaseObligation', common_cols].fillna(0)
            
            # Temporarily sort chronologically to calculate the difference
            temp_s = total_debt.copy()
            original_idx = temp_s.index
            temp_s.index = pd.to_datetime(temp_s.index)
            diff_s = temp_s.sort_index().diff()
            
            mapping = {pd.to_datetime(idx): idx for idx in original_idx}
            diff_s.index = diff_s.index.map(mapping)
            calc_bridge = diff_s[original_idx]
            
            df.loc['NetBorrowing', common_cols] = df.loc['NetBorrowing', common_cols].fillna(calc_bridge)

    #  ENDING CASH (From Balance Sheet)
    # We always bridge this directly from the BS as the absolute source of truth
    if df.loc['EndingCashBalance'].isna().any() and df_bs_calc is not None:
        if 'CashCashEquivalentsAndShortTermInvestments' in df_bs_calc.index:
            common_cols = df.columns.intersection(df_bs_calc.columns)
            df.loc['EndingCashBalance', common_cols] = df.loc['EndingCashBalance', common_cols].fillna(
                df_bs_calc.loc['CashCashEquivalentsAndShortTermInvestments', common_cols]
            )

    #  BEGINNING CASH (Internal CF Math) 
    # Strictly calculated using the bridged Ending Cash and the internal NetCashFlow
    if df.loc['BeginningCashBalance'].isna().any():
        if 'NetCashFlow' in df.index:
            calc_beg = df.loc['EndingCashBalance'].fillna(0) - df.loc['NetCashFlow'].fillna(0)
            has_beg_data = ~(df.loc['EndingCashBalance'].isna() & df.loc['NetCashFlow'].isna())
            df.loc['BeginningCashBalance'] = df.loc['BeginningCashBalance'].fillna(calc_beg.where(has_beg_data))

    #  DIRECT METHOD CONVERSIONS
    # Cash Receipts (Income Statement Bridge)
    if df.loc['CashReceipts'].isna().any() and df_is_calc is not None:
        if 'TotalRevenue' in df_is_calc.index:
            common_cols = df.columns.intersection(df_is_calc.columns)
            df.loc['CashReceipts', common_cols] = df.loc['CashReceipts', common_cols].fillna(
                df_is_calc.loc['TotalRevenue', common_cols]
            )
            
    # Cash Disbursements (Internal CF Math)
    if df.loc['CashDisbursements'].isna().any():
        calc_disbursements = df.loc['CashReceipts'].fillna(0) - df.loc['CashFromOperations'].fillna(0)
        has_disb_data = ~(df.loc['CashReceipts'].isna() & df.loc['CashFromOperations'].isna())
        df.loc['CashDisbursements'] = df.loc['CashDisbursements'].fillna(calc_disbursements.where(has_disb_data))

    #  FINAL CLEANUP
    final_df = df.loc[target_columns].fillna(0)
    
    return final_df



def apply_indirect_cash_flow_fallbacks(df, target_columns, df_is_calc=None, df_bs_calc=None):

    #  Standardize all indices to String YYYY-MM-DD to prevent Timestamp KeyErrors
    df.columns = [pd.to_datetime(c).strftime('%Y-%m-%d') for c in df.columns]
    
    if df_bs_calc is not None:
        df_bs_calc.columns = [pd.to_datetime(c).strftime('%Y-%m-%d') for c in df_bs_calc.columns]
        
        #  Identify dates present in BOTH statements
        common_cols = df.columns.intersection(df_bs_calc.columns)
        
        # Prepare sorted BS for the dates we actually have in CF
        bs_subset = df_bs_calc[common_cols].copy()
        bs_subset.columns = pd.to_datetime(bs_subset.columns)
        bs_sorted = bs_subset.sort_index(axis=1)

        #  DEPRECIATION 
        if 'DepreciationAndAmortization' in df.index:
            if 'AccumulatedDepreciation' in bs_sorted.index:
                # .diff() results in NaN for the first year; we fill with 0 to avoid KeyError
                dep_diff = bs_sorted.loc['AccumulatedDepreciation'].diff().abs().fillna(0)
                dep_diff.index = [c.strftime('%Y-%m-%d') for c in dep_diff.index]
                df.loc['DepreciationAndAmortization', common_cols] = \
                    df.loc['DepreciationAndAmortization', common_cols].fillna(dep_diff)

        #  WORKING CAPITAL (Prior - Current)

        # ONLY use BS differences if the actual CF values are 0 or NaN
        
        if "ChangeInAccountsReceivable" in df.index and "Receivables" in bs_sorted.index:
            ar_diff = -bs_sorted.loc["Receivables"].diff().fillna(0)
            ar_diff.index = [c.strftime("%Y-%m-%d") for c in ar_diff.index]
            # Replace NaNs or absolute 0s with the BS diff
            df.loc["ChangeInAccountsReceivable", common_cols] = df.loc["ChangeInAccountsReceivable", common_cols].replace(0, np.nan).fillna(ar_diff).fillna(0)

        if "ChangeInInventory" in df.index and "Inventory" in bs_sorted.index:
            inv_diff = -bs_sorted.loc["Inventory"].diff().fillna(0)
            inv_diff.index = [c.strftime("%Y-%m-%d") for c in inv_diff.index]
            df.loc["ChangeInInventory", common_cols] = df.loc["ChangeInInventory", common_cols].replace(0, np.nan).fillna(inv_diff).fillna(0)

        if "ChangeInAccountsPayable" in df.index and "PayablesAndAccruedExpenses" in bs_sorted.index:
            ap_diff = bs_sorted.loc["PayablesAndAccruedExpenses"].diff().fillna(0)
            ap_diff.index = [c.strftime("%Y-%m-%d") for c in ap_diff.index]
            df.loc["ChangeInAccountsPayable", common_cols] = df.loc["ChangeInAccountsPayable", common_cols].replace(0, np.nan).fillna(ap_diff).fillna(0)

        # CASH ANCHORS
        if 'EndingCash' in df.index and 'CashCashEquivalentsAndShortTermInvestments' in bs_sorted.index:
            cash_vals = bs_sorted.loc['CashCashEquivalentsAndShortTermInvestments']
            cash_vals.index = [c.strftime('%Y-%m-%d') for c in cash_vals.index]
            df.loc['EndingCash', common_cols] = df.loc['EndingCash', common_cols].fillna(cash_vals)
        
        if 'BeginningCash' in df.index and 'CashCashEquivalentsAndShortTermInvestments' in bs_sorted.index:
            # Shift allows us to get the previous year's ending cash
            beg_cash = bs_sorted.loc['CashCashEquivalentsAndShortTermInvestments'].shift(1).fillna(0)
            beg_cash.index = [c.strftime('%Y-%m-%d') for c in beg_cash.index]
            df.loc['BeginningCash', common_cols] = df.loc['BeginningCash', common_cols].fillna(beg_cash)

    #  Income Statement Bridge
    if df_is_calc is not None and 'NetIncome' in df.index:
        df_is_calc.columns = [pd.to_datetime(c).strftime('%Y-%m-%d') for c in df_is_calc.columns]
        is_cols = df.columns.intersection(df_is_calc.columns)
        if 'NetIncome' in df_is_calc.index:
            df.loc['NetIncome', is_cols] = df.loc['NetIncome', is_cols].fillna(df_is_calc.loc['NetIncome', is_cols])

    #Final Totals
    op_items = ['NetIncome', 'DepreciationAndAmortization', 'OtherNonCashAdjustments', 
                'ChangeInAccountsReceivable', 'ChangeInInventory', 
                'ChangeInAccountsPayable', 'OtherWorkingCapitalChanges']
    valid_op = [i for i in op_items if i in df.index]
    df.loc['TotalOperatingCashFlow'] = df.loc['TotalOperatingCashFlow'].fillna(df.loc[valid_op].sum())

    return df.loc[target_columns].fillna(0)

# 3-STATEMENT VALIDATION

In [23]:
def validate_financial_statements(df_is, df_bs, df_cf, df_indirect_cf=None):

    print("RUNNING 3-STATEMENT VALIDATION")


# Set indices for alignment
    df_is = df_is.set_index('ReportDate')
    df_bs = df_bs.set_index('ReportDate')
    df_cf = df_cf.set_index('ReportDate')
    
    if df_indirect_cf is not None:
        df_indirect_cf = df_indirect_cf.set_index('ReportDate')

    print("\n--- DIRECT STATEMENTS AUDIT ---")

    # 1. BALANCE SHEET
    bs_calc = df_bs['TotalLiabilitiesNetMinorityInterest'] + df_bs['StockholdersEquity']
    bs_gap = df_bs['TotalAssets'] - bs_calc
    bs_check = bs_gap.abs() <= 10
    
    if bs_check.all():
        print("Balance Sheet Equation (Assets = L + E): PERFECT MATCH")
    else:
        print("(!) BALANCE SHEET LEAK DETECTED:")
        for date, is_valid in bs_check.items():
            if not is_valid:
                print(f"   -> [{date}] Assets: {df_bs.at[date, 'TotalAssets']:.2f} | Calculated L+E: {bs_calc[date]:.2f} | Gap: {bs_gap[date]:.2f}")

    # 2. INCOME STATEMENT
    is_calc = df_is['GrossProfit'] - df_is['OperatingExpense']
    is_gap = df_is['OperatingIncome'] - is_calc
    is_check = is_gap.abs() < 1
    
    if is_check.all():
        print("Income Statement Equation (GP - Opex = OpInc): PERFECT MATCH")
    else:
        print("(!) INCOME STATEMENT LEAK DETECTED:")
        for date, is_valid in is_check.items():
            if not is_valid:
                print(f"   -> [{date}] OpInc: {df_is.at[date, 'OperatingIncome']:.2f} | Calculated (GP-Opex): {is_calc[date]:.2f} | Gap: {is_gap[date]:.2f}")

    # 3. BALANCE SHEET TO CASH FLOW LINK
    common_bs_cf = df_cf.index.intersection(df_bs.index)
    bs_aggregate = df_bs.loc[common_bs_cf, 'CashCashEquivalentsAndShortTermInvestments']
    cf_cash = df_cf.loc[common_bs_cf, 'EndingCashBalance']
    
    bs_cf_gap = cf_cash - bs_aggregate
    bs_cf_check = (bs_cf_gap.abs() < 1) | (cf_cash <= bs_aggregate + 1)
    
    if bs_cf_check.all():
        print("BS/CF Cash Link (Ending Cash): PERFECT MATCH")
    else:
        print("(!) BS/CF LINK LEAK DETECTED:")
        for date, is_valid in bs_cf_check.items():
            if not is_valid:
                print(f"   -> [{date}] CF Ending Cash: {cf_cash[date]:.2f} | BS Cash: {bs_aggregate[date]:.2f} | Gap: {bs_cf_gap[date]:.2f}")

    # 4. DIRECT CASH FLOW (Receipts - Disbursements)
    cf_calc = df_cf['CashReceipts'] - df_cf['CashDisbursements']
    cf_gap = df_cf['CashFromOperations'] - cf_calc
    cf_check = cf_gap.abs() < 1
    
    if cf_check.all():
        print("Direct Cash Flow Equation: PERFECT MATCH")
    else:
        print("(!) DIRECT CASH FLOW LEAK DETECTED:")
        for date, is_valid in cf_check.items():
            if not is_valid:
                print(f"   -> [{date}] CFO: {df_cf.at[date, 'CashFromOperations']:.2f} | Calc (Rec-Disb): {cf_calc[date]:.2f} | Gap: {cf_gap[date]:.2f}")

    # Initialize Audit Dict (Now with overall IsValid flags for the tables)
    audit_dict = {
        'BS_IsValid': bs_check,
        'IS_IsValid': is_check,
        'BS_CF_Link_Match': bs_cf_check,
        'Direct_CF_Match': cf_check
    }

    # INDIRECT CASH FLOW VALIDATION 
    if df_indirect_cf is not None:
        print("\nINDIRECT CASH FLOW AUDIT")
        
        common_is_cf = df_indirect_cf.index.intersection(df_is.index)
        
        cf_ni_anchor = df_indirect_cf.loc[common_is_cf, 'NetIncome']
        is_ni = df_is.loc[common_is_cf, 'NetIncome']
        
        # ANCHOR CHECK 
        indirect_ni_check = (cf_ni_anchor - is_ni).abs() < 1
        
        if not indirect_ni_check.all():
            print("(!) Strict NI match failed. Cascading through PBT, EBIT, and EBITDA anchors...")
            
            tax_val = df_is.loc[common_is_cf].get('TaxProvision', pd.Series(0, index=common_is_cf)).fillna(0)
            calc_pretax = is_ni + tax_val
            pbt_gap = (cf_ni_anchor - calc_pretax).abs()
            
            interest_val = df_is.loc[common_is_cf].get('NetInterestIncome', pd.Series(0, index=common_is_cf)).abs().fillna(0)
            calc_ebit = calc_pretax + interest_val
            ebit_gap = (cf_ni_anchor - calc_ebit).abs()

            dep_val = df_indirect_cf.loc[common_is_cf].get('DepreciationAndAmortization', pd.Series(0, index=common_is_cf)).fillna(0)
            calc_ebitda = calc_ebit + dep_val
            ebitda_gap = (cf_ni_anchor - calc_ebitda).abs()
            
            pbt_tolerance = calc_pretax.abs() * 0.05
            ebit_tolerance = calc_ebit.abs() * 0.05
            ebitda_tolerance = calc_ebitda.abs() * 0.05
            
            is_pbt_match = pbt_gap <= pbt_tolerance
            is_ebit_match = ebit_gap <= ebit_tolerance
            is_ebitda_match = ebitda_gap <= ebitda_tolerance
            
            indirect_ni_check = indirect_ni_check | is_pbt_match | is_ebit_match | is_ebitda_match

        # SOURCE-AWARE OCF RECONCILIATION & PLUG 
#
        is_screener = ('DataSource' in df_indirect_cf.columns) and (str(df_indirect_cf['DataSource'].iloc[0]).strip().lower() == 'screener')
        
        if is_screener:
            if not indirect_ni_check.all():
                print("(!) Screener Anchor contains hidden non-cash items. Bypassing strict IS Anchor verification.")
                indirect_ni_check = pd.Series(True, index=common_is_cf)

            print("(!) Screener Source: Bypassing Depreciation in OCF calc to prevent double-count...")
            calc_ocf_base = (df_indirect_cf['NetIncome'] + 
                             # Depreciation EXCLUDED
                             df_indirect_cf['OtherNonCashAdjustments'] + 
                             df_indirect_cf['ChangeInAccountsReceivable'] + 
                             df_indirect_cf['ChangeInInventory'] + 
                             df_indirect_cf['ChangeInAccountsPayable'] + 
                             df_indirect_cf['OtherWorkingCapitalChanges'] +
                            df_indirect_cf['IncomeTaxPaid'].fillna(0))
                         
        else:
            calc_ocf_base = (df_indirect_cf['NetIncome'] + 
                             df_indirect_cf['DepreciationAndAmortization'] + 
                             df_indirect_cf['OtherNonCashAdjustments'] + 
                             df_indirect_cf['ChangeInAccountsReceivable'] + 
                             df_indirect_cf['ChangeInInventory'] + 
                             df_indirect_cf['ChangeInAccountsPayable'] + 
                             df_indirect_cf['OtherWorkingCapitalChanges'])
                            # df_indirect_cf['IncomeTaxPaid'].fillna(0))

        # Base Calculations for Investing and Financing
        calc_icf_base = (df_indirect_cf['CapExPurchaseOfPPE'] + 
                         df_indirect_cf['PurchaseSaleOfInvestments'] + 
                         df_indirect_cf['OtherInvestingActivities'])
                         
        calc_fcf_base = (df_indirect_cf['NetDebtIssuedRepaid'] + 
                         df_indirect_cf['NetStockIssuedRepurchased'] + 
                         df_indirect_cf['DividendsPaid'] + 
                         df_indirect_cf['OtherFinancingActivities'])

        # Calculate missing gaps for all three sections
        gap_ocf = df_indirect_cf['TotalOperatingCashFlow'] - calc_ocf_base
        gap_icf = df_indirect_cf['TotalInvestingCashFlow'] - calc_icf_base
        gap_fcf = df_indirect_cf['TotalFinancingCashFlow'] - calc_fcf_base
        
        # Initialize the 3 compartmentalized plug columns
        df_indirect_cf['Unmapped_Operating'] = 0.0  
        df_indirect_cf['Unmapped_Investing'] = 0.0  
        df_indirect_cf['Unmapped_Financing'] = 0.0  
        
        # Inject the gaps only if they exceed API rounding dust (e.g., 5.0 scaled)
        for date in df_indirect_cf.index:
            if abs(gap_ocf[date]) > 5:
                df_indirect_cf.at[date, 'Unmapped_Operating'] = gap_ocf[date]
                print(f"   -> [{date}] OCF Leak: Plugging {gap_ocf[date]:.2f} into Unmapped_Operating")
            if abs(gap_icf[date]) > 5:
                df_indirect_cf.at[date, 'Unmapped_Investing'] = gap_icf[date]
                print(f"   -> [{date}] ICF Leak: Plugging {gap_icf[date]:.2f} into Unmapped_Investing")
            if abs(gap_fcf[date]) > 5:
                df_indirect_cf.at[date, 'Unmapped_Financing'] = gap_fcf[date]
                print(f"   -> [{date}] FCF Leak: Plugging {gap_fcf[date]:.2f} into Unmapped_Financing")

        # Calculate final section totals including the new plugs
        calc_ocf_final = calc_ocf_base + df_indirect_cf['Unmapped_Operating']
        calc_icf_final = calc_icf_base + df_indirect_cf['Unmapped_Investing']
        calc_fcf_final = calc_fcf_base + df_indirect_cf['Unmapped_Financing']
        
        # Verify Operating Waterfall
        ocf_gap_final = (df_indirect_cf['TotalOperatingCashFlow'] - calc_ocf_final).abs()
        indirect_ocf_check = ocf_gap_final <= (df_indirect_cf['TotalOperatingCashFlow'].abs() * 0.05)

        # --- 3. RELAXED BOTTOM-LINE CHECKS WITH FX PLUG ---
        dust_tolerance = 15.0

        calc_net_change = calc_ocf_final + calc_icf_final + calc_fcf_final
        indirect_net_change_check = (df_indirect_cf['NetChangeInCash'] - calc_net_change).abs() <= dust_tolerance

        # Base Rollforward
        calc_ending = (df_indirect_cf['BeginningCash'] + 
                       df_indirect_cf['NetChangeInCash'] +
                       df_indirect_cf['EffectOfExchangeRates'].fillna(0))
        
# Initialize the transparent Rollforward Plug
        df_indirect_cf['Unmapped_Rollforward'] = 0.0
        
        rollforward_gap = df_indirect_cf['EndingCash'] - calc_ending
        
        # Route unmapped cash directly into the tracking column
        for date in df_indirect_cf.index:
            if abs(rollforward_gap[date]) > dust_tolerance or df_indirect_cf.at[date, 'BeginningCash'] == 0:
                print(f"   -> [{date}] Rollforward Mismatch: Plugging {rollforward_gap[date]:.2f} into Unmapped_Rollforward")
                df_indirect_cf.at[date, 'Unmapped_Rollforward'] = rollforward_gap[date]
                
        # Final Verification including the plug
        calc_ending_final = calc_ending + df_indirect_cf['Unmapped_Rollforward']
        indirect_rollforward_check = (df_indirect_cf['EndingCash'] - calc_ending_final).abs() <= dust_tolerance


        audit_dict.update({
            'Indirect_CF_NI_Match': indirect_ni_check,
            'Indirect_CF_OCF_Match': indirect_ocf_check,
            'Indirect_CF_NetChange_Match': indirect_net_change_check,
            'Indirect_CF_Rollforward': indirect_rollforward_check
        })

    audit_report = pd.DataFrame(audit_dict)
    
    # RETURN BOTH the audit report AND the modified DataFrames (resetting the index back to normal)
    if df_indirect_cf is not None:
        return audit_report, df_indirect_cf.reset_index()
    else:
        return audit_report

In [24]:
target_tickers = ["ADANIPOWER.NS"
] 
failed_tickers = []

print("\n" + "="*40)
print("STARTING BATCH PROCESSING")
print("="*40)

for ticker in target_tickers:

    # FETCH UNIFIED PAYLOAD
 
    payload = fetch_all_financials(ticker)
    
    if not payload:
        failed_tickers.append(ticker)
        continue 
        
    source = payload["source"]
    data = payload["data"]
    
 
    # UNPACK TO DATAFRAMES

    print(f"[{ticker}] Formatting DataFrames for {source}...")
    
    if source == "yfinance":
        dfIncomeStatementQ = pd.DataFrame(data["is_q"])
        dfIncomeStatementY = pd.DataFrame(data["is_y"])
        dfBalanceSheetQ = pd.DataFrame(data["bs_q"])
        dfBalanceSheetY = pd.DataFrame(data["bs_y"])
        dfCashFlowY = pd.DataFrame(data["cf_y"])
        dfCashFlowQ = pd.DataFrame(data["cf_q"]) if data["cf_q"] is not None else None
        
    elif source == "vantage":
        dfIncomeStatementQ = pd.DataFrame(data["is"]["quarterlyReports"]).set_index("fiscalDateEnding").rename_axis(None).T
        dfIncomeStatementY = pd.DataFrame(data["is"]["annualReports"]).set_index("fiscalDateEnding").rename_axis(None).T
        dfBalanceSheetQ = pd.DataFrame(data["bs"]["quarterlyReports"]).set_index("fiscalDateEnding")
        dfBalanceSheetY = pd.DataFrame(data["bs"]["annualReports"]).set_index("fiscalDateEnding")
        dfCashFlowQ = pd.DataFrame(data["cf"]["quarterlyReports"]).set_index("fiscalDateEnding")
        dfCashFlowY = pd.DataFrame(data["cf"]["annualReports"]).set_index("fiscalDateEnding")
        
    elif source == "screener":
        dfIncomeStatementQ = pd.DataFrame(data["is_q"])
        dfIncomeStatementY = pd.DataFrame(data["is_y"])
        dfBalanceSheetY = pd.DataFrame(data["bs_y"])
        dfCashFlowY = pd.DataFrame(data["cf_y"])
        dfBalanceSheetQ = None 
        dfCashFlowQ = None


    #  UNIFIED CLEANING & MAPPING

    print(f"[{ticker}] Cleaning and Mapping Data...")

    if source == 'vantage':
        stmt_currency = 'USD'
        stmt_multiplier = 0.000001
    elif source == 'yfinance':
        stmt_currency = yf.Ticker(ticker).info.get('currency', 'USD') 
        stmt_multiplier = 0.000001
    elif source == 'screener':
        stmt_currency = 'INR'
        stmt_multiplier = 10.0

    # Base Pre-Processing
    if dfIncomeStatementY is not None: dfIncomeStatementY = clean_financial_dataframe(standardize_dataframe_labels(to_pascal_case(dfIncomeStatementY)))
    if dfIncomeStatementQ is not None: dfIncomeStatementQ = clean_financial_dataframe(standardize_dataframe_labels(to_pascal_case(dfIncomeStatementQ)))
    if dfBalanceSheetY is not None: dfBalanceSheetY = clean_financial_dataframe(standardize_dataframe_labels(to_pascal_case(dfBalanceSheetY)))
    if dfBalanceSheetQ is not None: dfBalanceSheetQ = clean_financial_dataframe(standardize_dataframe_labels(to_pascal_case(dfBalanceSheetQ)))
    if dfCashFlowY is not None: dfCashFlowY = clean_financial_dataframe(standardize_dataframe_labels(to_pascal_case(dfCashFlowY)))
    if dfCashFlowQ is not None: dfCashFlowQ = clean_financial_dataframe(standardize_dataframe_labels(to_pascal_case(dfCashFlowQ)))

    # Screener-Specific Conversions
    if source == 'screener':
        if dfIncomeStatementQ is not None: dfIncomeStatementQ = convert_screener_percentages_to_absolute(dfIncomeStatementQ)
        if dfIncomeStatementY is not None: dfIncomeStatementY = convert_screener_percentages_to_absolute(dfIncomeStatementY)

    # Dictionary Mapping & Fallback Application
    if source in ['yfinance', 'screener']:
        is_keys = ittelson_income_statement_columns + ['PretaxIncome', 'MaterialCost', 'ManufacturingCost', 'EmployeeCost', 'OtherCost']
        bs_keys = ittelson_balance_sheet_columns + ['CashEquivalents', 'Investments', 'LoansNAdvances', 'OtherAssetItems', 'TradePayables', 'AdvanceFromCustomers', 'ShortTermBorrowings', 'LeaseLiabilities', 'LongTermBorrowings', 'OtherBorrowings', 'OtherLiabilityItems', 'Borrowings', 'OtherLiabilities']
        cf_keys = ittelson_cash_flow_columns + ['IssuanceOfDebt', 'RepaymentOfDebt', 'NetCashFlow']
        cf_indirect_keys = ittelson_indirect_cf_columns + ['IssuanceOfDebt', 'RepaymentOfDebt', 'NetCashFlow']
        
        if dfIncomeStatementQ is not None: dfIncomeStatementQ_calc = apply_income_statement_fallbacks(map_statement_via_dictionary(dfIncomeStatementQ, normalized_is_synonym_map, is_keys), ittelson_income_statement_columns)
        if dfIncomeStatementY is not None:
            df_norm_is_y = map_statement_via_dictionary(dfIncomeStatementY, normalized_is_synonym_map, is_keys).iloc[:, :-1]
            if source == 'yfinance': df_norm_is_y = df_norm_is_y.iloc[:,:-1] 
            dfIncomeStatementY_calc = apply_income_statement_fallbacks(df_norm_is_y, ittelson_income_statement_columns)
            
        if dfBalanceSheetQ is not None: dfBalanceSheetQ_calc = apply_balance_sheet_fallbacks(map_statement_via_dictionary(dfBalanceSheetQ, normalized_bs_synonym_map, bs_keys), ittelson_balance_sheet_columns)
        if dfBalanceSheetY is not None: dfBalanceSheetY_calc = apply_balance_sheet_fallbacks(map_statement_via_dictionary(dfBalanceSheetY, normalized_bs_synonym_map, bs_keys), ittelson_balance_sheet_columns)
            
        if dfCashFlowQ is not None: dfCashFlowQ_calc = apply_cash_flow_fallbacks(map_statement_via_dictionary(dfCashFlowQ, normalized_cf_synonym_map, cf_keys), ittelson_cash_flow_columns, df_is_calc=dfIncomeStatementQ_calc, df_bs_calc=dfBalanceSheetQ_calc)
        if dfCashFlowY is not None: dfCashFlowY_calc = apply_cash_flow_fallbacks(map_statement_via_dictionary(dfCashFlowY, normalized_cf_synonym_map, cf_keys), ittelson_cash_flow_columns, df_is_calc=dfIncomeStatementY_calc, df_bs_calc=dfBalanceSheetY_calc)
            
        if dfCashFlowY is not None: dfInDirectCashFlowY_calc = apply_indirect_cash_flow_fallbacks(map_statement_via_dictionary(dfCashFlowY, normalized_indirect_cf_synonym_map, cf_indirect_keys, bucket_columns=indirect_cf_buckets), ittelson_indirect_cf_columns, df_is_calc=dfIncomeStatementY_calc, df_bs_calc=dfBalanceSheetY_calc)

    else:
        dfIncomeStatementQ_calc = dfIncomeStatementQ
        dfIncomeStatementY_calc = dfIncomeStatementY
        dfBalanceSheetQ_calc = dfBalanceSheetQ
        dfBalanceSheetY_calc = dfBalanceSheetY
        dfCashFlowQ_calc = dfCashFlowQ
        dfCashFlowY_calc = dfCashFlowY
        dfInDirectCashFlowY_calc = dfCashFlowY

    # Format for Database
    clean_yearly_income_statement = format_statement_for_db(dfIncomeStatementY_calc, ittelson_income_statement_columns, ticker, currency=stmt_currency, data_source=source, multiplier=stmt_multiplier, transpose=True).replace('None', np.nan)
    clean_yearly_balance_sheet = format_statement_for_db(dfBalanceSheetY_calc, ittelson_balance_sheet_columns, ticker, currency=stmt_currency, data_source=source, multiplier=stmt_multiplier, transpose=True).replace('None', np.nan)
    clean_yearly_cash_flow = format_statement_for_db(dfCashFlowY_calc, ittelson_cash_flow_columns, ticker, currency=stmt_currency, data_source=source, multiplier=stmt_multiplier, transpose=True).replace('None', np.nan)
    clean_yearly_indirect_cash_flow = format_statement_for_db(dfInDirectCashFlowY_calc, ittelson_indirect_cf_columns, ticker, currency=stmt_currency, data_source=source, multiplier=stmt_multiplier, transpose=True).replace('None', np.nan)

    if dfIncomeStatementQ is not None: clean_quarterly_income_statement = format_statement_for_db(dfIncomeStatementQ_calc, ittelson_income_statement_columns, ticker, currency=stmt_currency, data_source=source, multiplier=stmt_multiplier, transpose=True).replace('None', np.nan)
    if dfBalanceSheetQ is not None: clean_quarterly_balance_sheet = format_statement_for_db(dfBalanceSheetQ_calc, ittelson_balance_sheet_columns, ticker, currency=stmt_currency, data_source=source, multiplier=stmt_multiplier, transpose=True).replace('None', np.nan)
    if dfCashFlowQ is not None: clean_quarterly_cash_flow = format_statement_for_db(dfCashFlowQ_calc, ittelson_cash_flow_columns, ticker, currency=stmt_currency, data_source=source, multiplier=stmt_multiplier, transpose=True).replace('None', np.nan)


    # VALIDATE & FLAG
 
    audit_results_Y, clean_yearly_indirect_cash_flow = validate_financial_statements(
        clean_yearly_income_statement, 
        clean_yearly_balance_sheet, 
        clean_yearly_cash_flow, 
        clean_yearly_indirect_cash_flow
    )
    
    clean_yearly_income_statement['IsValid'] = clean_yearly_income_statement['ReportDate'].map(audit_results_Y['IS_IsValid']).fillna(False)
    clean_yearly_balance_sheet['IsValid'] = clean_yearly_balance_sheet['ReportDate'].map(audit_results_Y['BS_IsValid']).fillna(False)
    clean_yearly_cash_flow['IsValid'] = clean_yearly_cash_flow['ReportDate'].map(audit_results_Y['Direct_CF_Match']).fillna(False)
    clean_yearly_indirect_cash_flow['IsValid'] = clean_yearly_indirect_cash_flow['ReportDate'].map(audit_results_Y['Indirect_CF_Rollforward']).fillna(False)

   
    # UPSERT TO POSTGRES
  
    print(f"[{ticker}] Upserting Validated Data to Postgres...")
    
    clean_yearly_income_statement.to_sql(name='yearly_income_statement', con=engine, schema='public', if_exists='append', index=False, method=postgres_upsert)
    clean_yearly_balance_sheet.to_sql(name='yearly_balance_sheet', con=engine, schema='public', if_exists='append', index=False, method=postgres_upsert)
    clean_yearly_cash_flow.to_sql(name='yearly_cash_flow', con=engine, schema='public', if_exists='append', index=False, method=postgres_upsert)
    clean_yearly_indirect_cash_flow.to_sql(name='yearly_indirect_cash_flow', con=engine, schema='public', if_exists='append', index=False, method=postgres_upsert)
    
    # Do the same for Q statements if they exist
    if dfIncomeStatementQ is not None: clean_quarterly_income_statement.to_sql(name='quarterly_income_statement', con=engine, schema='public', if_exists='append', index=False, method=postgres_upsert)
    if dfBalanceSheetQ is not None: clean_quarterly_balance_sheet.to_sql(name='quarterly_balance_sheet', con=engine, schema='public', if_exists='append', index=False, method=postgres_upsert)
    if dfCashFlowQ is not None: clean_quarterly_cash_flow.to_sql(name='quarterly_cash_flow', con=engine, schema='public', if_exists='append', index=False, method=postgres_upsert)
    
 
    #  SLEEP
  
    print(f"[{ticker}] Processing complete. Pausing for rate limits...")
    time.sleep(12) 

# End of loop summary
print("\n" + "="*40)
print("BATCH PROCESSING COMPLETE")
if failed_tickers:
    print(f"Failed tickers requiring review: {failed_tickers}")
else:
    print("All tickers processed successfully.")
print("="*40)

========================================
STARTING BATCH PROCESSING
========================================

========================================
[ADANIPOWER.NS] INITIATING DATA FETCH
========================================
[ADANIPOWER.NS] Attempting YFinance...
Loading yfinance offline_statements\yfinance_ADANIPOWER.NS_INCOME_STATEMENT_quarterly.json from local cache
Loading yfinance offline_statements\yfinance_ADANIPOWER.NS_INCOME_STATEMENT_yearly.json from local cache
Loading yfinance offline_statements\yfinance_ADANIPOWER.NS_BALANCE_SHEET_quarterly.json from local cache
Loading yfinance offline_statements\yfinance_ADANIPOWER.NS_BALANCE_SHEET_yearly.json from local cache
Loading yfinance offline_statements\yfinance_ADANIPOWER.NS_CASH_FLOW_yearly.json from local cache
[ADANIPOWER.NS] SUCCESS: Complete YFinance dataset acquired.
Fetching ADANIPOWER.NS CASH_FLOW from Yfinance
No quarterly CASH_FLOW available from yfinance
[ADANIPOWER.NS] Formatting DataFrames for yfinance...
[ADANIPOWER.NS] Cleaning and Mapping Data...
RUNNING 3-STATEMENT VALIDATION

--- DIRECT STATEMENTS AUDIT ---
(!) BALANCE SHEET LEAK DETECTED:
   -> [2022-03-31] Assets: 0.00 | Calculated L+E: -95824.90 | Gap: 95824.90
Income Statement Equation (GP - Opex = OpInc): PERFECT MATCH
BS/CF Cash Link (Ending Cash): PERFECT MATCH
Direct Cash Flow Equation: PERFECT MATCH

INDIRECT CASH FLOW AUDIT
(!) Strict NI match failed. Cascading through PBT, EBIT, and EBITDA anchors...
   -> [2026-03-31] OCF Leak: Plugging 2494.70 into Unmapped_Operating
   -> [2026-03-31] ICF Leak: Plugging 194.70 into Unmapped_Investing
   -> [2026-03-31] FCF Leak: Plugging -1704.20 into Unmapped_Financing
   -> [2025-03-31] OCF Leak: Plugging 596.70 into Unmapped_Operating
   -> [2025-03-31] ICF Leak: Plugging 436.00 into Unmapped_Investing
   -> [2025-03-31] FCF Leak: Plugging 27194.40 into Unmapped_Financing
   -> [2024-03-31] OCF Leak: Plugging -498.90 into Unmapped_Operating
   -> [2024-03-31] ICF Leak: Plugging 3761.30 into Unmapped_Investing
   -> [2023-03-31] OCF Leak: Plugging -699.70 into Unmapped_Operating
   -> [2023-03-31] ICF Leak: Plugging 56.60 into Unmapped_Investing
   -> [2023-03-31] FCF Leak: Plugging -12058.80 into Unmapped_Financing
   -> [2022-03-31] Rollforward Mismatch: Plugging 3828.00 into Unmapped_Rollforward
[ADANIPOWER.NS] Upserting Validated Data to Postgres...
[ADANIPOWER.NS] Processing complete. Pausing for rate limits...

========================================
BATCH PROCESSING COMPLETE
All tickers processed successfully.
========================================

In [25]:
dfIS = dfIncomeStatementY
display(dfIS)

,2026-03-31,2025-03-31,2024-03-31,2023-03-31,2022-03-31
TaxEffectOfUnusualItems,0.00,0.00,650850000.00,2778600000.00,NaN
TaxRateForCalcs,0.16,0.22,0.30,0.30,NaN
NormalizedEbitda,234308700000.00,240081800000.00,275853200000.00,130923400000.00,NaN
TotalUnusualItems,NaN,-1991200000.00,2169500000.00,9262000000.00,-1009100000.00
TotalUnusualItemsExcludingGoodwill,NaN,-1991200000.00,2169500000.00,9262000000.00,-1009100000.00
NetIncomeFromContinuingOperationNetMinorityInterest,128343000000.00,129387700000.00,208287900000.00,107266400000.00,NaN
ReconciledDepreciation,45645300000.00,43088800000.00,39313300000.00,33036800000.00,NaN
ReconciledCostOfRevenue,299351000000.00,310893300000.00,302927300000.00,271885200000.00,NaN
Ebitda,234308700000.00,240081800000.00,278022700000.00,140185400000.00,NaN
Ebit,188663400000.00,196993000000.00,238709400000.00,107148600000.00,NaN
NetInterestIncome,-33668300000.00,-33397900000.00,55871600000.00,3877600000.00,NaN
InterestExpense,33668300000.00,33397900000.00,30794300000.00,30401600000.00,NaN
InterestIncome,NaN,14439600000.00,89211100000.00,36071900000.00,35582700000.00
NormalizedIncome,128343000000.00,129387700000.00,206769250000.00,100783000000.00,NaN
NetIncomeFromContinuingAndDiscontinuedOperation,128343000000.00,129387700000.00,208287900000.00,107266400000.00,NaN
TotalExpenses,389989400000.00,392065300000.00,353036100000.00,314147400000.00,NaN
RentExpenseSupplemental,NaN,139400000.00,167500000.00,106000000.00,56900000.00
DilutedAverageShares,19387160121.00,20029055728.00,19284694705.00,19284694705.00,NaN
BasicAverageShares,19387160121.00,20029055728.00,19284694705.00,19284694705.00,NaN
DilutedEps,6.62,6.46,10.32,4.91,NaN
BasicEps,6.62,6.46,10.32,4.91,NaN
DilutedNiavailtoComStockholders,128343000000.00,129387700000.00,199094800000.00,94749900000.00,NaN
NetIncomeCommonStockholders,128343000000.00,129387700000.00,199094800000.00,94749900000.00,NaN
OtherunderPreferredStockDividend,0.00,0.00,9193100000.00,12516500000.00,NaN
PreferredStockDividends,NaN,0.00,0.00,0.00,0.00
NetIncome,128343000000.00,129387700000.00,208287900000.00,107266400000.00,NaN
MinorityInterests,-1367800000.00,1891600000.00,NaN,NaN,0.00
NetIncomeIncludingNoncontrollingInterests,129710800000.00,127496100000.00,208287900000.00,107266400000.00,NaN
NetIncomeContinuousOperations,129710800000.00,127496100000.00,208287900000.00,107266400000.00,NaN
TaxProvision,25284300000.00,36099000000.00,-372800000.00,-30519400000.00,NaN
PretaxIncome,154995100000.00,163595100000.00,207915100000.00,76747000000.00,NaN
OtherNonOperatingIncomeExpenses,36247600000.00,27027400000.00,1402900000.00,1101200000.00,NaN
SpecialIncomeCharges,NaN,-1496600000.00,1784500000.00,7841700000.00,-1070800000.00
OtherSpecialCharges,NaN,1128900000.00,-1859800000.00,-7928500000.00,1066900000.00
WriteOff,NaN,367700000.00,75300000.00,86800000.00,3900000.00
NetNonOperatingInterestIncomeExpense,-33668300000.00,-33397900000.00,55871600000.00,3877600000.00,NaN
TotalOtherFinanceCost,NaN,1730400000.00,2545200000.00,1792700000.00,1459100000.00
InterestExpenseNonOperating,33668300000.00,33397900000.00,30794300000.00,30401600000.00,NaN
InterestIncomeNonOperating,NaN,14439600000.00,89211100000.00,36071900000.00,35582700000.00
OperatingIncome,152415800000.00,169965600000.00,147474600000.00,66082900000.00,NaN
OperatingExpense,90638400000.00,81172000000.00,50108800000.00,42262200000.00,NaN
OtherOperatingExpenses,36441300000.00,30239200000.00,5890900000.00,4645300000.00,NaN
DepreciationAndAmortizationInIncomeStatement,45645300000.00,43088800000.00,39313300000.00,33036800000.00,NaN
Amortization,NaN,59200000.00,45000000.00,NaN,NaN
DepreciationIncomeStatement,45645300000.00,43088800000.00,39268300000.00,33036800000.00,NaN
SellingGeneralAndAdministration,NaN,3741200000.00,3147300000.00,2576600000.00,1643300000.00
GeneralAndAdministrativeExpense,NaN,3741200000.00,3147300000.00,2576600000.00,1643300000.00
RentAndLandingFees,NaN,139400000.00,167500000.00,106000000.00,56900000.00
GrossProfit,243054200000.00,251137600000.00,197583400000.00,108345100000.00,NaN
CostOfRevenue,299351000000.00,310893300000.00,302927300000.00,271885200000.00,NaN
TotalRevenue,542405200000.00,562030900000.00,500510700000.00,380230300000.00,NaN
OperatingRevenue,542405200000.00,562030900000.00,500510700000.00,380230300000.00,NaN

In [26]:
dfBS = dfBalanceSheetY
display(dfIS)

,2026-03-31,2025-03-31,2024-03-31,2023-03-31,2022-03-31
TaxEffectOfUnusualItems,0.00,0.00,650850000.00,2778600000.00,NaN
TaxRateForCalcs,0.16,0.22,0.30,0.30,NaN
NormalizedEbitda,234308700000.00,240081800000.00,275853200000.00,130923400000.00,NaN
TotalUnusualItems,NaN,-1991200000.00,2169500000.00,9262000000.00,-1009100000.00
TotalUnusualItemsExcludingGoodwill,NaN,-1991200000.00,2169500000.00,9262000000.00,-1009100000.00
NetIncomeFromContinuingOperationNetMinorityInterest,128343000000.00,129387700000.00,208287900000.00,107266400000.00,NaN
ReconciledDepreciation,45645300000.00,43088800000.00,39313300000.00,33036800000.00,NaN
ReconciledCostOfRevenue,299351000000.00,310893300000.00,302927300000.00,271885200000.00,NaN
Ebitda,234308700000.00,240081800000.00,278022700000.00,140185400000.00,NaN
Ebit,188663400000.00,196993000000.00,238709400000.00,107148600000.00,NaN
NetInterestIncome,-33668300000.00,-33397900000.00,55871600000.00,3877600000.00,NaN
InterestExpense,33668300000.00,33397900000.00,30794300000.00,30401600000.00,NaN
InterestIncome,NaN,14439600000.00,89211100000.00,36071900000.00,35582700000.00
NormalizedIncome,128343000000.00,129387700000.00,206769250000.00,100783000000.00,NaN
NetIncomeFromContinuingAndDiscontinuedOperation,128343000000.00,129387700000.00,208287900000.00,107266400000.00,NaN
TotalExpenses,389989400000.00,392065300000.00,353036100000.00,314147400000.00,NaN
RentExpenseSupplemental,NaN,139400000.00,167500000.00,106000000.00,56900000.00
DilutedAverageShares,19387160121.00,20029055728.00,19284694705.00,19284694705.00,NaN
BasicAverageShares,19387160121.00,20029055728.00,19284694705.00,19284694705.00,NaN
DilutedEps,6.62,6.46,10.32,4.91,NaN
BasicEps,6.62,6.46,10.32,4.91,NaN
DilutedNiavailtoComStockholders,128343000000.00,129387700000.00,199094800000.00,94749900000.00,NaN
NetIncomeCommonStockholders,128343000000.00,129387700000.00,199094800000.00,94749900000.00,NaN
OtherunderPreferredStockDividend,0.00,0.00,9193100000.00,12516500000.00,NaN
PreferredStockDividends,NaN,0.00,0.00,0.00,0.00
NetIncome,128343000000.00,129387700000.00,208287900000.00,107266400000.00,NaN
MinorityInterests,-1367800000.00,1891600000.00,NaN,NaN,0.00
NetIncomeIncludingNoncontrollingInterests,129710800000.00,127496100000.00,208287900000.00,107266400000.00,NaN
NetIncomeContinuousOperations,129710800000.00,127496100000.00,208287900000.00,107266400000.00,NaN
TaxProvision,25284300000.00,36099000000.00,-372800000.00,-30519400000.00,NaN
PretaxIncome,154995100000.00,163595100000.00,207915100000.00,76747000000.00,NaN
OtherNonOperatingIncomeExpenses,36247600000.00,27027400000.00,1402900000.00,1101200000.00,NaN
SpecialIncomeCharges,NaN,-1496600000.00,1784500000.00,7841700000.00,-1070800000.00
OtherSpecialCharges,NaN,1128900000.00,-1859800000.00,-7928500000.00,1066900000.00
WriteOff,NaN,367700000.00,75300000.00,86800000.00,3900000.00
NetNonOperatingInterestIncomeExpense,-33668300000.00,-33397900000.00,55871600000.00,3877600000.00,NaN
TotalOtherFinanceCost,NaN,1730400000.00,2545200000.00,1792700000.00,1459100000.00
InterestExpenseNonOperating,33668300000.00,33397900000.00,30794300000.00,30401600000.00,NaN
InterestIncomeNonOperating,NaN,14439600000.00,89211100000.00,36071900000.00,35582700000.00
OperatingIncome,152415800000.00,169965600000.00,147474600000.00,66082900000.00,NaN
OperatingExpense,90638400000.00,81172000000.00,50108800000.00,42262200000.00,NaN
OtherOperatingExpenses,36441300000.00,30239200000.00,5890900000.00,4645300000.00,NaN
DepreciationAndAmortizationInIncomeStatement,45645300000.00,43088800000.00,39313300000.00,33036800000.00,NaN
Amortization,NaN,59200000.00,45000000.00,NaN,NaN
DepreciationIncomeStatement,45645300000.00,43088800000.00,39268300000.00,33036800000.00,NaN
SellingGeneralAndAdministration,NaN,3741200000.00,3147300000.00,2576600000.00,1643300000.00
GeneralAndAdministrativeExpense,NaN,3741200000.00,3147300000.00,2576600000.00,1643300000.00
RentAndLandingFees,NaN,139400000.00,167500000.00,106000000.00,56900000.00
GrossProfit,243054200000.00,251137600000.00,197583400000.00,108345100000.00,NaN
CostOfRevenue,299351000000.00,310893300000.00,302927300000.00,271885200000.00,NaN
TotalRevenue,542405200000.00,562030900000.00,500510700000.00,380230300000.00,NaN
OperatingRevenue,542405200000.00,562030900000.00,500510700000.00,380230300000.00,NaN

In [27]:
dfCS = dfCashFlowY
display(dfCS)

,2026-03-31,2025-03-31,2024-03-31,2023-03-31,2022-03-31
FreeCashFlow,-28364400000.00,99420700000.00,115677000000,51868500000.00,NaN
RepurchaseOfCapitalStock,0.00,-5000000000.00,0,NaN,NaN
RepaymentOfDebt,-52404200000.00,-28522900000.00,-305979500000,-269484300000.00,NaN
IssuanceOfDebt,205000000000.00,37132100000.00,245681400000,212054100000.00,NaN
IssuanceOfCapitalStock,0.00,2500000000.00,0,NaN,NaN
CapitalExpenditure,-233500900000.00,-115590400000.00,-26024500000,-32436800000.00,NaN
EndCashPosition,9278800000.00,3198600000.00,11362500000,3492300000.00,NaN
OtherCashAdjustmentOutsideChangeinCash,NaN,NaN,-27100000,3600000.00,2023500000.00
BeginningCashPosition,3198600000.00,11362500000.00,3492300000,7823700000.00,NaN
EffectOfExchangeRateChanges,NaN,0.00,-14200000,0.00,NaN
ChangesInCash,6080200000.00,-8163900000.00,7884400000,-4335000000.00,NaN
FinancingCashFlow,65549300000.00,-51754500000.00,-168640300000,-104084600000.00,NaN
NetOtherFinancingCharges,-44420400000.00,-50981500000.00,-74028900000,-946800000.00,NaN
InterestPaidCff,-40921900000.00,-34076600000.00,-34308600000,-33648800000.00,NaN
NetPreferredStockIssuance,0.00,-3000000000.00,0,NaN,NaN
PreferredStockPayments,0.00,-5000000000.00,0,NaN,NaN
PreferredStockIssuance,0.00,2000000000.00,0,NaN,NaN
NetCommonStockIssuance,0.00,500000000.00,0,NaN,NaN
CommonStockIssuance,0.00,500000000.00,0,NaN,NaN
NetIssuancePaymentsOfDebt,151002200000.00,36036400000.00,-60298100000,-69430700000.00,NaN
NetShortTermDebtIssuance,-1593600000.00,27427200000.00,18965300000,-12000500000.00,NaN
ShortTermDebtIssuance,NaN,27427200000.00,18965300000,NaN,NaN
NetLongTermDebtIssuance,152595800000.00,8609200000.00,-79263400000,-57430200000.00,NaN
LongTermDebtPayments,-52404200000.00,-28522900000.00,-305979500000,-269484300000.00,NaN
LongTermDebtIssuance,205000000000.00,37132100000.00,226716100000,212054100000.00,NaN
InvestingCashFlow,-264605600000.00,-171420500000.00,34823200000,15444300000.00,NaN
NetOtherInvestingChanges,-2336600000.00,4524000000.00,-45448200000,1510800000.00,NaN
InterestReceivedCfi,13395400000.00,8835600000.00,93161900000,48273400000.00,NaN
NetInvestmentPurchaseAndSale,-2465600000.00,-5669600000.00,4063400000,-4577000000.00,NaN
SaleOfInvestment,1374000000.00,0.00,4063400000,0.00,NaN
PurchaseOfInvestment,-3839600000.00,-5669600000.00,0,-4577000000.00,NaN
NetBusinessPurchaseAndSale,-39892600000.00,-63956100000.00,5309300000,2617300000.00,NaN
SaleOfBusiness,NaN,0.00,5335100000,9889000000.00,0.00
PurchaseOfBusiness,-39892600000.00,-63956100000.00,-25800000,-7271700000.00,NaN
NetPpepurchaseAndSale,194000000.00,151600000.00,-26018900000,8300000.00,NaN
SaleOfPpe,194000000.00,151600000.00,5600000,8300000.00,NaN
PurchaseOfPpe,NaN,-115590400000.00,-26024500000,NaN,NaN
CapitalExpenditureReported,-233500900000.00,-115590400000.00,-26024500000,-32436800000.00,NaN
OperatingCashFlow,205136500000.00,215011100000.00,141701500000,84305300000.00,NaN
TaxesRefundPaid,1022600000.00,-83400000.00,-574200000,-786500000.00,NaN
ChangeInWorkingCapital,-4471100000.00,-4401000000.00,-44500800000,-13506000000.00,NaN
ChangeInOtherCurrentLiabilities,-1207200000.00,-6093400000.00,-21398600000,31811800000.00,NaN
ChangeInOtherCurrentAssets,-13565900000.00,469200000.00,-1209000000,-2843100000.00,NaN
ChangeInPayable,-1821600000.00,-8799500000.00,6156200000,-4231600000.00,NaN
ChangeInInventory,-2341000000.00,13126600000.00,-10665000000,-8290600000.00,NaN
ChangeInReceivables,13704000000.00,-3416300000.00,-17384400000,-29952500000.00,NaN
OtherNonCashItems,8980300000.00,13263100000.00,-60710300000,-6191200000.00,NaN
ProvisionandWriteOffofAssets,67000000.00,-64400000.00,1641300000,121300000.00,NaN
DepreciationAndAmortization,45645300000.00,43088800000.00,39313300000,33036800000.00,NaN
AmortizationCashFlow,NaN,59200000.00,45000000,NaN,NaN
Depreciation,45645300000.00,43088800000.00,39268300000,33036800000.00,NaN
GainLossOnInvestmentSecurities,-715100000.00,-972400000.00,-814200000,-7075500000.00,NaN
NetForeignCurrencyExchangeGainLoss,-1099100000.00,-911300000.00,901500000,1016100000.00,NaN
GainLossOnSaleOfPpe,0.00,1128900000.00,783500000,856500000.00,NaN
GainLossOnSaleOfBusiness,NaN,0.00,-2329000000,NaN,NaN
NetIncomeFromContinuingOperations,154995100000.00,163595100000.00,207915100000,76747000000.00,NaN